--
-- PostgreSQL database dump
--

\restrict NhUR1GJm9I0fS4PtG2mhE8uhJzTutIJFf09iIuyDotdVDC7YDdO6dJGJqyM9jrg

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6 (Homebrew)

-- Started on 2025-11-15 09:41:19 GMT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 458 (class 1259 OID 99105)
-- Name: attractions; Type: TABLE; Schema: world; Owner: postgres
--

CREATE TABLE world.attractions (
    id integer NOT NULL,
    city_id character varying(20) NOT NULL,
    title text NOT NULL,
    subtitle text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    price double precision DEFAULT 0 NOT NULL,
    category_name text NOT NULL,
    address text DEFAULT ''::text NOT NULL,
    neighborhood text DEFAULT ''::text NOT NULL,
    street character varying(60) DEFAULT ''::character varying NOT NULL,
    postal_code character varying(20) DEFAULT ''::character varying NOT NULL,
    state character varying(20) DEFAULT ''::character varying NOT NULL,
    city character varying(60) DEFAULT ''::character varying NOT NULL,
    country character varying(50) DEFAULT ''::character varying NOT NULL,
    website text DEFAULT ''::text NOT NULL,
    phone character varying(20) DEFAULT ''::character varying NOT NULL,
    phone_unformatted character varying(20) DEFAULT ''::character varying NOT NULL,
    latitude double precision DEFAULT 0 NOT NULL,
    longitude double precision DEFAULT 0 NOT NULL,
    located_in text DEFAULT ''::text NOT NULL,
    total_score double precision DEFAULT 0 NOT NULL,
    permanently_closed boolean DEFAULT false NOT NULL,
    temporarily_closed boolean DEFAULT false NOT NULL,
    place_id character varying(100) NOT NULL,
    categories jsonb DEFAULT '{}'::jsonb NOT NULL,
    scraped_at timestamp with time zone NOT NULL,
    opening_hours jsonb DEFAULT '{}'::jsonb NOT NULL,
    additional_info jsonb DEFAULT '{}'::jsonb NOT NULL,
    image_url text DEFAULT ''::text NOT NULL
);


ALTER TABLE world.attractions OWNER TO postgres;

--
-- TOC entry 457 (class 1259 OID 99104)
-- Name: attractions_id_seq; Type: SEQUENCE; Schema: world; Owner: postgres
--

CREATE SEQUENCE world.attractions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE world.attractions_id_seq OWNER TO postgres;

--
-- TOC entry 3972 (class 0 OID 0)
-- Dependencies: 457
-- Name: attractions_id_seq; Type: SEQUENCE OWNED BY; Schema: world; Owner: postgres
--

ALTER SEQUENCE world.attractions_id_seq OWNED BY world.attractions.id;


--
-- TOC entry 3784 (class 2604 OID 99108)
-- Name: attractions id; Type: DEFAULT; Schema: world; Owner: postgres
--

ALTER TABLE ONLY world.attractions ALTER COLUMN id SET DEFAULT nextval('world.attractions_id_seq'::regclass);


--
-- TOC entry 3965 (class 0 OID 99105)
-- Dependencies: 458
-- Data for Name: attractions; Type: TABLE DATA; Schema: world; Owner: postgres
--

COPY world.attractions (id, city_id, title, subtitle, description, price, category_name, address, neighborhood, street, postal_code, state, city, country, website, phone, phone_unformatted, latitude, longitude, located_in, total_score, permanently_closed, temporarily_closed, place_id, categories, scraped_at, opening_hours, additional_info, image_url) FROM stdin;
1	IE-dublin	Phoenix Park	Pirc an Fhionnuisce	Wild deer, a zoo & a fort feature in this 708-hectare park known as &apos;Dublin&apos;s playground&apos;.	0		Dublin 8, Ireland					Dublin 8		https://www.phoenixpark.ie/	+353 1 820 5800	+35318205800	53.3558823	-6.3298133		4.7	f	f	ChIJe1F08akNZ0gRa1ndmi3YJqE	["Park", "Tourist attraction"]	2025-11-10 19:00:52.106+00	[{"day": "Monday", "hours": "Open 24 hours"}, {"day": "Tuesday", "hours": "Open 24 hours"}, {"day": "Wednesday", "hours": "Open 24 hours"}, {"day": "Thursday", "hours": "Open 24 hours"}, {"day": "Friday", "hours": "Open 24 hours"}, {"day": "Saturday", "hours": "Open 24 hours"}, {"day": "Sunday", "hours": "Open 24 hours"}]	{"Pets": ["Dog park", "Dogs allowed"], "Parking": ["Free parking lot"], "Children": ["Good for kids", "Good for kids birthday", "Kid-friendly hikes", "Playground"], "Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Amenities": ["Cycling lanes", "Picnic tables", "Public restroom", "Slides", "Swings"], "Activities": ["Hiking"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"], "Service options": ["Onsite services"]}	
2	IE-dublin	Papal Cross		Standing at 35 meters, this steel cross was erected in 1979 for the visit of Pope John Paul II.	0		Phoenix Park, Dublin, Ireland	Phoenix Park				Dublin					53.3566563	-6.3290634		4.6	f	f	ChIJM6zx6gANZ0gR5v0jZCWzmfQ	["Sculpture", "Tourist attraction"]	2025-11-10 19:00:52.106+00	[{"day": "Monday", "hours": "10 AM to 8 PM"}, {"day": "Tuesday", "hours": "10 AM to 8 PM"}, {"day": "Wednesday", "hours": "10 AM to 8 PM"}, {"day": "Thursday", "hours": "10 AM to 8 PM"}, {"day": "Friday", "hours": "10 AM to 8 PM"}, {"day": "Saturday", "hours": "10 AM to 8 PM"}, {"day": "Sunday", "hours": "10 AM to 8 PM"}]	{"Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
3	IE-dublin	Irish National War Memorial Gardens	Gairdn Nisinta Cuimhneachin Cogaidh na hireann	Elegant, Lutyens-designed gardens dedicated to the 49,400 Irish soldiers who died during WWI.	0		Island Bridge, Ushers, Dublin, Ireland	Ushers	Island Bridge			Dublin		https://heritageireland.ie/places-to-visit/irish-national-war-memorial-gardens/			53.3454216	-6.3172574		4.8	f	f	ChIJ018GzlAMZ0gRhtsC7h2srpw	["Memorial park", "Tourist attraction"]	2025-11-10 19:00:52.107+00	[{"day": "Monday", "hours": "Open 24 hours"}, {"day": "Tuesday", "hours": "Open 24 hours"}, {"day": "Wednesday", "hours": "Open 24 hours"}, {"day": "Thursday", "hours": "Open 24 hours"}, {"day": "Friday", "hours": "Open 24 hours"}, {"day": "Saturday", "hours": "Open 24 hours"}, {"day": "Sunday", "hours": "Open 24 hours"}]	{"Pets": ["Dogs allowed"], "Children": ["Good for kids"], "Amenities": ["Cycling lanes", "Picnic tables"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
4	IE-dublin	Irish National War Memorial Park			0		Kilmainham, Dublin, Ireland	Kilmainham				Dublin					53.3444618	-6.3182108		5	f	f	ChIJAQAAMFcMZ0gRzrj364nDBOw	["Park"]	2025-11-10 19:00:52.107+00	[]	{}	
5	IE-dublin	Dublin Heuston	Baile tha Cliath Heuston		0		Heuston Station Saint John&apos;s Road West, Dublin, Ireland	Saint James	Heuston Station Saint John&apos;s Road West			Dublin		http://www.irishrail.ie/travel-information/dublin-heuston			53.3464596	-6.2929845		4.2	f	f	ChIJBfHLsjcMZ0gR6tv-NUFv8bQ	["Train station"]	2025-11-10 19:00:52.107+00	[]	{"Parking": ["Paid parking lot"], "Amenities": ["Baggage storage", "Restroom"], "Getting here": ["24-hour transit available"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"], "Service options": ["Onsite services"]}	
6	IE-dublin	National Museum of Ireland, Collins Barracks		Irish haute couture and silver collections alongside exhibitions exploring Irish military history.	0		Collins Barracks, Benburb St, Stoneybatter, Dublin, D07 XKV4, Ireland	Stoneybatter	Collins Barracks, Benburb St			Dublin		https://www.museum.ie/en-IE/Museums/Decorative-Arts-History	+353 1 677 7444	+35316777444	53.3489404	-6.2863653		4.6	f	f	ChIJS7Q-vDEMZ0gRSvVL0e06s1k	["National museum", "Cultural center", "History museum", "Museum", "Tourist attraction"]	2025-11-10 19:00:52.107+00	[{"day": "Monday", "hours": "1 to 5 PM"}, {"day": "Tuesday", "hours": "10 AM to 5 PM"}, {"day": "Wednesday", "hours": "10 AM to 5 PM"}, {"day": "Thursday", "hours": "10 AM to 5 PM"}, {"day": "Friday", "hours": "10 AM to 5 PM"}, {"day": "Saturday", "hours": "10 AM to 5 PM"}, {"day": "Sunday", "hours": "1 to 5 PM"}]	{"Crowd": ["Family-friendly", "LGBTQ+ friendly"], "Parking": ["On-site parking", "Paid parking lot"], "Children": ["Good for kids", "Has changing table(s)"], "Amenities": ["Cafe", "Offers tours", "Restroom", "Wi-Fi", "Free Wi-Fi", "Restaurant"], "Offerings": ["Gift shop"], "Highlights": ["Live performances"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"], "Service options": ["Onsite services"]}	
7	IE-dublin	Wellington Monument	Leacht Wellington	Imposing 62m obelisk built to commemorate victories of Arthur Wellesley, 1st Duke of Wellington.	0		Phoenix Park, Saint James, Dublin, Ireland	Saint James	Phoenix Park			Dublin			+353 1 647 6635	+35316476635	53.3490364	-6.303101		4.6	f	f	ChIJJy1n5EsMZ0gRwdEqkxUxmHc	["Monument", "Tourist attraction"]	2025-11-10 19:00:52.107+00	[{"day": "Monday", "hours": "Open 24 hours"}, {"day": "Tuesday", "hours": "Open 24 hours"}, {"day": "Wednesday", "hours": "Open 24 hours"}, {"day": "Thursday", "hours": "Open 24 hours"}, {"day": "Friday", "hours": "Open 24 hours"}, {"day": "Saturday", "hours": "Open 24 hours"}, {"day": "Sunday", "hours": "Open 24 hours"}]	{"Parking": ["Free street parking"], "Children": ["Good for kids"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"]}	
8	IE-dublin	Ha&apos;penny Bridge	Droichead na Life	Refurbished 19th-century cast-iron span & city symbol, crossed by thousands of pedestrians daily.	0		Ha&apos;penny Bridge, North City, Dublin, Ireland	North City	Ha&apos;penny Bridge			Dublin		https://www.bridgesofdublin.ie/bridges/hapenny-bridge			53.3463347	-6.2631029		4.5	f	f	ChIJFXuSYYMOZ0gRb7gtcRw21Uc	["Bridge", "Historical landmark", "Tourist attraction"]	2025-11-10 19:00:52.108+00	[{"day": "Monday", "hours": "Open 24 hours"}, {"day": "Tuesday", "hours": "Open 24 hours"}, {"day": "Wednesday", "hours": "Open 24 hours"}, {"day": "Thursday", "hours": "Open 24 hours"}, {"day": "Friday", "hours": "Open 24 hours"}, {"day": "Saturday", "hours": "Open 24 hours"}, {"day": "Sunday", "hours": "Open 24 hours"}]	{"Amenities": ["Restroom"], "Accessibility": ["Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
9	IE-dublin	The Brazen Head		Meeting place for historic rebels, this brass-filled, lantern-lit pub hosts live music each night.	0		20 Bridge St. Lower, Usher&apos;s Quay, Dublin, D08 WC64, Ireland	Usher&apos;s Quay	20 Bridge St. Lower			Dublin		http://www.brazenhead.com/	+353 1 679 5186	+35316795186	53.3449326	-6.2763323		4.5	f	f	ChIJ5wqZWS8MZ0gRq5auJO7NbDE	["Irish pub", "Restaurant"]	2025-11-10 19:00:52.108+00	[{"day": "Monday", "hours": "12 to 11:30 PM"}, {"day": "Tuesday", "hours": "12 to 11:30 PM"}, {"day": "Wednesday", "hours": "12 to 11:30 PM"}, {"day": "Thursday", "hours": "12 to 11:30 PM"}, {"day": "Friday", "hours": "12 to 11:30 PM"}, {"day": "Saturday", "hours": "12 to 11:30 PM"}, {"day": "Sunday", "hours": "12 to 11:30 PM"}]	{"Crowd": ["College students", "Groups", "Tourists"], "Parking": ["Paid street parking", "Usually difficult to find a space"], "Children": ["High chairs"], "Payments": ["Credit cards", "Debit cards", "NFC mobile payments"], "Planning": ["Brunch reservations recommended", "Lunch reservations recommended", "Dinner reservations recommended", "Accepts reservations"], "Amenities": ["Bar onsite", "Restroom"], "Offerings": ["Alcohol", "Beer", "Cocktails", "Coffee", "Dancing", "Food", "Food at bar", "Hard liquor", "Late-night food", "Private dining room", "Quick bite", "Small plates", "Vegetarian options", "Wine"], "Atmosphere": ["Casual", "Cozy", "Historic", "Trendy"], "Highlights": ["Fireplace", "Great beer selection", "Great cocktails", "Great coffee", "Great dessert", "Live music", "Live performances"], "Popular for": ["Breakfast", "Lunch", "Dinner", "Solo dining"], "Accessibility": ["Wheelchair accessible restroom", "Wheelchair accessible seating", "Wheelchair accessible parking lot"], "Dining options": ["Breakfast", "Brunch", "Lunch", "Dinner", "Dessert", "Seating", "Table service"], "Service options": ["Outdoor seating", "Dine-in", "Delivery", "Takeout"]}	
10	IE-dublin	Hugh Lane Gallery	Dnlann Hugh Lane	Gallery containing the reconstructed studio of Francis Bacon, plus modern European & Irish works.	0		Charlemont House, Parnell Square N, Rotunda, Dublin 1, D01 F2X9, Ireland	Rotunda	Charlemont House, Parnell Square N			Dublin 1		http://www.hughlane.ie/	+353 1 222 5564	+35312225564	53.354177	-6.2646481		4.5	f	t	ChIJE42FqWAMZ0gRhDMWDRn7ksw	["Art museum", "Art gallery", "Museum", "Tourist attraction"]	2025-11-10 19:00:52.108+00	[]	{"Crowd": ["Family-friendly", "LGBTQ+ friendly", "Transgender safespace"], "Parking": ["Paid street parking"], "Children": ["Good for kids"], "Amenities": ["Restaurant", "Restroom", "Wi-Fi", "Free Wi-Fi"], "Highlights": ["Live performances"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"], "Service options": ["Onsite services"]}	
11	IE-dublin	14 Henrietta Street		Tours tell the story of a 1740s house carefully restored to grandeur after falling into disrepair.	0		14 Henrietta St, Dublin 1, D01 HH34, Ireland		14 Henrietta St			Dublin 1		https://14henriettastreet.ie/	+353 1 524 0383	+35315240383	53.3523798	-6.2701587		4.8	f	f	ChIJw39ydyoMZ0gR8-2bO_FERjM	["Museum", "Tourist attraction"]	2025-11-10 19:00:52.108+00	[{"day": "Monday", "hours": "Closed"}, {"day": "Tuesday", "hours": "Closed"}, {"day": "Wednesday", "hours": "10 AM to 4 PM"}, {"day": "Thursday", "hours": "10 AM to 6 PM"}, {"day": "Friday", "hours": "10 AM to 4 PM"}, {"day": "Saturday", "hours": "10 AM to 4 PM"}, {"day": "Sunday", "hours": "10 AM to 4 PM"}]	{"Crowd": ["Family-friendly"], "Parking": ["Paid street parking"], "Children": ["Good for kids"], "Planning": ["Getting tickets in advance recommended"], "Amenities": ["Gender-neutral restroom", "Restroom", "Wi-Fi", "Free Wi-Fi", "Restaurant"], "Highlights": ["Live performances"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible restroom"], "Service options": ["Onsite services"]}	
12	IE-dublin	Light House Cinema		An eclectic schedule of features, shorts, classics, foreign language and animated films.	0		Market St S, Smithfield, Dublin 7, D07 R6YE, Ireland	Smithfield	Market St S			Dublin 7		https://www.lighthousecinema.ie/	+353 1 872 8006	+35318728006	53.3487938	-6.2790491		4.8	f	f	ChIJi15MliMMZ0gRF0OPS9-7BCg	["Movie theater", "Bar", "Cafe", "Event venue"]	2025-11-10 19:00:52.108+00	[]	{"Children": ["Good for kids"], "Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Amenities": ["Restaurant", "Restroom"], "Offerings": ["Food"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom", "Wheelchair accessible seating"], "Service options": ["Onsite services"]}	
13	IE-dublin	TU Dublin, Grangegorman			0		Grangegorman Lower, Dublin 7, D07 H6K8, Ireland		Grangegorman Lower			Dublin 7		https://www.tudublin.ie/	+353 1 220 5000	+35312205000	53.3548669	-6.2794863		4.6	f	f	ChIJZbQuzywMZ0gR7LNOrFuzlpI	["University", "College"]	2025-11-10 19:00:53.159+00	[{"day": "Monday", "hours": "8 AM to 10 PM"}, {"day": "Tuesday", "hours": "8 AM to 10 PM"}, {"day": "Wednesday", "hours": "8 AM to 10 PM"}, {"day": "Thursday", "hours": "8 AM to 10 PM"}, {"day": "Friday", "hours": "8 AM to 10 PM"}, {"day": "Saturday", "hours": "8 AM to 5 PM"}, {"day": "Sunday", "hours": "Closed"}]	{"Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"]}	
14	IE-dublin	McGowans of Phibsboro		Bar bites & hearty comfort food in an old-school, kitschy pub with a beer garden & TVs for sports.	0		18 Phibsborough Rd, Phibsborough, Dublin 7, D07 A562, Ireland	Phibsborough	18 Phibsborough Rd			Dublin 7		https://mcgowans.ie/	+353 1 830 6606	+35318306606	53.356588	-6.273832		4.2	f	f	ChIJ5SSKF28OZ0gRwFzxZdVgaHo	["Bar", "Cocktail bar", "Function room facility", "Night club", "Pub", "Restaurant"]	2025-11-10 19:00:53.159+00	[{"day": "Monday", "hours": "5 PM to 12:30 AM"}, {"day": "Tuesday", "hours": "5 PM to 12:30 AM"}, {"day": "Wednesday", "hours": "5 PM to 2:30 AM"}, {"day": "Thursday", "hours": "5 PM to 2:30 AM"}, {"day": "Friday", "hours": "5 PM to 2:30 AM"}, {"day": "Saturday", "hours": "3 PM to 2:30 AM"}, {"day": "Sunday", "hours": "3 PM to 1:30 AM"}]	{"Crowd": ["Groups", "LGBTQ+ friendly", "Tourists"], "Parking": ["Paid street parking"], "Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Planning": ["Accepts reservations"], "Amenities": ["Restroom", "Wi-Fi", "Free Wi-Fi"], "Offerings": ["Alcohol", "Beer", "Cocktails", "Dancing", "Food", "Food at bar", "Happy hour drinks", "Hard liquor", "Wine"], "Atmosphere": ["Casual", "Trendy"], "Highlights": ["Great beer selection", "Great cocktails", "Great wine list", "Live music", "Live performances", "Sports", "Trivia night"], "Popular for": ["Solo dining"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible restroom", "Wheelchair accessible seating", "Wheelchair accessible parking lot"], "Dining options": ["Seating", "Table service"], "Service options": ["Outdoor seating", "Delivery", "Onsite services", "Takeout", "Dine-in"]}	
15	IE-dublin	Mountjoy Square Park	Cearng Mhuinseo	Leafy Georgian garden with a soccer field & tennis court, plus a playground & 1800s granite sundial.	0		Mountjoy Square, Mountjoy, Dublin, Ireland	Mountjoy	Mountjoy Square			Dublin			+353 1 855 4030	+35318554030	53.3566348	-6.2574474		4.2	f	f	ChIJ3RikV30OZ0gRdGnOXe9xpAM	["Park", "Tourist attraction"]	2025-11-10 19:00:53.159+00	[{"day": "Monday", "hours": "8 AM to 10 PM"}, {"day": "Tuesday", "hours": "8 AM to 10 PM"}, {"day": "Wednesday", "hours": "8 AM to 10 PM"}, {"day": "Thursday", "hours": "8 AM to 10 PM"}, {"day": "Friday", "hours": "8 AM to 10 PM"}, {"day": "Saturday", "hours": "8 AM to 10 PM"}, {"day": "Sunday", "hours": "8 AM to 10 PM"}]	{"Pets": ["Dog park", "Dogs allowed"], "Children": ["Good for kids", "Playground"], "Amenities": ["Basketball court", "Slides", "Swings"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"]}	
16	IE-dublin	Connolly			0		North Wall, Dublin 1, Ireland	North Wall				Dublin 1					53.3518198	-6.2487898		3.5	f	f	ChIJAYw6TYkOZ0gRtokAa9k_W8k	["Train station"]	2025-11-10 19:00:53.159+00	[]	{"Amenities": ["Restroom"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible restroom"]}	
17	IE-dublin	Tara Street	Srid na Teamhrach		0		Tara St, Dublin 2, D02 W597, Ireland		Tara St			Dublin 2		https://www.irishrail.ie/en-ie/station/tara-street			53.3472054	-6.2542182		3.9	f	f	ChIJPWurjI8OZ0gRgRn4fsIACMc	["Train station"]	2025-11-10 19:00:53.159+00	[]	{"Getting here": ["24-hour transit available"], "Accessibility": ["Wheelchair accessible entrance"]}	
18	IE-dublin	EPIC The Irish Emigration Museum			0		The Chq Building, Custom House Quay, North Wall, Dublin 1, Ireland	North Wall	The Chq Building, Custom House Quay			Dublin 1		https://epicchq.com/?utm_source=mybusiness&utm_medium=organic	+353 1 906 0861	+35319060861	53.3483124	-6.2481791		4.6	f	f	ChIJvwEAK4wOZ0gRZ-4HLJnKYZk	["Museum", "Event venue", "Genealogist", "Heritage museum", "History museum", "Local history museum", "National museum", "Tourist attraction", "Visitor center"]	2025-11-10 19:00:53.159+00	[{"day": "Monday", "hours": "10 AM to 5 PM"}, {"day": "Tuesday", "hours": "10:30 AM to 5 PM"}, {"day": "Wednesday", "hours": "10 AM to 5 PM"}, {"day": "Thursday", "hours": "10 AM to 5 PM"}, {"day": "Friday", "hours": "10 AM to 5 PM"}, {"day": "Saturday", "hours": "10 AM to 5 PM"}, {"day": "Sunday", "hours": "10 AM to 5 PM"}]	{"Crowd": ["Family-friendly"], "Children": ["Family discount", "Good for kids", "Has changing table(s)", "Kid-friendly activities"], "Planning": ["Getting tickets in advance recommended"], "Amenities": ["Cafe", "Restaurant", "Restroom", "Wi-Fi", "Free Wi-Fi"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"], "Service options": ["Onsite services"]}	
19	IE-dublin	Kylemore Karting			0		1A, Kylemore Industrial Estate, Killeen Rd, Kylemore, Dublin 10, Ireland	Kylemore	1A, Kylemore Industrial Estate, Killeen Rd			Dublin 10		http://www.kylemorekarting.ie/	+353 1 626 1444	+35316261444	53.3338632	-6.3546976		4.7	f	f	ChIJjaZVDKkOZ0gRNQVpsaHsDKw	["Go-karting venue", "Tourist attraction"]	2025-11-10 19:00:53.159+00	[]	{"Children": ["Good for kids", "Good for kids birthday"], "Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Amenities": ["Restroom", "Restaurant"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"]}	
20	IE-dublin	Kilmainham Gaol	Msaem Phrosn Chill Mhaighneann	Prison museum where many of Ireland&apos;s political prisoners were incarcerated, tortured and executed.	0		Inchicore Rd, Kilmainham, Dublin 8, D08 RK28, Ireland	Kilmainham	Inchicore Rd			Dublin 8		https://www.kilmainhamgaolmuseum.ie/	+353 1 453 5984	+35314535984	53.3418701	-6.3098048		4.7	f	f	ChIJbXwkCloMZ0gRO3zBD1Jo1Bg	["Museum", "Prison", "Tourist attraction"]	2025-11-10 19:00:53.159+00	[{"day": "Monday", "hours": "9:30 AM to 5:45 PM"}, {"day": "Tuesday", "hours": "9:30 AM to 5:45 PM"}, {"day": "Wednesday", "hours": "9:30 AM to 5:45 PM"}, {"day": "Thursday", "hours": "9:30 AM to 5:45 PM"}, {"day": "Friday", "hours": "9:30 AM to 5:45 PM"}, {"day": "Saturday", "hours": "9:30 AM to 5:45 PM"}, {"day": "Sunday", "hours": "9:30 AM to 5:45 PM"}]	{"Children": ["Good for kids"], "Planning": ["Getting tickets in advance recommended"], "Amenities": ["Restaurant", "Restroom"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible restroom"], "Service options": ["Onsite services"]}	
21	IE-dublin	Gravity Climbing Centre		Indoor climbing and bouldering centre with routes and challenges for all ages and abilities.	0		Goldenbridge Industrial Estate, 6a, Inchicore, Dublin 8, Ireland	Inchicore	Goldenbridge Industrial Estate, 6a			Dublin 8		http://www.gravityclimbing.ie/	+353 1 707 8585	+35317078585	53.335754	-6.323554		4.7	f	f	ChIJ8TyY7vUMZ0gRuXnZzxh9YH4	["Rock climbing gym", "Coffee shop", "Store"]	2025-11-10 19:00:53.159+00	[{"day": "Monday", "hours": "12 to 10 PM"}, {"day": "Tuesday", "hours": "12 to 10 PM"}, {"day": "Wednesday", "hours": "12 to 10 PM"}, {"day": "Thursday", "hours": "12 to 10 PM"}, {"day": "Friday", "hours": "12 to 10 PM"}, {"day": "Saturday", "hours": "10 AM to 8 PM"}, {"day": "Sunday", "hours": "10 AM to 8 PM"}]	{"Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom", "Wheelchair accessible seating"], "Service options": ["Onsite services"]}	
22	IE-dublin	Brickfield Park	Pairc Ghort na mBrc		0		345 Mourne Rd, Drimnagh, Dublin, D12 YW88, Ireland	Drimnagh	345 Mourne Rd			Dublin		http://www.dublincity.ie/			53.3320794	-6.3085351		4.5	f	f	ChIJpRpOJOgNZ0gRd7fsewMFW2M	["Park"]	2025-11-10 19:00:53.16+00	[]	{"Pets": ["Dogs allowed"], "Children": ["Good for kids", "Playground"], "Amenities": ["Cycling lanes", "Picnic tables", "Slides", "Swings"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance"]}	
49	IE-dublin	Dublin City University	Ollscoil Chathair Bhaile tha Cliath		0		Collins Ave Ext, Whitehall, Dublin 9, Ireland	Whitehall	Collins Ave Ext			Dublin 9		https://www.dcu.ie/	+353 1 700 5000	+35317005000	53.3853317	-6.2588403		4.4	f	f	ChIJA12dLxsOZ0gRqMIHQZhFuxI	["University", "College"]	2025-11-10 19:01:19.777+00	[{"day": "Monday", "hours": "9 AM to 5:30 PM"}, {"day": "Tuesday", "hours": "9 AM to 5:30 PM"}, {"day": "Wednesday", "hours": "9 AM to 5:30 PM"}, {"day": "Thursday", "hours": "9 AM to 5:30 PM"}, {"day": "Friday", "hours": "9 AM to 5:30 PM"}, {"day": "Saturday", "hours": "Closed"}, {"day": "Sunday", "hours": "Closed"}]	{"Parking": ["Paid parking garage", "Paid parking lot"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"]}	
23	IE-dublin	Guinness Storehouse		Brewery experience telling the tale of Ireland&apos;s famous beer, with tastings and a rooftop bar.	0		St. James&apos;s Gate, Dublin 8, D08 VF8H, Ireland	The Liberties	St. James&apos;s Gate			Dublin 8		https://www.guinness-storehouse.com/en/home?utm_source=Google&utm_medium=Organic&utm_campaign=gsh_google_my_business&utm_id=Google+My+Business+	+353 1 408 4800	+35314084800	53.3418088	-6.2867155		4.4	f	f	ChIJawXFQIQOZ0gRoucFdZIzGbM	["Brewery", "Tourist attraction"]	2025-11-10 19:00:53.16+00	[{"day": "Monday", "hours": "10 AM to 5 PM"}, {"day": "Tuesday", "hours": "10 AM to 5 PM"}, {"day": "Wednesday", "hours": "10 AM to 5 PM"}, {"day": "Thursday", "hours": "10 AM to 5 PM"}, {"day": "Friday", "hours": "10 AM to 5 PM"}, {"day": "Saturday", "hours": "9:30 AM to 5 PM"}, {"day": "Sunday", "hours": "9:30 AM to 5 PM"}]	{"Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Amenities": ["Bar onsite"], "Offerings": ["Alcohol", "Beer"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services", "Delivery"]}	
24	IE-dublin	Dublin Castle	Caislen Bhaile tha Cliath	Historic site, dating from 1204, with 2 museums, cafes and gardens, plus state rooms and a library.	0		Dame St, Dublin 2, Ireland		Dame St			Dublin 2		https://dublincastle.ie/	+353 46 942 2213	+353469422213	53.3428861	-6.2674284	State Apartments	4.3	f	f	ChIJif9mNYcOZ0gRhlbhwPbNDwU	["Castle", "Historical place", "Historical landmark", "Tourist attraction"]	2025-11-10 19:00:53.16+00	[{"day": "Monday", "hours": "9:45 AM to 5:15 PM"}, {"day": "Tuesday", "hours": "9:45 AM to 5:15 PM"}, {"day": "Wednesday", "hours": "9:45 AM to 5:15 PM"}, {"day": "Thursday", "hours": "9:45 AM to 5:15 PM"}, {"day": "Friday", "hours": "9:45 AM to 5:15 PM"}, {"day": "Saturday", "hours": "9:45 AM to 5:15 PM"}, {"day": "Sunday", "hours": "9:45 AM to 5:15 PM"}]	{"Children": ["Good for kids"], "Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
25	IE-dublin	St Patrick&apos;s Cathedral	Ard-Eaglais Naomh Pdraig	The Church of Ireland&apos;s national cathedral, dating from 1220, with regular musical recitals.	0		St Patrick&apos;s Close, Dublin, D08 H6X3, Ireland		St Patrick&apos;s Close			Dublin		https://www.stpatrickscathedral.ie/	+353 1 453 9472	+35314539472	53.3395154	-6.2714767		4.5	f	f	ChIJpVg1bAmnREgRVLEltpvmyJI	["Cathedral", "Church", "Tourist attraction"]	2025-11-10 19:00:53.16+00	[{"day": "Monday", "hours": "9:30 AM to 5 PM"}, {"day": "Tuesday", "hours": "9:30 AM to 5 PM"}, {"day": "Wednesday", "hours": "9:30 AM to 5 PM"}, {"day": "Thursday", "hours": "9:30 AM to 5 PM"}, {"day": "Friday", "hours": "9:30 AM to 5 PM"}, {"day": "Saturday", "hours": "9 AM to 5 PM"}, {"day": "Sunday", "hours": "9 to 10:30 AM, 1 to 2:30 PM"}]	{"Amenities": ["Restroom"], "Accessibility": ["Wheelchair accessible entrance"], "Service options": ["Onsite services"]}	
26	IE-dublin	Vicar Street		State of the art lighting rig for intimate concerts, stand up comedy gigs and drama performances.	0		58-59, Thomas St, The Liberties, Dublin 8, Ireland	The Liberties	58-59, Thomas St			Dublin 8		https://www.vicarstreet.com/	+353 1 775 5800	+35317755800	53.3426764	-6.2778366		4.6	f	f	ChIJcadEpCUMZ0gRpwjkz6OpV94	["Live music venue", "Concert hall"]	2025-11-10 19:00:53.16+00	[{"day": "Monday", "hours": "12 to 11:30 AM, 6:30 PM to 12 AM"}, {"day": "Tuesday", "hours": "6:30 PM to 12 AM"}, {"day": "Wednesday", "hours": "6:30 PM to 12 AM"}, {"day": "Thursday", "hours": "6:30 PM to 12 AM"}, {"day": "Friday", "hours": "6:30 PM to 1 AM"}, {"day": "Saturday", "hours": "6:30 PM to 1 AM"}, {"day": "Sunday", "hours": "6:30 PM to 12 AM"}]	{"Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Amenities": ["Bar onsite", "Restroom", "Restaurant"], "Highlights": ["Live performances"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible restroom", "Wheelchair accessible seating", "Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
27	IE-dublin	Trinity College Dublin	Coliste na Tronide, Baile tha Cliath	19-hectare university with Georgian buildings, known for its humanities, science & medical programs.	0		College Green, Dublin 2, Ireland		College Green			Dublin 2		https://www.tcd.ie/	+353 1 896 1000	+35318961000	53.3437935	-6.2545716		4.5	f	f	ChIJ3Y7HLZsOZ0gRZ2FxjA3-ACc	["University", "Tourist attraction"]	2025-11-10 19:00:54.041+00	[]	{"Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
28	IE-dublin	National Gallery of Ireland	Gaileara Nisinta na hireann	Grand collection of European art spanning the 14th to the 21st-century, covering all major schools.	0		Merrion Square W, Dublin 2, D02 K303, Ireland		Merrion Square W			Dublin 2		https://www.nationalgallery.ie/	+353 1 661 5133	+35316615133	53.3408887	-6.2522962	National Gallery of Ireland Art Library	4.7	f	f	ChIJb1ecSpcOZ0gRMQ3w0Qyz_Vg	["Art gallery", "Gift shop", "Tourist attraction"]	2025-11-10 19:00:54.042+00	[{"day": "Monday", "hours": "11 AM to 5:30 PM"}, {"day": "Tuesday", "hours": "9:15 AM to 5:30 PM"}, {"day": "Wednesday", "hours": "9:15 AM to 5:30 PM"}, {"day": "Thursday", "hours": "9:15 AM to 8:30 PM"}, {"day": "Friday", "hours": "9:15 AM to 5:30 PM"}, {"day": "Saturday", "hours": "9:15 AM to 5:30 PM"}, {"day": "Sunday", "hours": "11 AM to 5:30 PM"}]	{"Crowd": ["Family-friendly"], "Children": ["Good for kids"], "Amenities": ["Restaurant", "Restroom", "Wi-Fi", "Free Wi-Fi"], "Highlights": ["Live performances"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"], "Service options": ["Onsite services"]}	
29	IE-dublin	Dublin Pearse	Baile tha Cliath Stisin na bPiarsach		0		Dublin, Ireland					Dublin		http://www.irishrail.ie/travel-information/dublin-pearse			53.3433274	-6.2480209		4.2	f	f	ChIJpWwGCJEOZ0gRPZ-JB7vXAAU	["Train station"]	2025-11-10 19:00:54.042+00	[]	{"Amenities": ["Restroom"], "Getting here": ["24-hour transit available"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible restroom"], "Service options": ["Onsite services"]}	
30	IE-dublin	Merrion Square Park		Leafy park with floral and heather gardens, playground and notable Oscar Wilde statue.	0		1 Merrion Square E, Dublin, Ireland		1 Merrion Square E			Dublin		http://www.dublincity.ie/main-menu-services-recreation-culture-dublin-city-parks-visit-park/merrion-square-park	+353 1 222 5278	+35312225278	53.3396722	-6.2492134	The Giants Garden	4.6	f	f	ChIJb1ecSpcOZ0gRg3SCpRcmX4A	["Park"]	2025-11-10 19:00:54.042+00	[{"day": "Monday", "hours": "10 AM to 9:30 PM"}, {"day": "Tuesday", "hours": "10 AM to 9:30 PM"}, {"day": "Wednesday", "hours": "10 AM to 9:30 PM"}, {"day": "Thursday", "hours": "10 AM to 9:30 PM"}, {"day": "Friday", "hours": "10 AM to 9:30 PM"}, {"day": "Saturday", "hours": "10 AM to 9:30 PM"}, {"day": "Sunday", "hours": "10 AM to 9:30 PM"}]	{"Pets": ["Dogs allowed"], "Children": ["Good for kids", "Playground"], "Amenities": ["Picnic tables", "Slides", "Swings"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
31	IE-dublin	Iveagh Gardens	Gairdn Ubh Eachach	Unique collection of garden landscapes designed in 1865 and mostly restored since 1995.	0		St Stephen&apos;s Green, Park, Dublin 2, D02 HX65, Ireland	Park	St Stephen&apos;s Green			Dublin 2		http://www.iveaghgardens.ie/	+353 1 475 7816	+35314757816	53.3351376	-6.2610343	Waterfall Iveagh Gardens	4.7	f	f	ChIJIZpbZp8OZ0gR5pvUpWaYfzQ	["Garden", "Tourist attraction"]	2025-11-10 19:00:54.042+00	[{"day": "Monday", "hours": "8 AM to 4:30 PM"}, {"day": "Tuesday", "hours": "8 AM to 4:30 PM"}, {"day": "Wednesday", "hours": "8 AM to 4:30 PM"}, {"day": "Thursday", "hours": "8 AM to 4:30 PM"}, {"day": "Friday", "hours": "8 AM to 4:30 PM"}, {"day": "Saturday", "hours": "8 AM to 4:30 PM"}, {"day": "Sunday", "hours": "10 AM to 4:30 PM"}]	{"Pets": ["Dogs allowed"], "Children": ["Good for kids"], "Payments": ["NFC mobile payments"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"]}	
32	IE-dublin	St Stephen&apos;s Green	Faiche Stiabhna	City centre park with ornamental lake, waterfall, sculptures and a children&apos;s playground.	0		St Stephen&apos;s Green, Dublin 2, Ireland		St Stephen&apos;s Green			Dublin 2		http://ststephensgreenpark.ie/	+353 1 475 7816	+35314757816	53.3381736	-6.259119	Playground at St. Stephen&apos;s Green	4.7	f	f	ChIJo5EyLpkOZ0gRfIOtBfARzQU	["Park", "Garden", "Tourist attraction"]	2025-11-10 19:00:54.042+00	[{"day": "Monday", "hours": "7:30 AM to 5 PM"}, {"day": "Tuesday", "hours": "7:30 AM to 5 PM"}, {"day": "Wednesday", "hours": "7:30 AM to 5 PM"}, {"day": "Thursday", "hours": "7:30 AM to 5 PM"}, {"day": "Friday", "hours": "7:30 AM to 5 PM"}, {"day": "Saturday", "hours": "7:30 AM to 5 PM"}, {"day": "Sunday", "hours": "9:30 AM to 5 PM"}]	{"Pets": ["Dogs allowed"], "Children": ["Good for kids", "Playground"], "Amenities": ["Public restroom", "Slides", "Swings"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
33	IE-dublin	Drimnagh Medieval Castle and Gardens	Caislen Dhroimeanaigh	Restored feudal castle for weddings and events with manicured grounds, high towers and a moat.	0		Medieval Castle, Long Mile Rd, Drimnagh, Dublin, 12, Ireland	Drimnagh	Medieval Castle, Long Mile Rd			Dublin		http://www.drimnaghcastle.org/	+353 1 450 2530	+35314502530	53.3249029	-6.3328744		4.7	f	f	ChIJCdMvZ44MZ0gRzzTlTibTlOs	["Castle", "Fortress", "Garden", "Historical landmark", "History museum", "Tourist attraction"]	2025-11-10 19:00:54.042+00	[{"day": "Monday", "hours": "10 AM to 3 PM"}, {"day": "Tuesday", "hours": "10 AM to 3 PM"}, {"day": "Wednesday", "hours": "10 AM to 3 PM"}, {"day": "Thursday", "hours": "10 AM to 3 PM"}, {"day": "Friday", "hours": "10 AM to 12 PM"}, {"day": "Saturday", "hours": "Closed"}, {"day": "Sunday", "hours": "Closed"}]	{"Parking": ["Free parking lot"], "Children": ["Discounts for kids", "Good for kids"], "Payments": ["Cash-only"], "Planning": ["Getting tickets in advance recommended"], "Accessibility": ["Assistive hearing loop"]}	
34	IE-dublin	The Nightmare Realm			0		Royal Liver Assurance Retail Park, Old Naas Rd, Inchicore, Dublin, D12 X3FK, Ireland	Inchicore	Royal Liver Assurance Retail Park, Old Naas Rd			Dublin		http://www.thenightmarerealm.ie/	+353 1 571 9090	+35315719090	53.3284196	-6.3416547		4.5	f	f	ChIJgxp1YcYOZ0gRQJI1OcW969w	["Tourist attraction", "Event venue"]	2025-11-10 19:00:54.042+00	[{"day": "Monday", "hours": "Closed"}, {"day": "Tuesday", "hours": "Closed"}, {"day": "Wednesday", "hours": "6:30 to 10:30 PM"}, {"day": "Thursday", "hours": "6:30 to 10:30 PM"}, {"day": "Friday", "hours": "6:30 to 10:30 PM"}, {"day": "Saturday", "hours": "6 to 10:30 PM"}, {"day": "Sunday", "hours": "6:30 to 10:30 PM"}]	{"Crowd": ["LGBTQ+ friendly", "Transgender safespace"], "Parking": ["Free parking lot", "On-site parking"], "Payments": ["Credit cards", "Debit cards", "NFC mobile payments"], "Planning": ["Appointment required", "Getting tickets in advance recommended"], "Amenities": ["Gender-neutral restroom", "Restroom"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"]}	
35	IE-dublin	McDonald&apos;s		Classic, long-running fast-food chain known for its burgers & fries.	0		AT, Kylemore Rd, Naas Rd, Inchicore, Dublin, H91 K4A9, Ireland	Inchicore	AT, Kylemore Rd, Naas Rd			Dublin		https://www.mcdonalds.com/gb/en-gb.html?cid=RF:YEXT:GMB::Clicks:DIRSYN:	+353 1 450 5722	+35314505722	53.3274167	-6.3436746		3.5	f	f	ChIJcwx-WJQMZ0gRd-fttHNtb8E	["Fast food restaurant", "American restaurant", "Breakfast restaurant", "Chicken restaurant", "Delivery service", "Diner", "Hamburger restaurant", "Restaurant"]	2025-11-10 19:00:54.043+00	[{"day": "Monday", "hours": "Open 24 hours"}, {"day": "Tuesday", "hours": "Open 24 hours"}, {"day": "Wednesday", "hours": "Open 24 hours"}, {"day": "Thursday", "hours": "Open 24 hours"}, {"day": "Friday", "hours": "Open 24 hours"}, {"day": "Saturday", "hours": "Open 24 hours"}, {"day": "Sunday", "hours": "Open 24 hours"}]	{"Crowd": ["Family-friendly", "Groups"], "Parking": ["Free parking lot", "Free street parking", "Usually plenty of parking"], "Children": ["Good for kids", "Good for kids birthday", "Has changing table(s)", "High chairs", "Kids&apos; menu", "Playground"], "Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Amenities": ["Restroom"], "Offerings": ["Coffee", "Late-night food", "Quick bite", "Vegetarian options"], "Atmosphere": ["Casual"], "Highlights": ["Great coffee"], "Popular for": ["Breakfast", "Lunch", "Dinner", "Solo dining"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom", "Wheelchair accessible seating"], "Dining options": ["Breakfast", "Lunch", "Dinner", "Counter service", "Dessert", "Seating"], "Service options": ["Outdoor seating", "No-contact delivery", "Delivery", "Drive-through", "Takeout", "Dine-in"]}	
36	IE-dublin	O&apos;Neills Sports Store Dublin			0		Long Mile Rd, Walkinstown, Dublin, Ireland	Walkinstown	Long Mile Rd			Dublin		https://oneills.com/	+353 1 429 3548	+35314293548	53.3223664	-6.3372546		4.5	f	f	ChIJDYdKoZEMZ0gR9NFq_QPjBhk	["Outlet store", "Store"]	2025-11-10 19:00:54.043+00	[{"day": "Monday", "hours": "9:30 AM to 5:30 PM"}, {"day": "Tuesday", "hours": "9:30 AM to 5:30 PM"}, {"day": "Wednesday", "hours": "9:30 AM to 5:30 PM"}, {"day": "Thursday", "hours": "9:30 AM to 5:30 PM"}, {"day": "Friday", "hours": "9:30 AM to 5:30 PM"}, {"day": "Saturday", "hours": "9 AM to 5:30 PM"}, {"day": "Sunday", "hours": "11 AM to 5 PM"}]	{"Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Planning": ["Quick visit"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["In-store pickup", "In-store shopping", "Onsite services"]}	
37	IE-dublin	Lidl			0		12 Walkinstown Ave, Walkinstown, Dublin, D12 W954, Ireland	Walkinstown	12 Walkinstown Ave			Dublin		https://www.lidl.ie/	+353 1 920 3010	+35319203010	53.32216	-6.34029		4.4	f	f	ChIJwZcVK5cMZ0gRKs0VLULef9g	["Grocery store", "Fruit and vegetable store", "Promotional products supplier", "Supermarket"]	2025-11-10 19:00:54.043+00	[{"day": "Monday", "hours": "8 AM to 10 PM"}, {"day": "Tuesday", "hours": "8 AM to 10 PM"}, {"day": "Wednesday", "hours": "8 AM to 10 PM"}, {"day": "Thursday", "hours": "8 AM to 10 PM"}, {"day": "Friday", "hours": "8 AM to 10 PM"}, {"day": "Saturday", "hours": "8 AM to 10 PM"}, {"day": "Sunday", "hours": "9 AM to 9 PM"}]	{"Payments": ["Credit cards", "Debit cards", "NFC mobile payments"], "Planning": ["Quick visit"], "Offerings": ["Organic products"], "Recycling": ["Batteries"], "Highlights": ["Great produce"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services", "Delivery"]}	
38	IE-dublin	William Pearse Park			0		Drimnagh, Dublin, Ireland	Drimnagh				Dublin					53.3230737	-6.3157657	Swan Leisure @ Crumlin	4.4	f	f	ChIJv8pLMhUNZ0gR_jeU56Mtm9k	["Park"]	2025-11-10 19:00:54.829+00	[{"day": "Monday", "hours": "10 AM to 5:30 PM"}, {"day": "Tuesday", "hours": "10 AM to 5:30 PM"}, {"day": "Wednesday", "hours": "10 AM to 5:30 PM"}, {"day": "Thursday", "hours": "10 AM to 5:30 PM"}, {"day": "Friday", "hours": "10 AM to 5:30 PM"}, {"day": "Saturday", "hours": "10 AM to 6:30 PM"}, {"day": "Sunday", "hours": "10 AM to 6:30 PM"}]	{"Pets": ["Dogs allowed"], "Children": ["Good for kids", "Playground"], "Amenities": ["Slides", "Swings"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance"]}	
39	IE-dublin	Eamonn Ceannt Park		Sprawling green with tennis & basketball courts, a running track & soccer fields, plus a velodrome.	0		Clogher Rd, Crumlin, Dublin, Ireland	Crumlin	Clogher Rd			Dublin		http://www.dublincity.ie/main-menu-services-recreation-culture-dublin-city-parks-visit-park/eamonn-ceannt-park	+353 1 454 0799	+35314540799	53.3231477	-6.2922037	Eamonn Ceannt Playground	4.6	f	f	ChIJAVR-KW0MZ0gRRoQEyb21eP0	["City park", "Tourist attraction"]	2025-11-10 19:00:54.83+00	[{"day": "Monday", "hours": "10 AM to 10 PM"}, {"day": "Tuesday", "hours": "10 AM to 10 PM"}, {"day": "Wednesday", "hours": "10 AM to 10 PM"}, {"day": "Thursday", "hours": "10 AM to 10 PM"}, {"day": "Friday", "hours": "10 AM to 10 PM"}, {"day": "Saturday", "hours": "10 AM to 10 PM"}, {"day": "Sunday", "hours": "10 AM to 10 PM"}]	{"Pets": ["Dogs allowed"], "Children": ["Good for kids", "Good for kids birthday", "Playground"], "Amenities": ["Basketball court", "Cycling lanes", "Has a tennis court", "Picnic tables", "Slides", "Swings"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
40	IE-dublin	Dunnes Stores			0		Ashleaf Shopping Centre, Cromwellsfort Rd, Crumlin, Dublin, D12 RKK5, Ireland	Crumlin	Ashleaf Shopping Centre, Cromwellsfort Rd			Dublin		http://www.dunnesstores.com/	+353 1 456 0400	+35314560400	53.3155714	-6.3183352		4.3	f	f	ChIJ5w1DrYAMZ0gRiGx1nxoXR-k	["Department store", "Clothing store", "Grocery store"]	2025-11-10 19:00:54.83+00	[{"day": "Monday", "hours": "8 AM to 10 PM"}, {"day": "Tuesday", "hours": "8 AM to 10 PM"}, {"day": "Wednesday", "hours": "8 AM to 10 PM"}, {"day": "Thursday", "hours": "8 AM to 10 PM"}, {"day": "Friday", "hours": "8 AM to 10 PM"}, {"day": "Saturday", "hours": "8 AM to 10 PM"}, {"day": "Sunday", "hours": "8:30 AM to 9 PM"}]	{"Parking": ["Free parking lot"], "Payments": ["Credit cards", "Debit cards", "NFC mobile payments"], "Planning": ["Quick visit"], "Amenities": ["Restroom"], "Recycling": ["Batteries", "Glass bottles", "Plastic bottles"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"], "Service options": ["Delivery", "In-store pickup", "In-store shopping", "Onsite services"]}	
41	IE-dublin	Lidl			0		6W, 18 Rathfarnham Rd, Terenure, Dublin 6W, Co. Dublin, D6W WC60, Ireland	Terenure	6W, 18 Rathfarnham Rd		Co. Dublin	Dublin 6W		https://www.lidl.ie/	+353 1 920 3010	+35319203010	53.30913	-6.28326		4.3	f	f	ChIJ_TgCsfULZ0gRIXIYY9tdN2I	["Grocery store", "Fruit and vegetable store", "Promotional products supplier", "Supermarket"]	2025-11-10 19:00:55.715+00	[{"day": "Monday", "hours": "8 AM to 10 PM"}, {"day": "Tuesday", "hours": "8 AM to 10 PM"}, {"day": "Wednesday", "hours": "8 AM to 10 PM"}, {"day": "Thursday", "hours": "8 AM to 10 PM"}, {"day": "Friday", "hours": "8 AM to 10 PM"}, {"day": "Saturday", "hours": "8 AM to 10 PM"}, {"day": "Sunday", "hours": "9 AM to 9 PM"}]	{"Payments": ["Credit cards", "Debit cards", "NFC mobile payments"], "Planning": ["Quick visit"], "Amenities": ["Restroom"], "Offerings": ["Organic products"], "Recycling": ["Plastic bottles"], "Highlights": ["Great produce"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"], "Service options": ["Onsite services", "Delivery"]}	
42	IE-dublin	ALDI		Retail chain selling a range of grocery items, meat & dairy.	0		Terenure Rd E, Dublin, D06 KF20, Ireland		Terenure Rd E			Dublin		https://www.aldi.ie/?utm_source=google&utm_medium=local&utm_campaign=brand&utm_content=wklyad_webclick	+353 1800 991 828	+3531800991828	53.3107558	-6.2822241		4.5	f	f	ChIJQ5vQ3PULZ0gRN6wevWeR5NM	["Grocery store", "Supermarket"]	2025-11-10 19:00:55.716+00	[{"day": "Monday", "hours": "8 AM to 10 PM"}, {"day": "Tuesday", "hours": "8 AM to 10 PM"}, {"day": "Wednesday", "hours": "8 AM to 10 PM"}, {"day": "Thursday", "hours": "8 AM to 10 PM"}, {"day": "Friday", "hours": "8 AM to 10 PM"}, {"day": "Saturday", "hours": "8 AM to 10 PM"}, {"day": "Sunday", "hours": "9 AM to 9 PM"}]	{"Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Planning": ["Quick visit"], "Amenities": ["Restroom"], "Offerings": ["Organic products", "Prepared foods"], "Recycling": ["Batteries", "Electronics"], "Highlights": ["Great produce"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["In-store shopping", "Delivery"]}	
43	IE-dublin	Trinity Hall, Dublin			0		Trinity Hall, Dartry Rd, Dartry, Dublin 6, D06 R838, Ireland	Dartry	Trinity Hall, Dartry Rd			Dublin 6		https://www.tcd.ie/accommodation/	+353 1 896 8024	+35318968024	53.3121396	-6.2623657		4.3	f	f	ChIJg_re5P8LZ0gRpm7PRFteXog	["Student housing center"]	2025-11-10 19:00:55.716+00	[{"day": "Monday", "hours": "9 AM to 5 PM"}, {"day": "Tuesday", "hours": "9 AM to 5 PM"}, {"day": "Wednesday", "hours": "9 AM to 5 PM"}, {"day": "Thursday", "hours": "9 AM to 5 PM"}, {"day": "Friday", "hours": "9 AM to 5 PM"}, {"day": "Saturday", "hours": "Closed"}, {"day": "Sunday", "hours": "Closed"}]	{"Crowd": ["LGBTQ+ friendly", "Transgender safespace"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom", "Wheelchair accessible seating"]}	
44	IE-dublin	Bushy Park		Riverside park with woodland, pond, children&apos;s playground, football pitches and tennis courts.	0		Terenure, Dublin, Ireland	Terenure				Dublin		https://www.dublincity.ie/ga/node/4537	+353 1 490 0320	+35314900320	53.3025499	-6.2943383		4.6	f	f	ChIJOf3xVPALZ0gRWYW_38LRanQ	["Park", "Tourist attraction"]	2025-11-10 19:00:56.667+00	[{"day": "Monday", "hours": "10 AM to 8:30 PM"}, {"day": "Tuesday", "hours": "10 AM to 8:30 PM"}, {"day": "Wednesday", "hours": "10 AM to 8:30 PM"}, {"day": "Thursday", "hours": "10 AM to 8:30 PM"}, {"day": "Friday", "hours": "10 AM to 8:30 PM"}, {"day": "Saturday", "hours": "10 AM to 8:30 PM"}, {"day": "Sunday", "hours": "10 AM to 8:30 PM"}]	{"Pets": ["Dogs allowed"], "Parking": ["Paid street parking"], "Children": ["Good for kids", "Playground"], "Amenities": ["Basketball court", "Cycling lanes", "Has a tennis court", "Public restroom", "Skateboarding area", "Slides", "Swings"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
45	IE-dublin	Elm Park Golf & Sports Club		Bay views from the fairways of this 18-hole course, with a restaurant known for Irish seafood.	0		Nutley House, Elm Park, Nutley Ln, Donnybrook, Dublin 4, D04 WE09, Ireland	Donnybrook	Nutley House, Elm Park, Nutley Ln			Dublin 4		http://www.elmpark.ie/	+353 1 269 3438	+35312693438	53.3138971	-6.217228		4.5	f	f	ChIJGxNZLy0JZ0gRmZliWYGL9LI	["Golf club", "Golf course"]	2025-11-10 19:01:09.916+00	[{"day": "Monday", "hours": "7 AM to 9 PM"}, {"day": "Tuesday", "hours": "7 AM to 9 PM"}, {"day": "Wednesday", "hours": "7 AM to 9 PM"}, {"day": "Thursday", "hours": "7 AM to 9 PM"}, {"day": "Friday", "hours": "7 AM to 9 PM"}, {"day": "Saturday", "hours": "7 AM to 9 PM"}, {"day": "Sunday", "hours": "7 AM to 9 PM"}]	{"Payments": ["Credit cards", "Debit cards", "NFC mobile payments", "Credit cards"], "Amenities": ["Restroom"], "Offerings": ["Food"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"]}	
46	IE-dublin	Maldron Hotel Merrion Road		Relaxed hotel featuring an airy restaurant, a polished bar & a coffee shop, plus parking.	0		Bellevue Ave, Merrion Rd, Dublin, D04 K5C2, Ireland		Bellevue Ave, Merrion Rd			Dublin		https://ad.doubleclick.net/ddm/trackclk/N1074062.3913567MALDRONHOTELS-OR/B24608539.348271838;dc_trk_aid=562986230;dc_trk_cid=179423986;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;ltd=;dc_tdv=1	+353 1 233 0020	+35312330020	53.3125535	-6.2021873		4.4	f	f	ChIJZ0vrtQ4JZ0gR-X2jViGpvK8	["Hotel", "Bar", "Conference center", "Restaurant"]	2025-11-10 19:01:09.918+00	[]	{"Amenities": ["Free Wi-Fi"]}	
47	IE-dublin	Johnstown Park			0		11 Glasanaon Rd, Ballygall, Dublin, Ireland	Ballygall	11 Glasanaon Rd			Dublin		http://www.dublincity.ie/main-menu-services-recreation-culture-dublin-city-parks-visit-park/johnstown-park	+353 1 222 5278	+35312225278	53.3858212	-6.282176		4.4	f	f	ChIJ74f4EOMNZ0gRNP151qrsOnk	["Park", "Tourist attraction"]	2025-11-10 19:01:19.777+00	[{"day": "Monday", "hours": "10 AM to 6:30 PM"}, {"day": "Tuesday", "hours": "10 AM to 6:30 PM"}, {"day": "Wednesday", "hours": "10 AM to 6:30 PM"}, {"day": "Thursday", "hours": "10 AM to 6:30 PM"}, {"day": "Friday", "hours": "10 AM to 6:30 PM"}, {"day": "Saturday", "hours": "10 AM to 6:30 PM"}, {"day": "Sunday", "hours": "8 AM to 6:30 PM"}]	{"Pets": ["Dogs allowed"], "Children": ["Good for kids", "Playground"], "Amenities": ["Has a tennis court", "Picnic tables", "Slides", "Swings"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"], "Service options": ["Onsite services"]}	
48	IE-dublin	Omni Shopping Centre		Bright, long-running indoor mall with 80 stores on 2 levels, including an 11-screen cinema.	0		Swords Rd, Santry, Dublin, D09 HH61, Ireland	Santry	Swords Rd			Dublin		http://www.omnipark.ie/	+353 1 842 1262	+35318421262	53.3924195	-6.2482747		4.2	f	f	ChIJ-Zcpuz8OZ0gRI0AEcPnEzh4	["Shopping mall", "Children&apos;s clothing store", "Men&apos;s clothing store", "Pharmacy", "Women&apos;s clothing store"]	2025-11-10 19:01:19.777+00	[{"day": "Monday", "hours": "8:30 AM to 7 PM"}, {"day": "Tuesday", "hours": "8:30 AM to 7 PM"}, {"day": "Wednesday", "hours": "8:30 AM to 9 PM"}, {"day": "Thursday", "hours": "8:30 AM to 9 PM"}, {"day": "Friday", "hours": "8:30 AM to 9 PM"}, {"day": "Saturday", "hours": "8:30 AM to 7 PM"}, {"day": "Sunday", "hours": "10 AM to 7 PM"}]	{"Parking": ["Free parking lot"], "Children": ["Has changing table(s)"], "Payments": ["Credit cards", "Debit cards", "NFC mobile payments"], "Amenities": ["Restroom"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot", "Wheelchair accessible restroom"], "Service options": ["Onsite services"]}	
50	IE-dublin	Ellenfield Park			0		1 Glencorp Rd, Whitehall, Dublin 9, 9, Ireland	Whitehall	1 Glencorp Rd			Dublin 9			+353 1 842 1182	+35318421182	53.3861562	-6.2402827		4.4	f	f	ChIJNdujlTsOZ0gRdR5mkck87B4	["Park", "Tourist attraction"]	2025-11-10 19:01:19.778+00	[{"day": "Monday", "hours": "10 AM to 8:30 PM"}, {"day": "Tuesday", "hours": "10 AM to 8:30 PM"}, {"day": "Wednesday", "hours": "10 AM to 8:30 PM"}, {"day": "Thursday", "hours": "10 AM to 8:30 PM"}, {"day": "Friday", "hours": "10 AM to 8:30 PM"}, {"day": "Saturday", "hours": "10 AM to 8:30 PM"}, {"day": "Sunday", "hours": "10 AM to 8:30 PM"}]	{"Pets": ["Dogs allowed"], "Children": ["Good for kids", "Playground"], "Amenities": ["Has a tennis court", "Slides", "Swings"], "Highlights": ["Picnics"], "Accessibility": ["Wheelchair accessible entrance", "Wheelchair accessible parking lot"]}	
\.


--
-- TOC entry 3974 (class 0 OID 0)
-- Dependencies: 457
-- Name: attractions_id_seq; Type: SEQUENCE SET; Schema: world; Owner: postgres
--

SELECT pg_catalog.setval('world.attractions_id_seq', 50, true);


--
-- TOC entry 3809 (class 2606 OID 99135)
-- Name: attractions attractions_pkey; Type: CONSTRAINT; Schema: world; Owner: postgres
--

ALTER TABLE ONLY world.attractions
    ADD CONSTRAINT attractions_pkey PRIMARY KEY (id);


--
-- TOC entry 3962 (class 3256 OID 99136)
-- Name: attractions Users can read attractions; Type: POLICY; Schema: world; Owner: postgres
--

CREATE POLICY "Users can read attractions" ON world.attractions FOR SELECT USING (( SELECT true));


--
-- TOC entry 3961 (class 0 OID 99105)
-- Dependencies: 458
-- Name: attractions; Type: ROW SECURITY; Schema: world; Owner: postgres
--

ALTER TABLE world.attractions ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3971 (class 0 OID 0)
-- Dependencies: 458
-- Name: TABLE attractions; Type: ACL; Schema: world; Owner: postgres
--

GRANT ALL ON TABLE world.attractions TO anon;
GRANT ALL ON TABLE world.attractions TO authenticated;
GRANT ALL ON TABLE world.attractions TO service_role;
GRANT SELECT ON TABLE world.attractions TO PUBLIC;


--
-- TOC entry 3973 (class 0 OID 0)
-- Dependencies: 457
-- Name: SEQUENCE attractions_id_seq; Type: ACL; Schema: world; Owner: postgres
--

GRANT ALL ON SEQUENCE world.attractions_id_seq TO anon;
GRANT ALL ON SEQUENCE world.attractions_id_seq TO authenticated;
GRANT ALL ON SEQUENCE world.attractions_id_seq TO service_role;


-- Completed on 2025-11-15 09:41:24 GMT

--
-- PostgreSQL database dump complete
--

\unrestrict NhUR1GJm9I0fS4PtG2mhE8uhJzTutIJFf09iIuyDotdVDC7YDdO6dJGJqyM9jrg

