DELETE FROM "world"."attractions" WHERE "city_id" = 'IE-dublin';
INSERT INTO "world"."attractions" (
	"city_id",
	"visible",
	"title",
	"subtitle",
	"description",
	"category_name",
	"address",
	"website",
	"phone",
	"latitude",
	"longitude",
	"total_score",
	"categories",
	"scraped_at",
	"reviews_count",
	"opening_hours",
	"additional_info",
	"image_url"
) VALUES (
	'IE-dublin',
	TRUE,
	'Samuel Beckett Bridge',
	'Droichead Samuel Beckett',
	'21st-century cable-stayed bridge for vehicles & pedestrians, noted for its bold, harp-like outline.',
	'Bridge',
	'Samuel Beckett Brg, North Wall, Dublin, Ireland',
	'http://www.bridgesofdublin.ie/bridges/samuel-beckett-bridge',
	'+353 1 222 2222',
	53.3469567,
	-6.2413141,
	4.7,
	'["Bridge"]',
	'2025-11-24T11:57:14.084Z',
	1521,
	'[{"day":"Monday","hours":"Open 24 hours"},{"day":"Tuesday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Wednesday"},{"day":"Thursday","hours":"Open 24 hours"},{"day":"Friday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Saturday"},{"day":"Sunday","hours":"Open 24 hours"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSw5G5CSl7Xm3Yk1f8iVhXLzGPBGHln9Iq3RMljDSyu4qRqCIauvXfc9kJ2MLMs0FIFdGC3gFDEf9En7C9MSoORFpadsTPnmhJ5wZZ_IwqZz9XwdX5HLoZWEiZyoYWxQ3QAywmJP=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Irish Dance Party - Interactive Show',
	'',
	'',
	'Entertainer',
	'The Merchants Arch Bar (upstairs, 48-49 Wellington Quay, Templebar, Dublin 2, D02 EY65, Ireland',
	'https://www.irishdanceparty.com/',
	'+353 87 656 0952',
	53.3459236,
	-6.2628323,
	4.9,
	'["Entertainer","Tourist attraction"]',
	'2025-11-24T11:57:11.643Z',
	3673,
	'[{"day":"Monday","hours":"9â¯AM to 10â¯PM"},{"hours":"9â¯AM to 10â¯PM","day":"Tuesday"},{"hours":"9â¯AM to 10â¯PM","day":"Wednesday"},{"hours":"9â¯AM to 10â¯PM","day":"Thursday"},{"hours":"9â¯AM to 10â¯PM","day":"Friday"},{"day":"Saturday","hours":"9â¯AM to 10â¯PM"},{"day":"Sunday","hours":"9â¯AM to 10â¯PM"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Service options":["Onsite services"],"Payments":["Credit cards","Debit cards","Credit cards"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzdYPBXB5sshIEly7vttrezJNyVQ2CbVLWVOLcRyA0V1ELTBdN5t7qRUd-G1BqaUdQDSBxDpGFxExRsb9penMfI2aYifW_HpJ7ME7IL-HenJCM7Xw6YPfnVd1hyfUAfNqIplFnnSsNNut0=w408-h544-k-no'
),(
	'IE-dublin',
	TRUE,
	'Pearse Lyons Whiskey Distillery',
	'',
	'Spirits manufacturer offering guided tours & whiskey tastings, food-pairing experiences & tea rooms.',
	'Tourist attraction',
	'121-122, James&apos;s St, The Liberties, Dublin, D08 ET27, Ireland',
	'https://www.pearselyonsdistillery.com/',
	'+353 1 691 6000',
	53.3435139,
	-6.2898404,
	4.7,
	'["Tourist attraction","Distillery"]',
	'2025-11-24T11:57:00.074Z',
	1177,
	'[{"hours":"10:30â¯AM to 6â¯PM","day":"Monday"},{"hours":"10:30â¯AM to 6â¯PM","day":"Tuesday"},{"hours":"10:30â¯AM to 6â¯PM","day":"Wednesday"},{"hours":"10:30â¯AM to 6â¯PM","day":"Thursday"},{"day":"Friday","hours":"10:30â¯AM to 6â¯PM"},{"day":"Saturday","hours":"10:30â¯AM to 6â¯PM"},{"hours":"11:30â¯AM to 6â¯PM","day":"Sunday"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom"],"Service options":["Onsite services"],"Planning":["Appointment required","Getting tickets in advance recommended"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Amenities":["Restroom"]}',
	'https://lh3.googleusercontent.com/p/AF1QipMpdi7jaWKnAl4EiNp342NSM42oAFzVxyxfz6VY=w408-h602-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Bank on College Green',
	'',
	'Elegant bar with live piano music and chandeliers hanging from an intricately decorated ceiling.',
	'Tourist attraction',
	'20-22 College Green, Dublin 2, D02 C868, Ireland',
	'http://www.bankoncollegegreen.com/',
	'+353 1 677 0677',
	53.3441151,
	-6.2614964,
	4.5,
	'["Tourist attraction","Gastropub","Historical place","Irish pub","Pub","European restaurant"]',
	'2025-11-24T11:56:48.299Z',
	6447,
	'[{"hours":"10:30â¯AM to 11:30â¯PM","day":"Monday"},{"hours":"10:30â¯AM to 11:30â¯PM","day":"Tuesday"},{"hours":"10:30â¯AM to 11:30â¯PM","day":"Wednesday"},{"hours":"10:30â¯AM to 11:30â¯PM","day":"Thursday"},{"day":"Friday","hours":"10:30â¯AM to 1â¯AM"},{"day":"Saturday","hours":"10:30â¯AM to 1â¯AM"},{"hours":"11â¯AM to 11:30â¯PM","day":"Sunday"}]',
	'{"Children":["High chairs"],"Popular for":["Lunch","Dinner","Solo dining"],"Offerings":["Alcohol","Beer","Cocktails","Coffee","Hard liquor","Late-night food","Quick bite","Small plates","Wine"],"Parking":["Paid street parking","Usually difficult to find a space"],"Accessibility":["Wheelchair accessible seating","Wheelchair accessible parking lot"],"Dining options":["Breakfast","Brunch","Lunch","Dinner","Dessert","Seating","Table service"],"Service options":["Onsite services","Dine-in","Delivery","Takeout"],"Atmosphere":["Casual","Cozy","Historic","Romantic","Trendy","Upscale"],"Highlights":["Great beer selection","Great cocktails","Great coffee","Great dessert","Great tea selection","Great wine list"],"Amenities":["Bar onsite","Restroom"],"Planning":["Brunch reservations recommended","Lunch reservations recommended","Dinner reservations recommended","Accepts reservations"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Crowd":["Groups","Tourists"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwfrCjrZWoFA2IwOtdl23022MuM2nPlSJcuJewZsj4jqCeEPCUUPI6CdP6mK12Pq5LCO9Ovf3eWG1kB7n1mZTo4geeF8N84zrdAhoM8L90stD9EeffCqpBpQ8ODlb6OYgeApd68jQ=w408-h544-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Church Café Bar',
	'',
	'Sympathetic conversion of imposing church with cafe/bar and Irish restaurant surrounded by terraces.',
	'Tourist attraction',
	'Jervis St, North City, Dublin 1, D01 YX64, Ireland',
	'https://www.thechurch.ie/',
	'+353 1 828 0102',
	53.3486718,
	-6.2668261,
	4.4,
	'["Tourist attraction","Bar","Beer garden","Cafe","Cocktail bar","Event venue","Historical landmark","Restaurant","Bar & grill"]',
	'2025-11-24T11:56:48.299Z',
	18232,
	'[{"day":"Monday","hours":"10:30â¯AM to 11â¯PM"},{"day":"Tuesday","hours":"10:30â¯AM to 11â¯PM"},{"day":"Wednesday","hours":"10:30â¯AM to 11â¯PM"},{"day":"Thursday","hours":"10:30â¯AM to 11:30â¯PM"},{"hours":"10:30â¯AM to 12:30â¯AM","day":"Friday"},{"day":"Saturday","hours":"10â¯AM to 1:30â¯AM"},{"day":"Sunday","hours":"10â¯AM to 11â¯PM"}]',
	'{"Parking":["Paid street parking","Usually difficult to find a space"],"Offerings":["Alcohol","Beer","Cocktails","Coffee","Food","Food at bar","Hard liquor","Late-night food","Private dining room","Quick bite","Small plates","Vegan options","Vegetarian options","Wine"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Amenities":["Bar onsite","Restroom"],"Planning":["Brunch reservations recommended","Lunch reservations recommended","Dinner reservations recommended","Accepts reservations"],"Dining options":["Brunch","Lunch","Dinner","Catering","Dessert","Seating","Table service"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Wheelchair accessible seating","Wheelchair accessible parking lot"],"Crowd":["College students","Groups","LGBTQ+ friendly","Tourists"],"Children":["Has changing table(s)","High chairs","Kids&apos; menu"],"Highlights":["Great beer selection","Great cocktails","Great coffee","Great dessert","Great tea selection","Great wine list","Live music","Live performances"],"Popular for":["Lunch","Dinner","Solo dining"],"Service options":["Outdoor seating","Onsite services","Dine-in","Delivery"],"Atmosphere":["Casual","Cozy","Historic","Romantic","Trendy","Upscale"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxIeC5QtSW-plN2yPlSEyHAATGx7Mp1qUC20i8nakHzcmeruME8uFDTlrsPmPJVcWjZXPglyd59w26SFxFA-WzWo9JgxlU69AWxMjraZTyiuIJkrBL0R-uDqkl1CgzErr9bYzDAqA=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'Zozimus Bar',
	'',
	'',
	'Tourist attraction',
	'Centenary House, 5 Anne&apos;s Ln, Anne St S, Dublin 2, D02 AK30, Ireland',
	'https://www.zozimusbar.ie/',
	'+353 1 536 9640',
	53.340588,
	-6.259737,
	4.3,
	'["Tourist attraction","Brunch restaurant","Disco club","Event venue","Cocktail bar"]',
	'2025-11-24T11:56:48.298Z',
	1102,
	'[{"day":"Monday","hours":"Closed"},{"hours":"5â¯PM to 12:30â¯AM","day":"Tuesday"},{"day":"Wednesday","hours":"5â¯PM to 12:30â¯AM"},{"hours":"5â¯PM to 2:30â¯AM","day":"Thursday"},{"hours":"3â¯PM to 2:30â¯AM","day":"Friday"},{"day":"Saturday","hours":"12â¯PM to 2:30â¯AM"},{"day":"Sunday","hours":"12 to 11â¯PM"}]',
	'{"Planning":["Accepts reservations"],"Amenities":["Restroom"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Crowd":["Groups","LGBTQ+ friendly","Tourists"],"Atmosphere":["Cozy","Trendy","Upscale"],"Service options":["Outdoor seating","Dine-in","Delivery","Takeout"],"Highlights":["Great beer selection","Great cocktails","Great wine list","Live music"],"Offerings":["Alcohol","Beer","Cocktails","Dancing","Food","Food at bar","Happy hour drinks","Hard liquor","Wine"],"Parking":["Paid parking lot"],"Dining options":["Seating","Table service"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Wheelchair accessible seating","Wheelchair accessible parking lot"],"Popular for":["Solo dining"],"Pets":["Dogs allowed"]}',
	'https://lh3.googleusercontent.com/p/AF1QipOUwDSvS7e9-Y2OQraSHzuUiaXuP-ajD1KU7OdB=w408-h272-k-no'
),(
	'IE-dublin',
	TRUE,
	'Token',
	'',
	'',
	'Tourist attraction',
	'Mayor Street Lower, North Wall, Dublin 1, D01 DE47, Ireland',
	'http://tokendublin.ie/',
	'+353 1 912 5783',
	53.3495863,
	-6.2430884,
	4.5,
	'["Tourist attraction","Bar","Restaurant","Video arcade"]',
	'2025-11-24T11:56:47.411Z',
	4690,
	'[]',
	'{"From the business":["Identifies as women-owned"],"Offerings":["Alcohol","Beer","Cocktails","Coffee","Halal food","Happy hour drinks","Hard liquor","Late-night food","Small plates","Vegan options","Vegetarian options","Wine"],"Parking":["Usually plenty of parking"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Wheelchair accessible seating"],"Dining options":["Breakfast","Brunch","Lunch","Dinner","Counter service","Dessert","Seating"],"Children":["Kids&apos; menu"],"Pets":["Dogs allowed","Dogs allowed inside","Dogs allowed outside"],"Planning":["Accepts reservations"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Amenities":["Bar onsite","Restroom","Wi-Fi","Free Wi-Fi"],"Crowd":["LGBTQ+ friendly","Transgender safespace"],"Highlights":["Live music","Sports"],"Service options":["Outdoor seating","No-contact delivery","Delivery","Onsite services","Takeout","Dine-in"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyPx3G3BL6PGwAOYv6PHPbLCpIMJXqm6QkZPsiDB2F4xVxpsuObW4q1cSFa-Dlp8RRJJVP1Zt74tHiy59f7FgFV0ARscucOTSzJIDwMtq84MK3xLlsdEv6sqaNT_olMkMIls_sQDQ=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'Liberty Market',
	'',
	'Time-tested market with numerous vendors selling apparel, shoes, housewares, books & other goods.',
	'Tourist attraction',
	'Liberty Market, Meath St, The Liberties, Dublin, Ireland',
	'http://www.libertymarket.ie/',
	'+353 1 280 8683',
	53.3411335,
	-6.2783724,
	4.1,
	'["Tourist attraction","Market"]',
	'2025-11-24T11:56:47.411Z',
	1347,
	'[{"day":"Monday","hours":"Closed"},{"hours":"Closed","day":"Tuesday"},{"day":"Wednesday","hours":"Closed"},{"day":"Thursday","hours":"10:30â¯AM to 4â¯PM"},{"day":"Friday","hours":"10:30â¯AM to 4â¯PM"},{"day":"Saturday","hours":"10:30â¯AM to 5â¯PM"},{"day":"Sunday","hours":"Closed"}]',
	'{"Accessibility":["Wheelchair accessible entrance"],"Service options":["Onsite services"],"Payments":["Credit cards","Debit cards","NFC mobile payments"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyOyvrm4Dy1lsXLHNxZCQOre2Dlt3GrjXcM6HDzaWiBCDZxpCq-BaDuDn8vbBuXkM9TjrHmdHBUQ8cWHbM2b8uupUv12RLYXmvjJoDVLKQTKH_WSZMrkvG8fSupJ4spUSpaqgU0=w408-h302-k-no'
),(
	'IE-dublin',
	TRUE,
	'Teeling Whiskey Distillery',
	'',
	'Opened in 2015, this Irish whiskey distillery is the city&apos;s first for 125 years & hosts tours.',
	'Visitor center',
	'13-17 Newmarket, The Liberties, Dublin 8, D08 KD91, Ireland',
	'https://teelingdistillery.com/?utm_source=google&utm_medium=organic&utm_campaign=gmb&utm_id=gmb',
	'+353 1 531 0888',
	53.3377848,
	-6.277199,
	4.7,
	'["Visitor center","Distillery"]',
	'2025-11-24T11:56:45.546Z',
	3820,
	'[{"day":"Monday","hours":"11â¯AM to 6â¯PM"},{"hours":"11â¯AM to 6â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"11â¯AM to 6â¯PM"},{"day":"Thursday","hours":"11â¯AM to 6â¯PM"},{"day":"Friday","hours":"11â¯AM to 6â¯PM"},{"hours":"11â¯AM to 7â¯PM","day":"Saturday"},{"day":"Sunday","hours":"11â¯AM to 6â¯PM"}]',
	'{"Crowd":["LGBTQ+ friendly","Transgender safespace"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom","Wheelchair accessible seating"],"Service options":["Online appointments","Onsite services"],"Amenities":["Gender-neutral restroom","Restroom"],"Planning":["Getting tickets in advance recommended"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"]}',
	'https://lh3.googleusercontent.com/p/AF1QipM6HDnNfkD2Pdj35NcNg7yG9VZS_eC5665tBhR3=w408-h272-k-no'
),(
	'IE-dublin',
	TRUE,
	'Vintage Tea Trips',
	'',
	'',
	'Tour agency',
	'Stephen Court, 20-22 St Stephen&apos;s Green, Dublin 2, D02 HW54, Ireland',
	'http://www.vintageteatrips.ie/',
	'+353 1 255 1777',
	53.3393024,
	-6.2575396,
	4.9,
	'["Tour agency","Tourist attraction"]',
	'2025-11-24T11:56:45.546Z',
	1821,
	'[{"day":"Monday","hours":"9â¯AM to 4:30â¯PM"},{"hours":"9â¯AM to 4:30â¯PM","day":"Tuesday"},{"hours":"9â¯AM to 4:30â¯PM","day":"Wednesday"},{"day":"Thursday","hours":"9â¯AM to 4:30â¯PM"},{"hours":"9â¯AM to 4:30â¯PM","day":"Friday"},{"hours":"9â¯AM to 3:30â¯PM","day":"Saturday"},{"hours":"9â¯AM to 3:30â¯PM","day":"Sunday"}]',
	'{"Payments":["Credit cards","Debit cards","NFC mobile payments"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/p/AF1QipMCQY0PBqGb2pxamP-GGptWhKNXX4B5IyDY2S3f=w408-h478-k-no'
),(
	'IE-dublin',
	TRUE,
	'Aviva Stadium',
	'Bóthar Lansdún,',
	'Large stadium with an unusual glass end used for international sports and occasional concerts.',
	'Tourist attraction',
	'Lansdowne Rd, Dublin 4, Ireland',
	'https://www.avivastadium.ie/',
	'+353 1 238 2300',
	53.3351738,
	-6.2279515,
	4.6,
	'["Tourist attraction","Stadium"]',
	'2025-11-24T11:56:44.733Z',
	17179,
	'[]',
	'{"Children":["Has changing table(s)"],"Amenities":["Restroom"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"],"Service options":["Onsite services"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyyVwZzfLEyzVpaZ7bM8O1DfXQohQ3dcyw505D0wmER6pkGqrBZZGv2Kp8kFzRN99e0btiqYTzOiiNppZ82PDS85Fb8CtSs07alJLqet2JEp6A11vyyrptiQNo10s9e4xP0KCBorw=w408-h408-k-no'
),(
	'IE-dublin',
	TRUE,
	'MoLI – Museum of Literature Ireland',
	'',
	'Terraced, Georgian-era villas open for tours of stucco interiors & exhibitions on Irish literature.',
	'Museum',
	'UCD Naughton Joyce Centre, 86 St Stephen&apos;s Green, Saint Kevin&apos;s, Dublin, D02 XY43, Ireland',
	'http://www.moli.ie/',
	'+353 1 716 5900',
	53.3367903,
	-6.2601607,
	4.6,
	'["Museum","Tourist attraction"]',
	'2025-11-24T11:56:44.126Z',
	1013,
	'[{"hours":"10:30â¯AM to 5:30â¯PM","day":"Monday"},{"day":"Tuesday","hours":"10:30â¯AM to 5:30â¯PM"},{"day":"Wednesday","hours":"10:30â¯AM to 5:30â¯PM"},{"hours":"10:30â¯AM to 5:30â¯PM","day":"Thursday"},{"day":"Friday","hours":"10:30â¯AM to 5:30â¯PM"},{"day":"Saturday","hours":"10:30â¯AM to 5:30â¯PM"},{"day":"Sunday","hours":"10:30â¯AM to 5:30â¯PM"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Assistive hearing loop"],"Service options":["Onsite services"],"Parking":["Paid parking lot"],"Amenities":["Restaurant","Restroom","Wi-Fi","Free Wi-Fi"],"Children":["Good for kids"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxnV0gUl0Dfph0_VyXP85zupVE3QybDZuR4MmQgW6pYcwD6GkvcUdHYRcSSFhCTfcqPAHznuX2mrrVzrw0g8MKINiDCb97bnh3IkPcJiQTmOJ6e1T5tir3GwMsRxE8M7OWn9iW6=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'St Stephen&apos;s Green',
	'Faiche Stiabhna',
	'City centre park with ornamental lake, waterfall, sculptures and a children&apos;s playground.',
	'Tourist attraction',
	'St Stephen&apos;s Green, Dublin 2, Ireland',
	'http://ststephensgreenpark.ie/',
	'+353 1 475 7816',
	53.3381736,
	-6.259119,
	4.7,
	'["Tourist attraction","Garden","Park"]',
	'2025-11-24T11:56:43.542Z',
	32468,
	'[{"hours":"7:30â¯AM to 5â¯PM","day":"Monday"},{"hours":"7:30â¯AM to 5â¯PM","day":"Tuesday"},{"hours":"7:30â¯AM to 5â¯PM","day":"Wednesday"},{"hours":"7:30â¯AM to 5â¯PM","day":"Thursday"},{"hours":"7:30â¯AM to 5â¯PM","day":"Friday"},{"hours":"7:30â¯AM to 5â¯PM","day":"Saturday"},{"day":"Sunday","hours":"9:30â¯AM to 5â¯PM"}]',
	'{"Amenities":["Public restroom","Slides","Swings"],"Children":["Good for kids","Playground"],"Pets":["Dogs allowed"],"Highlights":["Picnics"],"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyKAymknAj1BxVDTiNKBTZj4kTJklZqoxGPUwQWMKyYitMIM2sFz7ktpOTC29_4o81JYPeGXA1W8qn4VLT24LfvMbx63sIfv0cqgufiihrBiUTInHIbpf7xlQKrZTfFtSq5Z9rAgg=w408-h307-k-no'
),(
	'IE-dublin',
	TRUE,
	'St Anne&apos;s Park',
	'Páirc Naomh Áine',
	'Sprawling green space with tennis courts, gardens & follies like the Clocktower & Fairy Door Tree.',
	'Park',
	'Clontarf East, Dublin, Ireland',
	'',
	'+353 1 222 8933',
	53.3718307,
	-6.1793446,
	4.8,
	'["Park"]',
	'2025-11-24T11:56:36.314Z',
	5379,
	'[{"day":"Monday","hours":"Open 24 hours"},{"day":"Tuesday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Wednesday"},{"hours":"Open 24 hours","day":"Thursday"},{"hours":"Open 24 hours","day":"Friday"},{"hours":"Open 24 hours","day":"Saturday"},{"day":"Sunday","hours":"Open 24 hours"}]',
	'{"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Pets":["Dog park","Dogs allowed"],"Highlights":["Picnics"],"Activities":["Hiking"],"Children":["Good for kids","Good for kids birthday","Kid-friendly hikes","Playground"],"Amenities":["Cycling lanes","Has a tennis court","Picnic tables","Public restroom","Slides","Swings"],"Payments":["Credit cards","Debit cards","NFC mobile payments"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSymLtyHdPsHwS4bI7hUWSDpv-39w-LB44UCSWt_ARkZrgo3nceJWm-PHyxi_ovjfGwkkuV-T7swvQrU5rvJXYc96CWHvyP7VXiX0IUMX3MoXy6DwoDaZ35V3QW-nS0S2-pqSwqM=w408-h884-k-no'
),(
	'IE-dublin',
	TRUE,
	'Dublin Mosque',
	'',
	'',
	'Tourist attraction',
	'163 S Circular Rd, Dublin 8, D08 F642, Ireland',
	'http://islaminireland.com/',
	'+353 1 453 3242',
	53.3309915,
	-6.2818096,
	4.8,
	'["Tourist attraction","Mosque"]',
	'2025-11-24T11:56:36.080Z',
	1366,
	'[{"hours":"10â¯AM to 5â¯PM","day":"Monday"},{"day":"Tuesday","hours":"10â¯AM to 5â¯PM"},{"day":"Wednesday","hours":"10â¯AM to 5â¯PM"},{"day":"Thursday","hours":"10â¯AM to 5â¯PM"},{"hours":"10â¯AM to 5â¯PM","day":"Friday"},{"hours":"Closed","day":"Saturday"},{"hours":"Closed","day":"Sunday"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"],"Service options":["Onsite services"],"Amenities":["Restroom"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzs-ODnhJ_hydcAPArgHfXjFP9QyS8uVboNqscZ_8zxYWoyHxTHV1ug3jXVD44WjhW5Fx_FN4CECwMLK0GgDgZeyVuxIhz18hPpeL1xywifdYB0B26_vDzHIkpd9RecCd_HaK70=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'Herbert Park',
	'',
	'',
	'Park',
	'Herbert Park, Dublin, Ireland',
	'',
	'+353 1 222 5278',
	53.3263689,
	-6.2349694,
	4.7,
	'["Park"]',
	'2025-11-24T11:56:35.684Z',
	1708,
	'[{"day":"Monday","hours":"10â¯AM to 9:30â¯PM"},{"hours":"10â¯AM to 9:30â¯PM","day":"Tuesday"},{"hours":"10â¯AM to 9:30â¯PM","day":"Wednesday"},{"hours":"10â¯AM to 9:30â¯PM","day":"Thursday"},{"hours":"10â¯AM to 9:30â¯PM","day":"Friday"},{"hours":"10â¯AM to 9:30â¯PM","day":"Saturday"},{"hours":"10â¯AM to 9:30â¯PM","day":"Sunday"}]',
	'{"Payments":["Debit cards","NFC mobile payments"],"Amenities":["Cycling lanes","Has a tennis court","Picnic tables","Slides","Swings"],"Children":["Good for kids","Good for kids birthday","Playground"],"Highlights":["Picnics"],"Pets":["Dog park","Dogs allowed"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Service options":["Onsite services"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwdm2NSi9ZH7XUlktlpZUe_2lvRehIH-DoW9l8ISPG5QORRsQKYSiyKuBsZjZFi_6GVOebgSLPuLnyOsrgBTYmsgotxsHjujdWcp2nMYxXpzZD5UANQao7TDPLlWnnVWhNOtTbFUw=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'Eamonn Ceannt Park',
	'',
	'Sprawling green with tennis & basketball courts, a running track & soccer fields, plus a velodrome.',
	'Tourist attraction',
	'Clogher Rd, Crumlin, Dublin, Ireland',
	'http://www.dublincity.ie/main-menu-services-recreation-culture-dublin-city-parks-visit-park/eamonn-ceannt-park',
	'+353 1 454 0799',
	53.3231477,
	-6.2922037,
	4.6,
	'["Tourist attraction","City park"]',
	'2025-11-24T11:56:35.684Z',
	1096,
	'[{"day":"Monday","hours":"10â¯AM to 10â¯PM"},{"hours":"10â¯AM to 10â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"10â¯AM to 10â¯PM"},{"hours":"10â¯AM to 10â¯PM","day":"Thursday"},{"hours":"10â¯AM to 10â¯PM","day":"Friday"},{"day":"Saturday","hours":"10â¯AM to 10â¯PM"},{"day":"Sunday","hours":"10â¯AM to 10â¯PM"}]',
	'{"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Pets":["Dogs allowed"],"Highlights":["Picnics"],"Children":["Good for kids","Good for kids birthday","Playground"],"Amenities":["Basketball court","Cycling lanes","Has a tennis court","Picnic tables","Slides","Swings"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxluduTyq9HjVu_8lxeXnNoco1Pcug7q05LJZUqbv9lTFARNFNajlPitPHz1G6ZBbkDOMVaVDrGLZA9lQm7ziPFwRZtIF0FQYfvIdHtrS8p7KepG2MC540-17fYv1xSNf9FOQG8yQ=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'Jameson Distillery Bow St.',
	'',
	'Expert guides tell the story of Jameson in a recreated distillery scene with tastings and dining.',
	'Distillery',
	'Bow St, Smithfield, Dublin 7, D07 N9VH, Ireland',
	'https://www.jamesonwhiskey.com/en-ie/visit-our-distilleries/jameson-bow-street-distillery-tour/',
	'+353 1 807 2355',
	53.3481851,
	-6.2770289,
	4.7,
	'["Distillery","Bar","Historical landmark","Tourist attraction","Visitor center"]',
	'2025-11-24T11:56:33.708Z',
	5515,
	'[{"day":"Monday","hours":"10:30â¯AM to 6â¯PM"},{"hours":"10:30â¯AM to 6â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"10:30â¯AM to 6â¯PM"},{"day":"Thursday","hours":"10:30â¯AM to 6â¯PM"},{"day":"Friday","hours":"10â¯AM to 7â¯PM"},{"hours":"10â¯AM to 7â¯PM","day":"Saturday"},{"day":"Sunday","hours":"11:45â¯AM to 6â¯PM"}]',
	'{"Payments":["Credit cards","Debit cards","Credit cards"],"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Wheelchair accessible seating"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxhp_dOARaDG-BQVJyi2WxbC2irJzAHt_cBbl1HXdQHqViocCAPBvFIE2QEDAXJRgpxoHh514lkrjyWxCTeiV8Glr2EGPp-aL_Zy1HHpBebZNRgeulA_XhcUSQmvHCeMpCiM2kS5TjmqJbu=w408-h272-k-no'
),(
	'IE-dublin',
	TRUE,
	'Mountjoy Square Park',
	'Cearnóg Mhuinseo',
	'Leafy Georgian garden with a soccer field & tennis court, plus a playground & 1800s granite sundial.',
	'Tourist attraction',
	'Mountjoy Square, Mountjoy, Dublin, Ireland',
	'',
	'+353 1 855 4030',
	53.3566348,
	-6.2574474,
	4.2,
	'["Tourist attraction","Park"]',
	'2025-11-24T11:56:31.533Z',
	3649,
	'[{"day":"Monday","hours":"8â¯AM to 10â¯PM"},{"day":"Tuesday","hours":"8â¯AM to 10â¯PM"},{"hours":"8â¯AM to 10â¯PM","day":"Wednesday"},{"hours":"8â¯AM to 10â¯PM","day":"Thursday"},{"day":"Friday","hours":"8â¯AM to 10â¯PM"},{"hours":"8â¯AM to 10â¯PM","day":"Saturday"},{"day":"Sunday","hours":"8â¯AM to 10â¯PM"}]',
	'{"Children":["Good for kids","Playground"],"Amenities":["Basketball court","Slides","Swings"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Pets":["Dog park","Dogs allowed"],"Highlights":["Picnics"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyr7Xpje-d7cw07DkPqjQvMRzE3Pl_hwdDq026qYXar_sVL6dzxs11My18j9xN4fXeduE1mkv4dXKkP-HgTTjobYh9Uz5a9gNqst5g4IBYD5O3yGtgV5845Inrk27xYSsomL8t4=w425-h240-k-no'
),(
	'IE-dublin',
	TRUE,
	'Griffith Park',
	'',
	'',
	'Tourist attraction',
	'27 St Michael&apos;s Rd, Drumcondra, Dublin 9, D09 C8W7, Ireland',
	'http://www.dublincity.ie/main-menu-services-recreation-culture-dublin-city-parks-visit-park/griffith-park',
	'+353 1 222 5278',
	53.3699941,
	-6.261508,
	4.7,
	'["Tourist attraction","Park"]',
	'2025-11-24T11:56:30.682Z',
	1912,
	'[{"hours":"Open 24 hours","day":"Monday"},{"hours":"Open 24 hours","day":"Tuesday"},{"hours":"Open 24 hours","day":"Wednesday"},{"day":"Thursday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Friday"},{"hours":"Open 24 hours","day":"Saturday"},{"hours":"Open 24 hours","day":"Sunday"}]',
	'{"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Pets":["Dogs allowed"],"Highlights":["Picnics"],"Children":["Good for kids","Good for kids birthday","Playground"],"Amenities":["Picnic tables","Slides","Swings"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwvmsISa4x4iYe0fQyoFwZ14XckNwWtIk78v8bjqjQyjxCLj86Fd84D3H1Vke5VPztD3aR9YIh8rNzQXkKQ3IjOvI0i02rvmr2kLubOzxAetkIj5_JOfwhI11NtW0IEFppzkwqkxA=w426-h240-k-no'
),(
	'IE-dublin',
	TRUE,
	'Blessington Basin',
	'',
	'',
	'Tourist attraction',
	'28 Primrose Ave, Phibsborough, Dublin 7, D07 E0X8, Ireland',
	'',
	'',
	53.3571323,
	-6.26982,
	4.6,
	'["Tourist attraction","Park"]',
	'2025-11-24T11:56:30.682Z',
	1463,
	'[{"day":"Monday","hours":"10â¯AM to 5:30â¯PM"},{"day":"Tuesday","hours":"10â¯AM to 5:30â¯PM"},{"hours":"10â¯AM to 5:30â¯PM","day":"Wednesday"},{"day":"Thursday","hours":"10â¯AM to 5:30â¯PM"},{"hours":"10â¯AM to 5:30â¯PM","day":"Friday"},{"day":"Saturday","hours":"10â¯AM to 5:30â¯PM"},{"hours":"10â¯AM to 5:30â¯PM","day":"Sunday"}]',
	'{"Amenities":["Picnic tables"],"Children":["Good for kids"],"Pets":["Dogs allowed"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxly5zdlmJKf-WOq6ZgIJw0hCPtTlbCQyHvjNnT0If4Tx53lXSd-k7r5ZUhooI7BWyjjos1dT7n41DuFFtkM2nH5x8fVFPtk3XLyZA0yOgf1-dL54NhJlcfM-KDhUpZmHb_fZ9jZA=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Famine Memorial',
	'',
	'Poignant, life-sized statues depicting starving people to commemorate Ireland&apos;s 19th-century famine.',
	'Tourist attraction',
	'Custom House Quay, North Wall, Dublin, Ireland',
	'https://www.visitdublin.com/see-do/details/famine-memorial',
	'',
	53.3480473,
	-6.2500367,
	4.7,
	'["Tourist attraction","Sculpture","Memorial"]',
	'2025-11-24T11:56:30.682Z',
	1368,
	'[{"hours":"Open 24 hours","day":"Monday"},{"day":"Tuesday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Wednesday"},{"hours":"Open 24 hours","day":"Thursday"},{"day":"Friday","hours":"Open 24 hours"},{"day":"Saturday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Sunday"}]',
	'{"Accessibility":["Wheelchair accessible entrance"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzHgvizvAwlr6ywrgn0A938j7cesrQOHocN_TZLKFzJhuqSs5bYUn1ODG7QEpGB8gw32USTRMhSnWWS1s5AONtt7yzWtS9fvDf0XJWK-8K_1D4Df8uHy6r0jd5IZNxo1BJgV7Er=w408-h612-k-no'
),(
	'IE-dublin',
	TRUE,
	'O&apos;Connell Monument',
	'',
	'',
	'Tourist attraction',
	'O&apos;Connell Street Lower, North City, Dublin 1, D01 TX31, Ireland',
	'http://www.buildingsofireland.ie/niah/search.jsp?type=record&county=DU&regno=50010320',
	'',
	53.34777,
	-6.2593458,
	4.4,
	'["Tourist attraction","Monument"]',
	'2025-11-24T11:56:30.656Z',
	2193,
	'[{"hours":"Open 24 hours","day":"Monday"},{"day":"Tuesday","hours":"Open 24 hours"},{"day":"Wednesday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Thursday"},{"day":"Friday","hours":"Open 24 hours"},{"day":"Saturday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Sunday"}]',
	'{"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance"],"Parking":["Paid parking lot"],"Children":["Good for kids"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSymuvB4hoCd0uq0c39HrnhvStx2b7reHPLUEw9dy0ioc1fKKKosv4dgACVje3Ye3xcf9DYUtn0vOVrNb85cXAbQiSGrXhNJbvyJgQJLSv_9Ti2RFkszblC2Y_bGGIg8dPclwcQ=w408-h544-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Jeanie Johnston Famine Ship',
	'',
	'Tours below and above deck of a replica, 19th-century ship that took Irish emigrants to America.',
	'Tourist attraction',
	'Custom House Quay, North Wall, Dublin 1, D01 T9C2, Ireland',
	'https://jeaniejohnston.ie/?utm_source=googlemybusiness&utm_medium=referral',
	'+353 1 473 0111',
	53.3476481,
	-6.2468158,
	4.7,
	'["Tourist attraction","Cultural landmark","History museum","Museum"]',
	'2025-11-24T11:56:29.993Z',
	1885,
	'[{"hours":"10â¯AM to 4:30â¯PM","day":"Monday"},{"hours":"10â¯AM to 4:30â¯PM","day":"Tuesday"},{"hours":"10â¯AM to 4:30â¯PM","day":"Wednesday"},{"hours":"10â¯AM to 4:30â¯PM","day":"Thursday"},{"day":"Friday","hours":"10â¯AM to 4:30â¯PM"},{"hours":"10â¯AM to 4:30â¯PM","day":"Saturday"},{"day":"Sunday","hours":"10â¯AM to 4:30â¯PM"}]',
	'{"Service options":["Onsite services"],"Children":["Good for kids"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Crowd":["Family-friendly"],"Planning":["Getting tickets in advance recommended"],"Amenities":["Restaurant","Restroom"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSys4o-xnvsF7yCX7ti6slBsQEtd1gVnj_YoSP42oMc9AU0YhEK_3cYr88pjkscxE9UveqQk_p1F3i5zyLVXJ38HJvmIoMppHbOocgMTaZXtnh6XpjKBmZByBshJQNUabQ9l-KbWsw=w426-h240-k-no'
),(
	'IE-dublin',
	TRUE,
	'Iveagh Gardens',
	'Gairdíní Uíbh Eachach',
	'Unique collection of garden landscapes designed in 1865 and mostly restored since 1995.',
	'Tourist attraction',
	'St Stephen&apos;s Green, Park, Dublin 2, D02 HX65, Ireland',
	'http://www.iveaghgardens.ie/',
	'+353 1 475 7816',
	53.3351376,
	-6.2610343,
	4.7,
	'["Tourist attraction","Garden"]',
	'2025-11-24T11:56:29.993Z',
	4512,
	'[{"hours":"8â¯AM to 4:30â¯PM","day":"Monday"},{"hours":"8â¯AM to 4:30â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"8â¯AM to 4:30â¯PM"},{"day":"Thursday","hours":"8â¯AM to 4:30â¯PM"},{"day":"Friday","hours":"8â¯AM to 4:30â¯PM"},{"day":"Saturday","hours":"8â¯AM to 4:30â¯PM"},{"day":"Sunday","hours":"10â¯AM to 4:30â¯PM"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Pets":["Dogs allowed"],"Highlights":["Picnics"],"Children":["Good for kids"],"Payments":["NFC mobile payments"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxqEoiJJocLZQGhqMpq2dLQzaucG2l3DHiyTnSVZbvK4PBdB0-NFkjOporii3DaEf7LW6dOdVKVmCz8IOt1udmmrrSK5EihVOD0syCqbNzd3cxgvPhWyiZcMswjni7vjiQlUQL9wQ=w426-h240-k-no'
),(
	'IE-dublin',
	TRUE,
	'St Patrick’s Park',
	'',
	'',
	'Tourist attraction',
	'Bull Alley St, Dublin, Ireland',
	'',
	'+353 1 475 5435',
	53.3402425,
	-6.2711649,
	4.6,
	'["Tourist attraction","Park"]',
	'2025-11-24T11:56:29.992Z',
	4726,
	'[{"day":"Monday","hours":"7:30â¯AM to 9â¯PM"},{"day":"Tuesday","hours":"7:30â¯AM to 9â¯PM"},{"day":"Wednesday","hours":"7:30â¯AM to 9â¯PM"},{"hours":"7:30â¯AM to 9â¯PM","day":"Thursday"},{"day":"Friday","hours":"7:30â¯AM to 9â¯PM"},{"day":"Saturday","hours":"7:30â¯AM to 9â¯PM"},{"hours":"7:30â¯AM to 9â¯PM","day":"Sunday"}]',
	'{"Accessibility":["Wheelchair accessible entrance"],"Service options":["Onsite services"],"Highlights":["Picnics"],"Pets":["Dog park","Dogs allowed"],"Children":["Good for kids","Playground"],"Payments":["Credit cards"],"Amenities":["Public restroom","Swings"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwGKfhWpIczn6gxAG1P_pq9MXcRiPZCl0jwh4cr7S3x9I199sigQeuSo-rx2Hkw5jM2oZkVYy8mEENd-EsstvKEt4DUentlWCa7z4hQx1lpdxoy7MJkLAz4Xme8Sgl4_rMfqJ0r=w408-h544-k-no'
),(
	'IE-dublin',
	TRUE,
	'Garden of Remembrance',
	'',
	'Formal garden remembering all those who gave their lives in the cause of Irish freedom.',
	'Tourist attraction',
	'Parnell Square E, Rotunda, Dublin 1, D01 A0F8, Ireland',
	'https://heritageireland.ie/places-to-visit/garden-of-remembrance/',
	'+353 1 821 3021',
	53.3537619,
	-6.2641935,
	4.6,
	'["Tourist attraction","Garden","Park","Memorial park","War memorial"]',
	'2025-11-24T11:56:29.992Z',
	2766,
	'[{"day":"Monday","hours":"8:30â¯AM to 6â¯PM"},{"hours":"8:30â¯AM to 6â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"8:30â¯AM to 6â¯PM"},{"day":"Thursday","hours":"8:30â¯AM to 6â¯PM"},{"day":"Friday","hours":"8:30â¯AM to 6â¯PM"},{"day":"Saturday","hours":"8:30â¯AM to 6â¯PM"},{"hours":"8:30â¯AM to 6â¯PM","day":"Sunday"}]',
	'{"Pets":["Dogs allowed"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Children":["Good for kids"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyVX-Cnu1Hgue7QYSk4a-VXAjlv89myQ3a-uxWnOTXRZZHX4mXNqR-AvcBjKvw0tjxMPvGfjvnzIwY4cLbHGq7IjwnZWTI7aJ2tWzXBZQeKQ_-oY9L5S6_E-gxDPNOXF5FyVlmykg=w408-h725-k-no'
),(
	'IE-dublin',
	TRUE,
	'National Gallery of Ireland',
	'Gailearaí Náisiúnta na hÉireann',
	'Grand collection of European art spanning the 14th to the 21st-century, covering all major schools.',
	'Tourist attraction',
	'Merrion Square W, Dublin 2, D02 K303, Ireland',
	'https://www.nationalgallery.ie/',
	'+353 1 661 5133',
	53.3408887,
	-6.2522962,
	4.7,
	'["Tourist attraction","Gift shop","Art gallery"]',
	'2025-11-24T11:56:29.336Z',
	17233,
	'[{"hours":"11â¯AM to 5:30â¯PM","day":"Monday"},{"day":"Tuesday","hours":"9:15â¯AM to 5:30â¯PM"},{"day":"Wednesday","hours":"9:15â¯AM to 5:30â¯PM"},{"hours":"9:15â¯AM to 8:30â¯PM","day":"Thursday"},{"hours":"9:15â¯AM to 5:30â¯PM","day":"Friday"},{"hours":"9:15â¯AM to 5:30â¯PM","day":"Saturday"},{"day":"Sunday","hours":"11â¯AM to 5:30â¯PM"}]',
	'{"Children":["Good for kids"],"Highlights":["Live performances"],"Service options":["Onsite services"],"Amenities":["Restaurant","Restroom","Wi-Fi","Free Wi-Fi"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"],"Crowd":["Family-friendly"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxnrz0JoWO0VOn9LVd1zoF13gnU8zgFJkG2tpFfNzKS9EtABBJnTrkmRVTX8O1RZxjcX-qTgcO1XMLd7WaZw__MIp70WnHryltQhp3Mif7-L-mmMCYGoMulJrWY9WvdsFJns4fqOg=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Royal Hospital Kilmainham',
	'',
	'Versatile rooms for banquetting, concerts or lectures within 17th-century home for retired soldiers.',
	'Tourist attraction',
	'Military Rd, Saint James, Dublin 8, Ireland',
	'',
	'+353 1 612 9903',
	53.3429206,
	-6.3000339,
	4.6,
	'["Tourist attraction","Event venue","Historical place"]',
	'2025-11-24T11:56:24.405Z',
	1272,
	'[{"hours":"8â¯AM to 7â¯PM","day":"Monday"},{"day":"Tuesday","hours":"8â¯AM to 7â¯PM"},{"hours":"8â¯AM to 7â¯PM","day":"Wednesday"},{"hours":"8â¯AM to 7â¯PM","day":"Thursday"},{"hours":"8â¯AM to 7â¯PM","day":"Friday"},{"day":"Saturday","hours":"8â¯AM to 7â¯PM"},{"day":"Sunday","hours":"8â¯AM to 7â¯PM"}]',
	'{"Parking":["Paid parking lot"],"Children":["Good for kids"],"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzisL1VOiECJFuT-LqNgpmEjreJ6u_qw9u3oPdxBOyHqRmHZ8azMu7fZtanjtDb7tXkMATG3tp-bJWRrQJigN0Kt5Z78FpkXx78Emfo0ZrU1su0ABnUUW91UlfLaFZQb_QWQeomcw=w408-h305-k-no'
),(
	'IE-dublin',
	TRUE,
	'Bushy Park',
	'',
	'Riverside park with woodland, pond, children&apos;s playground, football pitches and tennis courts.',
	'Tourist attraction',
	'Terenure, Dublin, Ireland',
	'https://www.dublincity.ie/ga/node/4537',
	'+353 1 490 0320',
	53.3025499,
	-6.2943383,
	4.6,
	'["Tourist attraction","Park"]',
	'2025-11-24T11:56:24.071Z',
	4443,
	'[{"day":"Monday","hours":"10â¯AM to 8:30â¯PM"},{"day":"Tuesday","hours":"10â¯AM to 8:30â¯PM"},{"hours":"10â¯AM to 8:30â¯PM","day":"Wednesday"},{"hours":"10â¯AM to 8:30â¯PM","day":"Thursday"},{"day":"Friday","hours":"10â¯AM to 8:30â¯PM"},{"day":"Saturday","hours":"10â¯AM to 8:30â¯PM"},{"day":"Sunday","hours":"10â¯AM to 8:30â¯PM"}]',
	'{"Highlights":["Picnics"],"Pets":["Dogs allowed"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Service options":["Onsite services"],"Parking":["Paid street parking"],"Amenities":["Basketball court","Cycling lanes","Has a tennis court","Public restroom","Skateboarding area","Slides","Swings"],"Children":["Good for kids","Playground"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwxk5kOp8y449LsXdW8MTMV0dT_2rr3877z9mUsRX4bDWGC-QnlbOpQTzYyhxaFh-bb0F_gWRd_5uW1euJ64BUd2eYlf2K4MYVZl-mFbf5jbetGiVAay855IIjc9l0jYfGhUIWG=w408-h272-k-no'
),(
	'IE-dublin',
	TRUE,
	'Wellington Monument',
	'Leacht Wellington',
	'Imposing 62m obelisk built to commemorate victories of Arthur Wellesley, 1st Duke of Wellington.',
	'Tourist attraction',
	'Phoenix Park, Saint James, Dublin, Ireland',
	'',
	'+353 1 647 6635',
	53.3490364,
	-6.303101,
	4.6,
	'["Tourist attraction","Monument"]',
	'2025-11-24T11:56:23.759Z',
	2004,
	'[{"day":"Monday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Tuesday"},{"day":"Wednesday","hours":"Open 24 hours"},{"day":"Thursday","hours":"Open 24 hours"},{"day":"Friday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Saturday"},{"day":"Sunday","hours":"Open 24 hours"}]',
	'{"Parking":["Free street parking"],"Children":["Good for kids"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyYBjgb342r2XKTJ65icwrEVcSKRsjgvkW2DAXCTIZIumrS7aNGbVyYBH2cXOWVtHDnlidixZkBw4mGfFvEKiFdFCOdrm6BAEsRwO2uBEJTp3VkqF59jnbHKX0SGQcLyF3uV4dF=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'Irish National War Memorial Gardens',
	'Gairdíní Náisiúnta Cuimhneacháin Cogaidh na hÉireann',
	'Elegant, Lutyens-designed gardens dedicated to the 49,400 Irish soldiers who died during WWI.',
	'Tourist attraction',
	'Island Bridge, Ushers, Dublin, Ireland',
	'https://heritageireland.ie/places-to-visit/irish-national-war-memorial-gardens/',
	'',
	53.3454216,
	-6.3172574,
	4.8,
	'["Tourist attraction","Memorial park"]',
	'2025-11-24T11:56:23.759Z',
	2535,
	'[{"day":"Monday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Tuesday"},{"hours":"Open 24 hours","day":"Wednesday"},{"day":"Thursday","hours":"Open 24 hours"},{"day":"Friday","hours":"Open 24 hours"},{"day":"Saturday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Sunday"}]',
	'{"Amenities":["Cycling lanes","Picnic tables"],"Children":["Good for kids"],"Pets":["Dogs allowed"],"Highlights":["Picnics"],"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyWAPB9Tl5ZKr5e8rOlkp5qo2ZzWy7p6D5ndSGWs1O7JtrltYXwWLI9Cb6GJiSRUX_4VWgeoZX-miZzp8R5pebKVuwVZP3NIrR5Nm1mVOoj9KqYghuiTHjloxuYju5F0nAsCR8=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'Irish Museum of Modern Art',
	'Aras Nua-Ealaíne na hÉireann',
	'Imposing building from 1684 housing permanent collection and temporary exhibitions of varied art.',
	'Modern art museum',
	'Royal Hospital Kilmainham, Military Rd, Kilmainham, Dublin 8, D08 FW31, Ireland',
	'https://imma.ie/',
	'+353 1 612 9900',
	53.3425871,
	-6.2999286,
	4.3,
	'["Modern art museum","Art museum","Tourist attraction"]',
	'2025-11-24T11:56:23.429Z',
	4898,
	'[{"day":"Monday","hours":"Closed"},{"hours":"10â¯AM to 5:30â¯PM","day":"Tuesday"},{"hours":"11:30â¯AM to 5:30â¯PM","day":"Wednesday"},{"day":"Thursday","hours":"10â¯AM to 5:30â¯PM"},{"day":"Friday","hours":"10â¯AM to 5:30â¯PM"},{"day":"Saturday","hours":"10â¯AM to 5:30â¯PM"},{"day":"Sunday","hours":"12 to 5:30â¯PM"}]',
	'{"Children":["Good for kids","Has changing table(s)"],"Amenities":["Restaurant","Restroom","Wi-Fi","Free Wi-Fi"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"],"Crowd":["Family-friendly"],"Service options":["Onsite services"],"Highlights":["Live performances"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxxh-XiSsLOUHnUCyzKBF99O15sydRelpcIqieZ0JD6aFZfrlScXa-pE6itCkmba8j_ygtkF6LgIAfZPD9HICMWMuizG09pmj7GqvbLG5h3MEY9noRABpiL1oUHaVs_FX-0hd2O=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'14 Henrietta Street',
	'',
	'Tours tell the story of a 1740s house carefully restored to grandeur after falling into disrepair.',
	'Tourist attraction',
	'14 Henrietta St, Dublin 1, D01 HH34, Ireland',
	'https://14henriettastreet.ie/',
	'+353 1 524 0383',
	53.3523798,
	-6.2701587,
	4.8,
	'["Tourist attraction","Museum"]',
	'2025-11-24T11:56:18.657Z',
	1726,
	'[{"hours":"Closed","day":"Monday"},{"hours":"Closed","day":"Tuesday"},{"day":"Wednesday","hours":"10â¯AM to 4â¯PM"},{"day":"Thursday","hours":"10â¯AM to 6â¯PM"},{"hours":"10â¯AM to 4â¯PM","day":"Friday"},{"hours":"10â¯AM to 4â¯PM","day":"Saturday"},{"hours":"10â¯AM to 4â¯PM","day":"Sunday"}]',
	'{"Children":["Good for kids"],"Parking":["Paid street parking"],"Planning":["Getting tickets in advance recommended"],"Amenities":["Gender-neutral restroom","Restroom","Wi-Fi","Free Wi-Fi","Restaurant"],"Crowd":["Family-friendly"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom"],"Service options":["Onsite services"],"Highlights":["Live performances"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz3etTD1wK7C1nE_g_7OhHxK3NZUNxhJE5yZ9kQ1-XuxShSTR4uNxrjRNeBdQ8goNjkslG_-KKQR2ViDBpFWNvfuGetVfrW31M5cDTeLxCH-8I1sE-s_yosP3130Q2dOROWEEHy=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Cock and Bull Coolock',
	'',
	'',
	'Bar',
	'Main St, Coolock Village Cl, Kilmore, Dublin 5, D05 AE73, Ireland',
	'https://thecockandbull.ie/',
	'+353 1 867 1919',
	53.3891735,
	-6.200831,
	4.1,
	'["Bar","Beer garden","Cocktail bar","Function room facility","Gastropub","Live music venue","Night club","Parking lot","Restaurant","Sports bar"]',
	'2025-11-24T11:56:11.984Z',
	1382,
	'[{"hours":"10:30â¯AM to 12â¯AM","day":"Monday"},{"hours":"10:30â¯AM to 12â¯AM","day":"Tuesday"},{"day":"Wednesday","hours":"10:30â¯AM to 12â¯AM"},{"hours":"10:30â¯AM to 12â¯AM","day":"Thursday"},{"hours":"10:30â¯AM to 2:30â¯AM","day":"Friday"},{"hours":"10:30â¯AM to 2:30â¯AM","day":"Saturday"},{"day":"Sunday","hours":"12â¯PM to 12â¯AM"}]',
	'{"Highlights":["Great beer selection","Great cocktails","Great wine list","Live music","Live performances","Sports"],"Atmosphere":["Casual","Cozy","Trendy"],"Service options":["Outdoor seating","Takeout","Dine-in","Delivery"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Amenities":["Restroom"],"Planning":["Accepts reservations"],"Crowd":["Groups"],"Popular for":["Solo dining"],"Offerings":["Alcohol","Beer","Cocktails","Dancing","Food","Food at bar","Hard liquor","Wine"],"Parking":["Free parking lot","Free street parking","Usually plenty of parking"],"Dining options":["Seating","Table service"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"]}',
	'https://lh3.googleusercontent.com/p/AF1QipMwtMLPl6oAE07n0bVcd6Au9mlii9n4_lWdLEaR=w427-h240-k-no'
),(
	'IE-dublin',
	TRUE,
	'Woodie&apos;s Coolock',
	'',
	'Home improvement chain selling decorating products, gardening tools & plants, plus homewares.',
	'Hardware store',
	'Malahide Rd, Priorswood, Dublin 17, D17 TD70, Ireland',
	'https://www.woodies.ie/?utm_source=gmb-listing&utm_medium=organic&utm_campaign=gmb-listing-coolock',
	'+353 1 848 5923',
	53.3946495,
	-6.1907758,
	4.1,
	'["Hardware store","Building materials store","Do-it-yourself shop","Furniture store","Garden center","Garden furniture shop","Home improvement store","Key duplication service","Paint store","Party store","Tool store"]',
	'2025-11-24T11:56:11.984Z',
	2951,
	'[{"hours":"9â¯AM to 9â¯PM","day":"Monday"},{"day":"Tuesday","hours":"9â¯AM to 9â¯PM"},{"day":"Wednesday","hours":"9â¯AM to 9â¯PM"},{"day":"Thursday","hours":"9â¯AM to 9â¯PM"},{"hours":"9â¯AM to 9â¯PM","day":"Friday"},{"hours":"9â¯AM to 7â¯PM","day":"Saturday"},{"day":"Sunday","hours":"10â¯AM to 6â¯PM"}]',
	'{"Recycling":["Batteries"],"Planning":["Quick visit"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Parking":["Free parking lot"],"Service options":["Delivery","In-store pickup","Onsite services","Same-day delivery"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwc9gtGDfT7Z690417-0oRhbellHRfrNc0Cl5DXsasb71vL2WePH3BRgavmtV7y86GaActPLIKGvuIWPSSNfnUp5wtvA0fanIJva5ZLjYizOtKMyn70uJ6j2HGiC0FgI2oR8l4cNw=w408-h544-k-no'
),(
	'IE-dublin',
	TRUE,
	'Father Collins Park',
	'',
	'Public park with sleek wind turbines & a dramatic water feature, plus a running track & playgrounds.',
	'Tourist attraction',
	'Hole in The Wall Rd, Donaghmede, Co. Dublin, Ireland',
	'',
	'+353 1 222 5278',
	53.4052231,
	-6.1607677,
	4.5,
	'["Tourist attraction","Park"]',
	'2025-11-24T11:56:11.614Z',
	1799,
	'[{"hours":"10â¯AM to 8:30â¯PM","day":"Monday"},{"hours":"10â¯AM to 8:30â¯PM","day":"Tuesday"},{"hours":"10â¯AM to 8:30â¯PM","day":"Wednesday"},{"day":"Thursday","hours":"10â¯AM to 8:30â¯PM"},{"hours":"10â¯AM to 8:30â¯PM","day":"Friday"},{"day":"Saturday","hours":"10â¯AM to 8:30â¯PM"},{"day":"Sunday","hours":"10â¯AM to 8:30â¯PM"}]',
	'{"Children":["Good for kids","Playground"],"Amenities":["Cycling lanes","Picnic tables","Skateboarding area","Slides","Swings"],"Accessibility":["Wheelchair-accessible car park","Wheelchair-accessible entrance"],"Pets":["Dogs allowed"],"Highlights":["Picnics"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxjfaVv04P3tZ_LlcHhE5CtPqeGtvlDMG-FAY523lTKLuK2g2AxPdHKcAttkjj8Q7QcCcWtkUfkrOMNnubs0EU_CnZjXUN9pYmulqbzqgdfWEQrHoG_qcYikWZ9vjLE4Wkf-c1M=w426-h240-k-no'
),(
	'IE-dublin',
	TRUE,
	'North Bull Island',
	'',
	'Nature preserve featuring a long beach, scenic hiking areas & views of migrating birds & wildlife.',
	'Tourist attraction',
	'Dublin, Ireland',
	'http://www.northbullisland.com/',
	'',
	53.3690367,
	-6.1478517,
	4.6,
	'["Tourist attraction","Nature preserve"]',
	'2025-11-24T11:56:10.916Z',
	4117,
	'[{"day":"Monday","hours":"Open 24 hours"},{"day":"Tuesday","hours":"Open 24 hours"},{"day":"Wednesday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Thursday"},{"day":"Friday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Saturday"},{"day":"Sunday","hours":"Open 24 hours"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Amenities":["Cycling lanes","Picnic tables","Public restroom"],"Payments":["NFC mobile payments"],"Activities":["Hiking"],"Highlights":["Picnics"],"Pets":["Dogs allowed"],"Service options":["Onsite services"],"Children":["Good for kids","Kid-friendly hikes"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyya9UJk_gkjelShHpE-llbEXl8rBbQFKOtL3KRv0DHbfWTZ6cHlEUW09L2jbqSs5M98V4PlT3_JBXAxAdPIuYZVg5jxFLFU3ZCTgK2wBqpkXkOFmxS1dZB2T_-1KzGZXAvAgfR=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'GAA Museum & Tours',
	'',
	'Museum of Gaelic sports (Gaelic football, hurling, handball and camogie) with interactive exhibits.',
	'Tourist attraction',
	'St Joseph&apos;s Ave, Drumcondra, Dublin, D03 P6K7, Ireland',
	'https://crokepark.ie/tours',
	'+353 1 819 2323',
	53.3606949,
	-6.2494275,
	4.6,
	'["Tourist attraction","Museum"]',
	'2025-11-24T11:56:10.404Z',
	1067,
	'[{"day":"Monday","hours":"9:30â¯AM to 5â¯PM"},{"hours":"9:30â¯AM to 5â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"9:30â¯AM to 5â¯PM"},{"day":"Thursday","hours":"9:30â¯AM to 5â¯PM"},{"hours":"9:30â¯AM to 5â¯PM","day":"Friday"},{"day":"Saturday","hours":"9:30â¯AM to 5â¯PM"},{"hours":"12:30 to 3:30â¯PM","day":"Sunday"}]',
	'{"Amenities":["Restaurant","Restroom"],"Planning":["Getting tickets in advance recommended"],"Parking":["Free parking lot"],"Children":["Good for kids"],"Highlights":["Live performances"],"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxv2ZQGc5bub3e6QDu4VB5MrStGv5bND8xzXr0wm5aT5gmiK0EWCh4m0-rDaAKK3Zf9PGa73JpJVFUTJl8S6f3QIcJ7DyIovc3tMEDGk7fCEbakt60RkzTxz2-1NW0x4HGqdwdk=w410-h240-k-no'
),(
	'IE-dublin',
	TRUE,
	'Phoenix Park Visitor Centre',
	'',
	'Displays on park wildlife & Celtic history in a restored 15th-century castle with a walled garden.',
	'Visitor center',
	'Phoenix Park, Dublin, Ireland',
	'http://www.phoenixpark.ie/',
	'+353 1 677 0095',
	53.3661176,
	-6.3309742,
	4.6,
	'["Visitor center","Tourist attraction"]',
	'2025-11-24T11:56:10.404Z',
	1682,
	'[{"day":"Monday","hours":"9:30â¯AM to 5â¯PM"},{"day":"Tuesday","hours":"9:30â¯AM to 5â¯PM"},{"day":"Wednesday","hours":"9:30â¯AM to 5â¯PM"},{"hours":"9:30â¯AM to 5â¯PM","day":"Thursday"},{"day":"Friday","hours":"9:30â¯AM to 5â¯PM"},{"day":"Saturday","hours":"9:30â¯AM to 5â¯PM"},{"hours":"9:30â¯AM to 5â¯PM","day":"Sunday"}]',
	'{"Amenities":["Restroom"],"Payments":["Credit cards","Debit cards","NFC mobile payments"],"Children":["Good for kids"],"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxw3bK69joLrvrLP0strjEnAcgbFYnzGB9ZRQl00w_gXFSh-YOJgWU_xfRyDSr4LLRrJkxy6EXtpKTmwd6tFn5k2EWrp7DO8u4dN_9BQYVNZcxqnCw6wugA0EICZoH_M0_gmZyJPF1OrITP=w408-h544-k-no'
),(
	'IE-dublin',
	TRUE,
	'The National Wax Museum Plus',
	'',
	'Family museum containing hundreds of wax versions of famous Irish and international personalities.',
	'Tourist attraction',
	'The Lafayette Building, 22-25 Westmoreland St, Temple Bar, Dublin 2, D02 EH29, Ireland',
	'https://www.waxmuseumplus.ie/',
	'+353 1 671 8373',
	53.346644,
	-6.2587802,
	4.1,
	'["Tourist attraction","Museum","National museum","Wax museum"]',
	'2025-11-24T11:56:07.059Z',
	5039,
	'[{"day":"Monday","hours":"10â¯AM to 7â¯PM"},{"day":"Tuesday","hours":"10â¯AM to 7â¯PM"},{"day":"Wednesday","hours":"10â¯AM to 7â¯PM"},{"hours":"10â¯AM to 7â¯PM","day":"Thursday"},{"day":"Friday","hours":"10â¯AM to 7â¯PM"},{"hours":"10â¯AM to 7â¯PM","day":"Saturday"},{"hours":"10â¯AM to 7â¯PM","day":"Sunday"}]',
	'{"Amenities":["Restroom","Wi-Fi","Free Wi-Fi","Restaurant"],"Children":["Good for kids"],"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Wheelchair accessible parking lot"],"Crowd":["Family-friendly"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxso5v3LMwOy0Gp33Bl-xm9NQizveM7dsttgaQ6u1-9RNyk4zzdybAnFdSp2s-FE3ZPSwzpnuANH3TE3tzXdYcF5SV9AI2nR6f2pxO3flboK4arBl976V1KBBmrNN-8MhBwbRiG=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Oscar Wilde Monument',
	'',
	'Set in a historic square, this memorial sculpture was erected in 1997 & consists of 3 major pieces.',
	'Tourist attraction',
	'Merrion Square N, Dublin, Ireland',
	'https://www.visitdublin.com/guides/oscar-wildes-dublin',
	'',
	53.3408162,
	-6.2505294,
	4.6,
	'["Tourist attraction","Sculpture"]',
	'2025-11-24T11:56:07.059Z',
	1935,
	'[]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyDQZxSuboi4rb7FwgrH9nZseNUpTlhj2iIfBGMSVxwUi3rd4clpmodwZvH0_bus3yzw46BSepk82ix8E_z_0y528lfJXFV5wxrrOzzddUiJN6Es2oIlYiY1o-jZQwX-F2C_PSR=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'Experience Glasnevin - Ireland&apos;s National Cemetery',
	'',
	'Victorian burial ground of many prominent Irish figures, plus a museum with interactive displays.',
	'Visitor center',
	'Finglas Rd, Glasnevin, Dublin, D11 H2TH, Ireland',
	'https://www.dctrust.ie/experience-glasnevin.html?utm_source=google&utm_medium=gmb',
	'+353 1 882 6550',
	53.3696223,
	-6.2770345,
	4.8,
	'["Visitor center","Tourist attraction"]',
	'2025-11-24T11:56:07.059Z',
	1296,
	'[{"day":"Monday","hours":"10â¯AM to 5â¯PM"},{"day":"Tuesday","hours":"10â¯AM to 5â¯PM"},{"day":"Wednesday","hours":"10â¯AM to 5â¯PM"},{"hours":"10â¯AM to 5â¯PM","day":"Thursday"},{"day":"Friday","hours":"10â¯AM to 5â¯PM"},{"hours":"10â¯AM to 5â¯PM","day":"Saturday"},{"day":"Sunday","hours":"10â¯AM to 5â¯PM"}]',
	'{"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"],"Children":["Good for kids"],"Planning":["Getting tickets in advance recommended"],"Payments":["Credit cards","Debit cards","NFC mobile payments"],"Amenities":["Restroom"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSynDDmQD1Tfur1ocUdE5-74XPmHwQsO6ToSIrMeBZkbum7_FGZfNa6r8n3HI4XhWGW560L-n1oyUp7xQv2tBCLdF9rbpqAPmEJmFpA9_4PJ_sKDf5IFi5CcwA_5JzAm3J__8zGl=w408-h537-k-no'
),(
	'IE-dublin',
	TRUE,
	'Molly Malone Statue',
	'Mol Ní Mhaoileoin',
	'Bronze statue of a fictional fishmonger named Molly Malone, the star of a well-known Irish song.',
	'Tourist attraction',
	'Suffolk St, Dublin 2, D02 KX03, Ireland',
	'https://www.visitdublin.com/molly-malone',
	'+353 1 222 2222',
	53.3437409,
	-6.2609725,
	4.4,
	'["Tourist attraction","Monument","Sculpture"]',
	'2025-11-24T11:56:07.058Z',
	13575,
	'[{"hours":"Open 24 hours","day":"Monday"},{"day":"Tuesday","hours":"Open 24 hours"},{"day":"Wednesday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Thursday"},{"hours":"Open 24 hours","day":"Friday"},{"day":"Saturday","hours":"Open 24 hours"},{"day":"Sunday","hours":"Open 24 hours"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Service options":["Onsite services"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSztJfzN2HpfQNimGguXbklwbbvYG-S-CRZx1SHExV1MfSAwaZ1MQFaB2wlPEMr4DmvWDKLMLGdt76UoIQvuXNRBFTnz957xhWonGqC_aYZlqboNqkrONPHojScXKq70XhWybQzU=w408-h408-k-no'
),(
	'IE-dublin',
	TRUE,
	'Irish Whiskey Museum',
	'',
	'Guided tours tracing the history of whiskey through interactive exhibits, plus a tasting at the end.',
	'Tourist attraction',
	'119 Grafton Street, Dublin, D02 E620, Ireland',
	'https://irishwhiskeymuseum.ie/',
	'+353 1 525 0970',
	53.344198,
	-6.259525,
	4.7,
	'["Tourist attraction","Heritage museum","History museum","Museum"]',
	'2025-11-24T11:56:07.058Z',
	7433,
	'[{"day":"Monday","hours":"10â¯AM to 7:30â¯PM"},{"day":"Tuesday","hours":"10â¯AM to 7:30â¯PM"},{"day":"Wednesday","hours":"10â¯AM to 7:30â¯PM"},{"day":"Thursday","hours":"10â¯AM to 7:30â¯PM"},{"day":"Friday","hours":"10â¯AM to 10â¯PM"},{"day":"Saturday","hours":"10â¯AM to 10â¯PM"},{"day":"Sunday","hours":"10â¯AM to 7:30â¯PM"}]',
	'{"Crowd":["Family-friendly"],"Accessibility":["Wheelchair accessible restroom","Wheelchair accessible parking lot"],"Service options":["Onsite services"],"Planning":["Getting tickets in advance recommended"],"Amenities":["Restroom","Wi-Fi","Free Wi-Fi","Restaurant"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSy6e87VqI49UE81TR7cbqnyzUMci_NXFNXmvNkzsXlIheZtHvFSteG_GUIokdSCVp_pr5azJCgtv6gUU6lHMKmkWOprGVa8QvEEt-wlOL3EX8VYUX1MLtQdHUL2EQPFEPqYeJqt=w408-h544-k-no'
),(
	'IE-dublin',
	TRUE,
	'Phoenix Park',
	'Páirc an Fhionnuisce',
	'Wild deer, a zoo & a fort feature in this 708-hectare park known as &apos;Dublin&apos;s playground&apos;.',
	'Tourist attraction',
	'Dublin 8, Ireland',
	'https://www.phoenixpark.ie/',
	'+353 1 820 5800',
	53.3558823,
	-6.3298133,
	4.7,
	'["Tourist attraction","Park"]',
	'2025-11-24T11:56:07.058Z',
	40806,
	'[{"hours":"Open 24 hours","day":"Monday"},{"day":"Tuesday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Wednesday"},{"day":"Thursday","hours":"Open 24 hours"},{"day":"Friday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Saturday"},{"day":"Sunday","hours":"Open 24 hours"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"],"Service options":["Onsite services"],"Highlights":["Picnics"],"Pets":["Dog park","Dogs allowed"],"Children":["Good for kids","Good for kids birthday","Kid-friendly hikes","Playground"],"Activities":["Hiking"],"Parking":["Free parking lot"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Amenities":["Cycling lanes","Picnic tables","Public restroom","Slides","Swings"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSybdIradEq2brhVCqJPF_5TEbHusxD-yo_k_paMr6HU1tmjW3gd_ZnnJUp2aK1W84eW3tzE5HQmgPljobJP7fNlQCC_znWR-YcduZwr_YyTvD1VRtx5b0LLjIWqBIBavwwq15Cy=w408-h272-k-no'
),(
	'IE-dublin',
	TRUE,
	'Dublin Zoo',
	'Zú Bhaile Átha Cliath',
	'The largest zoo in Ireland has African Plain, Fringes of the Arctic and Asian Forests exhibits.',
	'Tourist attraction',
	'Phoenix park, Saint James, Dublin, D08 AC98, Ireland',
	'https://www.dublinzoo.ie/',
	'+353 1 474 8900',
	53.3572232,
	-6.3071091,
	4.6,
	'["Tourist attraction","Zoo"]',
	'2025-11-24T11:56:07.058Z',
	28333,
	'[{"day":"Monday","hours":"9:30â¯AM to 4â¯PM"},{"hours":"9:30â¯AM to 4â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"9:30â¯AM to 4â¯PM"},{"day":"Thursday","hours":"9:30â¯AM to 4â¯PM"},{"hours":"9:30â¯AM to 4â¯PM","day":"Friday"},{"day":"Saturday","hours":"9:30â¯AM to 4â¯PM"},{"day":"Sunday","hours":"9:30â¯AM to 4â¯PM"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Service options":["Onsite services"],"Parking":["Free parking lot","Free street parking"],"Planning":["Getting tickets in advance recommended"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Children":["Good for kids","Good for kids birthday","Playground"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwMYM4YBKlwonzEbaM8uspJxwZwj6Fd_mzA4SRSZM6c0CZWWDFKrI95gxJSD7m6UTPFsof_qfkGFAEPJQoOFPuVCxsxm0u-J_6M1w0XyFjoT2q3_vLziSk99yYGzTmLGLYHVuSC=w408-h307-k-no'
),(
	'IE-dublin',
	TRUE,
	'National Leprechaun Museum of Ireland',
	'',
	'Family-friendly museum with interactive exhibits telling stories about Ireland&apos;s mythical creatures.',
	'Tourist attraction',
	'2-3, Mary&apos;s Abbey, North City, Dublin, D07 X6R6, Ireland',
	'http://www.leprechaunmuseum.ie/',
	'+353 1 873 3899',
	53.3473649,
	-6.2686696,
	4.2,
	'["Tourist attraction","Museum"]',
	'2025-11-24T11:56:07.058Z',
	3636,
	'[{"hours":"10â¯AM to 6:30â¯PM","day":"Monday"},{"day":"Tuesday","hours":"10â¯AM to 6:30â¯PM"},{"day":"Wednesday","hours":"10â¯AM to 6:30â¯PM"},{"hours":"10â¯AM to 9:30â¯PM","day":"Thursday"},{"hours":"12â¯AM to 9:30â¯PM","day":"Friday"},{"hours":"10â¯AM to 9:30â¯PM","day":"Saturday"},{"hours":"10â¯AM to 6:30â¯PM","day":"Sunday"}]',
	'{"Service options":["Onsite services"],"Highlights":["Live performances"],"Children":["Good for kids"],"Crowd":["Family-friendly","LGBTQ+ friendly","Transgender safespace"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Wheelchair accessible parking lot"],"Planning":["Getting tickets in advance recommended"],"Payments":["Admission fee"],"Amenities":["Gender-neutral restroom","Restroom","Restaurant"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxJNMl3dLNnMx4xyZge5azt8vMzeX56tSo-s2hWC_k4yO_ccnymqUan8cOARCHNEz2Gosh53kWgrMkTOh8zWThxY591hRGjRsZjUXpHrtBzsM_3r8IzpDtNDbneHgxfFxBLZoxd=w408-h544-k-no'
),(
	'IE-dublin',
	TRUE,
	'Kilmainham Gaol',
	'Músaem Phríosún Chill Mhaighneann',
	'Prison museum where many of Ireland&apos;s political prisoners were incarcerated, tortured and executed.',
	'Tourist attraction',
	'Inchicore Rd, Kilmainham, Dublin 8, D08 RK28, Ireland',
	'https://www.kilmainhamgaolmuseum.ie/',
	'+353 1 453 5984',
	53.3418701,
	-6.3098048,
	4.7,
	'["Tourist attraction","Prison","Museum"]',
	'2025-11-24T11:56:07.057Z',
	2474,
	'[{"day":"Monday","hours":"9:30â¯AM to 5:45â¯PM"},{"day":"Tuesday","hours":"9:30â¯AM to 5:45â¯PM"},{"day":"Wednesday","hours":"9:30â¯AM to 5:45â¯PM"},{"day":"Thursday","hours":"9:30â¯AM to 5:45â¯PM"},{"day":"Friday","hours":"9:30â¯AM to 5:45â¯PM"},{"hours":"9:30â¯AM to 5:45â¯PM","day":"Saturday"},{"hours":"9:30â¯AM to 5:45â¯PM","day":"Sunday"}]',
	'{"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom"],"Service options":["Onsite services"],"Amenities":["Restaurant","Restroom"],"Planning":["Getting tickets in advance recommended"],"Children":["Good for kids"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzCx1AE-N5wYZR1kg8nFvN923kuq6LpJa_0zquOUD9NTWeJ9ITPSfyYUkCUU3JowUEzOXnDwgsQmJZT4tqJXpbb8C6TKHshmpX2OzsyRkTRLJWUfk2hI3ielnW_7wyTkr0gjFAt=w408-h341-k-no'
),(
	'IE-dublin',
	TRUE,
	'Horse Show House',
	'',
	'',
	'Pub',
	'34-36 Merrion Rd, Ballsbridge, Dublin 4, D04 C535, Ireland',
	'http://www.horseshowhouse.ie/',
	'+353 1 668 9424',
	53.3285787,
	-6.2288803,
	4.2,
	'["Pub","Bar","Beer garden","Function room facility","Lunch restaurant"]',
	'2025-11-24T11:56:06.503Z',
	1638,
	'[{"hours":"Closed","day":"Monday"},{"hours":"12 to 11:30â¯PM","day":"Tuesday"},{"hours":"12 to 11:30â¯PM","day":"Wednesday"},{"day":"Thursday","hours":"12 to 11:30â¯PM"},{"day":"Friday","hours":"12â¯PM to 12:30â¯AM"},{"day":"Saturday","hours":"12â¯PM to 12:30â¯AM"},{"day":"Sunday","hours":"12 to 11â¯PM"}]',
	'{"Planning":["Accepts reservations"],"Amenities":["Restroom","Wi-Fi","Free Wi-Fi"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Crowd":["Groups","Tourists"],"Atmosphere":["Casual","Cozy","Trendy"],"Service options":["Outdoor seating","Takeout","Dine-in","Delivery"],"Highlights":["Great beer selection","Great cocktails","Great wine list","Live music","Live performances","Rooftop seating","Sports"],"Parking":["Paid street parking","Usually difficult to find a space"],"Offerings":["Alcohol","Beer","Cocktails","Food","Food at bar","Hard liquor","Wine"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Wheelchair accessible seating"],"Dining options":["Seating","Table service"],"Popular for":["Solo dining"]}',
	'https://lh3.googleusercontent.com/p/AF1QipOaso8Ob8tMmGueq-S-fcJFJgEA86pZzJqiN8Yr=w408-h241-k-no'
),(
	'IE-dublin',
	TRUE,
	'GPO Museum',
	'',
	'Popular immersive & interactive attraction & tourist hub on the 1916 Easter Rising aftermath.',
	'History museum',
	'O&apos;Connell Street Lower, North City, Dublin 1, D01 F5P2, Ireland',
	'https://www.gpomuseum.ie/',
	'+353 1 872 1916',
	53.3495282,
	-6.2606027,
	4.6,
	'["History museum","Gift shop","Historical landmark","Museum","Tourist attraction"]',
	'2025-11-24T11:56:04.639Z',
	2421,
	'[{"day":"Monday","hours":"10â¯AM to 5â¯PM"},{"day":"Tuesday","hours":"10â¯AM to 5â¯PM"},{"day":"Wednesday","hours":"10â¯AM to 5â¯PM"},{"day":"Thursday","hours":"10â¯AM to 5â¯PM"},{"hours":"10â¯AM to 5â¯PM","day":"Friday"},{"day":"Saturday","hours":"10â¯AM to 5â¯PM"},{"hours":"Closed","day":"Sunday"}]',
	'{"Amenities":["Restroom"],"Children":["Good for kids"],"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom"]}',
	'https://lh3.googleusercontent.com/p/AF1QipNILca0CvzC_yn-43LCbKeUsWS4GeitdHKJfstH=w408-h241-k-no'
),(
	'IE-dublin',
	TRUE,
	'Christ Church Cathedral',
	'Ardeaglais Theampall Chríost',
	'Medieval place of worship with a mummified rat & cat plus a cafe & gift shop in the crypt.',
	'Tourist attraction',
	'Christchurch Pl, Wood Quay, Dublin, D08 TF98, Ireland',
	'https://christchurchcathedral.ie/',
	'+353 1 677 8099',
	53.343513,
	-6.2710602,
	4.5,
	'["Tourist attraction","Church","Place of worship","Cathedral"]',
	'2025-11-24T11:56:04.639Z',
	11180,
	'[{"day":"Monday","hours":"9:30â¯AM to 5â¯PM"},{"hours":"9:30â¯AM to 5â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"9:30â¯AM to 5â¯PM"},{"hours":"9:30â¯AM to 5â¯PM","day":"Thursday"},{"day":"Friday","hours":"9:30â¯AM to 5â¯PM"},{"day":"Saturday","hours":"9:30â¯AM to 5â¯PM"},{"hours":"Closed","day":"Sunday"}]',
	'{"Amenities":["Gender-neutral restroom","Restroom"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Service options":["Onsite services"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwoeXmqHnSM3VHYCqMxGJmVAHHBNkZotvtQd-eZYtZYnHS_V-TfUjX_ieFI4WBtKUZqwW0YuouBKrR_5PDW5FN3TM2r3hrVCU3KTMZm33REohOckntlnN64g_4Rm5cPHuWzZROUqQ=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'National Museum of Ireland, Collins Barracks',
	'',
	'Irish haute couture and silver collections alongside exhibitions exploring Irish military history.',
	'National museum',
	'Collins Barracks, Benburb St, Stoneybatter, Dublin, D07 XKV4, Ireland',
	'https://www.museum.ie/en-IE/Museums/Decorative-Arts-History',
	'+353 1 677 7444',
	53.3489404,
	-6.2863653,
	4.6,
	'["National museum","Cultural center","History museum","Museum","Tourist attraction"]',
	'2025-11-24T11:56:04.639Z',
	6264,
	'[{"day":"Monday","hours":"1 to 5â¯PM"},{"hours":"10â¯AM to 5â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"10â¯AM to 5â¯PM"},{"day":"Thursday","hours":"10â¯AM to 5â¯PM"},{"hours":"10â¯AM to 5â¯PM","day":"Friday"},{"day":"Saturday","hours":"10â¯AM to 5â¯PM"},{"day":"Sunday","hours":"1 to 5â¯PM"}]',
	'{"Highlights":["Live performances"],"Service options":["Onsite services"],"Children":["Good for kids","Has changing table(s)"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"],"Crowd":["Family-friendly","LGBTQ+ friendly"],"Amenities":["Cafe","Offers tours","Restroom","Wi-Fi","Free Wi-Fi","Restaurant"],"Offerings":["Gift shop"],"Parking":["On-site parking","Paid parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyfDFviZto_guWQht293urtQ30_ImU_oCBiZJk7SDLYbe99DynIv60qfC3VpEH8hsFrOsHf0nG1jjS0NbaVkoYb3hegttP1-1Bz4XkilNoQNQKaqrV9F8wxz2C0W-SE3Vv-HQkn=w408-h272-k-no'
),(
	'IE-dublin',
	TRUE,
	'Guinness Storehouse',
	'',
	'Brewery experience telling the tale of Ireland&apos;s famous beer, with tastings and a rooftop bar.',
	'Brewery',
	'St. James&apos;s Gate, Dublin 8, D08 VF8H, Ireland',
	'https://www.guinness-storehouse.com/en/home?utm_source=Google&utm_medium=Organic&utm_campaign=gsh_google_my_business&utm_id=Google+My+Business+',
	'+353 1 408 4800',
	53.3418088,
	-6.2867155,
	4.4,
	'["Brewery","Tourist attraction"]',
	'2025-11-24T11:56:04.639Z',
	23339,
	'[{"hours":"9â¯AM to 2:30â¯PM","day":"Monday"},{"day":"Tuesday","hours":"11â¯AM to 5â¯PM"},{"day":"Wednesday","hours":"10â¯AM to 5â¯PM"},{"day":"Thursday","hours":"10â¯AM to 5â¯PM"},{"day":"Friday","hours":"10â¯AM to 5â¯PM"},{"day":"Saturday","hours":"9:30â¯AM to 5â¯PM"},{"day":"Sunday","hours":"9:30â¯AM to 5â¯PM"}]',
	'{"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Offerings":["Alcohol","Beer"],"Amenities":["Bar onsite"],"Service options":["Onsite services","Delivery"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxJSNxAo-aGK8kn0BCJB7D43ob7dO62B3Go4fLJCUNBDboX20VcjbA-XqpdEn__2T1FIIe-bmQELfPajzavWNXspSp13tG9jH9DON-Nik_P37UXh_F706S7qjRziNW9djp2sG7iUQ=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Spire',
	'',
	'Stainless steel tapered column stretching 120 meters up, known as a symbol of the city.',
	'Tourist attraction',
	'O&apos;Connell Street Upper, North City, Dublin, Ireland',
	'http://www.visitdublin.com/see-do/details/the-spire/31186/',
	'',
	53.349825,
	-6.2602557,
	4.3,
	'["Tourist attraction","Sculpture"]',
	'2025-11-24T11:56:04.639Z',
	10723,
	'[{"day":"Monday","hours":"Open 24 hours"},{"day":"Tuesday","hours":"Open 24 hours"},{"day":"Wednesday","hours":"Open 24 hours"},{"day":"Thursday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Friday"},{"day":"Saturday","hours":"Open 24 hours"},{"day":"Sunday","hours":"Open 24 hours"}]',
	'{"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxikwtYk6c_ximj2Z538WrhR1EOTDbRP1PcGlUz8THrjBlQmUgo4vovsFyRnR0MavL6FfqDT4NMlELMEfAAM_qEgrGHVXah9k4jPM-9OIxXAFFIsJdXosOVzph7TaFT6IpMDsFy=w408-h544-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Irish Rock &apos;n&apos; Roll Museum Experience',
	'',
	'',
	'Tourist attraction',
	'Curved St, Temple Bar, Dublin, D02 RD26, Ireland',
	'http://irishrocknrollmuseum.com/',
	'+353 89 449 0795',
	53.344926,
	-6.2644318,
	4.7,
	'["Tourist attraction"]',
	'2025-11-24T11:56:04.638Z',
	1716,
	'[{"hours":"10:30â¯AM to 5â¯PM","day":"Monday"},{"day":"Tuesday","hours":"10:30â¯AM to 5â¯PM"},{"day":"Wednesday","hours":"10:30â¯AM to 5â¯PM"},{"day":"Thursday","hours":"10:30â¯AM to 5â¯PM"},{"hours":"10:30â¯AM to 5â¯PM","day":"Friday"},{"hours":"10:30â¯AM to 5â¯PM","day":"Saturday"},{"hours":"10:30â¯AM to 5â¯PM","day":"Sunday"}]',
	'{"Planning":["Getting tickets in advance recommended"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"],"Amenities":["Restroom"],"Children":["Discounts for kids","Family discount"],"Accessibility":["Wheelchair accessible parking lot"],"Service options":["Onsite services"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxN26_saWoXL6WG8rRiscxkO1O-ASH61mcdiTsSc-izHbI0pncbfp-LowICMCdBthIOAn_ejL5YQEVtWtFYN3xR9CaiWerJfiKItVjiUzFGLFJoq3g6TKxiFjGm_Su1KsqA3IkO1g=w426-h240-k-no'
),(
	'IE-dublin',
	TRUE,
	'EPIC The Irish Emigration Museum',
	'',
	'',
	'Museum',
	'The Chq Building, Custom House Quay, North Wall, Dublin 1, Ireland',
	'https://epicchq.com/?utm_source=mybusiness&utm_medium=organic',
	'+353 1 906 0861',
	53.3483124,
	-6.2481791,
	4.6,
	'["Museum","Event venue","Genealogist","Heritage museum","History museum","Local history museum","National museum","Tourist attraction","Visitor center"]',
	'2025-11-24T11:56:04.638Z',
	10589,
	'[{"day":"Monday","hours":"10â¯AM to 6:30â¯PM"},{"hours":"10â¯AM to 6:30â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"10â¯AM to 6:30â¯PM"},{"hours":"10â¯AM to 6:30â¯PM","day":"Thursday"},{"day":"Friday","hours":"10â¯AM to 6:30â¯PM"},{"day":"Saturday","hours":"10â¯AM to 6:30â¯PM"},{"day":"Sunday","hours":"10â¯AM to 6:30â¯PM"}]',
	'{"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom"],"Crowd":["Family-friendly"],"Children":["Family discount","Good for kids","Has changing table(s)","Kid-friendly activities"],"Planning":["Getting tickets in advance recommended"],"Amenities":["Cafe","Restaurant","Restroom","Wi-Fi","Free Wi-Fi"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwCFxN7ItxVWfECxzh6SAbVhSaIuwyEzz8K-CYQR24F-87Hh581Ama5_PgrxuY4Nte_J0dIeBV3AM70PbfFALQtweVG-uTqUIgbxO3FLTT_0aDj8kKF6GgBvTvFiPIG-yyAlX5ROQ=w408-h541-k-no'
),(
	'IE-dublin',
	TRUE,
	'Ha&apos;penny Bridge',
	'Droichead na Life',
	'Refurbished 19th-century cast-iron span & city symbol, crossed by thousands of pedestrians daily.',
	'Bridge',
	'Ha&apos;penny Bridge, North City, Dublin, Ireland',
	'https://www.bridgesofdublin.ie/bridges/hapenny-bridge',
	'',
	53.3463347,
	-6.2631029,
	4.5,
	'["Bridge","Historical landmark","Tourist attraction"]',
	'2025-11-24T11:56:04.638Z',
	14460,
	'[{"hours":"Open 24 hours","day":"Monday"},{"day":"Tuesday","hours":"Open 24 hours"},{"hours":"Open 24 hours","day":"Wednesday"},{"day":"Thursday","hours":"Open 24 hours"},{"day":"Friday","hours":"Open 24 hours"},{"day":"Saturday","hours":"Open 24 hours"},{"day":"Sunday","hours":"Open 24 hours"}]',
	'{"Amenities":["Restroom"],"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible parking lot"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzwoEN0ifrjHll2ryG5KPHNAn49SG2Chreb5SGJ51TRKpatDwrUMP7ShwoIbAyMVfWPG77brLdxhIOlyFNKV8nuPcLV0pV6ksqkSGa_EdolO7RmsWgYKoo2_qM0Bt3TMHEX3GVz=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'Dubh Linn Garden',
	'',
	'',
	'Tourist attraction',
	'Dublin Castle, Dame St, Dublin, Ireland',
	'https://www.dublincastle.ie/the-castle-gardens/',
	'+353 1 645 8813',
	53.3423616,
	-6.266632,
	4.6,
	'["Tourist attraction","Park"]',
	'2025-11-24T11:56:04.638Z',
	1436,
	'[{"day":"Monday","hours":"6:30â¯AM to 7â¯PM"},{"day":"Tuesday","hours":"6:30â¯AM to 7â¯PM"},{"day":"Wednesday","hours":"6:30â¯AM to 7â¯PM"},{"day":"Thursday","hours":"6:30â¯AM to 7â¯PM"},{"hours":"6:30â¯AM to 7â¯PM","day":"Friday"},{"hours":"6:30â¯AM to 7â¯PM","day":"Saturday"},{"day":"Sunday","hours":"6:30â¯AM to 7â¯PM"}]',
	'{"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance"],"Highlights":["Picnics"],"Children":["Good for kids"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyS3UEXfy5oJeiNmL4ZjIC-TBWIv68Np4T3Zf2rKjI7G8uwfB8y6TxNYFjBfnxYO_uQnZJTMnByuLdobjdkscX_lqc5ZvFPB8gO4FH8oJuQufWsJ52aZzcljb68knfjkebwpjc=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Book of Kells Experience',
	'',
	'Grand library location for illuminated illustrations of the Christian Gospels dating from 800AD.',
	'Tourist attraction',
	'Trinity College, The University of Dublin Trinity College, College Green, South-East Inner City, Dublin, Ireland',
	'https://bookofkellsexperience.ie/',
	'+353 1 896 2320',
	53.343888,
	-6.2567554,
	4.4,
	'["Tourist attraction"]',
	'2025-11-24T11:56:04.638Z',
	17868,
	'[{"hours":"9:30â¯AM to 4:30â¯PM","day":"Monday"},{"day":"Tuesday","hours":"9:30â¯AM to 4:30â¯PM"},{"day":"Wednesday","hours":"9:30â¯AM to 4:30â¯PM"},{"hours":"9:30â¯AM to 4:30â¯PM","day":"Thursday"},{"hours":"9:30â¯AM to 4:30â¯PM","day":"Friday"},{"day":"Saturday","hours":"9:30â¯AM to 5â¯PM"},{"hours":"10â¯AM to 4:30â¯PM","day":"Sunday"}]',
	'{"Service options":["Onsite services"],"Children":["Good for kids"],"Crowd":["LGBTQ+ friendly","Transgender safespace"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Wheelchair accessible parking lot"],"Amenities":["Restroom"],"Planning":["Appointment required","Getting tickets in advance recommended"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"]}',
	'https://lh3.googleusercontent.com/p/AF1QipP_SCKxm5OjBQc3o41cGnn6YG9Tu5sUGBfo_eHR=w408-h272-k-no'
),(
	'IE-dublin',
	TRUE,
	'Dublinia',
	'',
	'Sights and smells bring hundreds of years&apos; worth of history to life at this child-friendly museum.',
	'History museum',
	'St Michaels Hill Christ Church, 5 Meath St, Saint Catherine&apos;s, Dublin 8, D08 VE80, Ireland',
	'https://www.dublinia.ie/',
	'+353 1 679 4611',
	53.343149,
	-6.2720614,
	4.5,
	'["History museum","Local history museum","Museum","Tourist attraction"]',
	'2025-11-24T11:56:04.638Z',
	6883,
	'[{"hours":"10â¯AM to 4â¯PM","day":"Monday"},{"day":"Tuesday","hours":"10â¯AM to 4â¯PM"},{"day":"Wednesday","hours":"10â¯AM to 4â¯PM"},{"hours":"10â¯AM to 4â¯PM","day":"Thursday"},{"hours":"10â¯AM to 4â¯PM","day":"Friday"},{"day":"Saturday","hours":"10â¯AM to 4â¯PM"},{"day":"Sunday","hours":"10â¯AM to 4â¯PM"}]',
	'{"Service options":["Onsite services"],"Crowd":["Family-friendly","LGBTQ+ friendly","Transgender safespace"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Wheelchair accessible seating","Wheelchair accessible parking lot"],"Children":["Good for kids","Has changing table(s)"],"Amenities":["Restroom","Restaurant"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwmIkroampkjn4gi3eNHyixCPaYcM6Sba-KvXRRKKtjUrlDnGCYX8e4Tzoada5Coz5__NDZ_pwAGPHGdDdjUfKyDECfnWW4yWKfG7w6flVeWyLi6RlGKlXSGbVI9zaW_khmYtMr=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'The Little Museum of Dublin',
	'',
	'Museum chronicling remarkable changes to the lifestyles of Dubliners over the the last century.',
	'Museum',
	'15 St Stephen&apos;s Green, Dublin 2, D02 Y066, Ireland',
	'http://www.littlemuseum.ie/',
	'+353 1 661 1000',
	53.3396416,
	-6.2584039,
	4.7,
	'["Museum"]',
	'2025-11-24T11:56:04.638Z',
	5182,
	'[{"day":"Monday","hours":"9:30â¯AM to 4:30â¯PM"},{"day":"Tuesday","hours":"9:30â¯AM to 4:30â¯PM"},{"hours":"9:30â¯AM to 4:30â¯PM","day":"Wednesday"},{"day":"Thursday","hours":"9:30â¯AM to 4:30â¯PM"},{"day":"Friday","hours":"9:30â¯AM to 4:30â¯PM"},{"day":"Saturday","hours":"9:30â¯AM to 4:30â¯PM"},{"hours":"9:30â¯AM to 4:30â¯PM","day":"Sunday"}]',
	'{"Crowd":["Family-friendly","LGBTQ+ friendly","Transgender safespace"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Wheelchair accessible parking lot"],"Service options":["Onsite services"],"Highlights":["Live performances"],"Children":["Good for kids"],"Parking":["Paid street parking"],"Amenities":["Offers tours","Restroom","Restaurant"],"Planning":["Getting tickets in advance recommended"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzpYVlrd5NkUCKbFWiHEqutOuM2bnfzF7HEmcv4CjGlXppsXzzuR_8o-G_wCjfRhPJmj8I7xdJg_QjeGjelnpczysqxm6nA0Vx-tFDvJt2w3N08-FKdpAmSvdGZWSQB0ep194U9NQ=w408-h307-k-no'
),(
	'IE-dublin',
	TRUE,
	'National Museum of Ireland, Kildare Street',
	'Ard-mhúsaem na hÉireann, Sráid Chill Dara',
	'Local archaeological finds from the Bronze Age, Vikings and medieval times with some Egyptian items.',
	'National museum',
	'35A Kildare St, Dublin 2, D02 YK38, Ireland',
	'https://www.museum.ie/Home',
	'+353 1 677 7444',
	53.3402225,
	-6.2549209,
	4.6,
	'["National museum","Archaeological museum","Cultural center","History museum","Museum","Tourist attraction"]',
	'2025-11-24T11:56:04.638Z',
	14394,
	'[{"hours":"1 to 5â¯PM","day":"Monday"},{"day":"Tuesday","hours":"10â¯AM to 5â¯PM"},{"day":"Wednesday","hours":"10â¯AM to 5â¯PM"},{"hours":"10â¯AM to 5â¯PM","day":"Thursday"},{"day":"Friday","hours":"10â¯AM to 5â¯PM"},{"hours":"10â¯AM to 5â¯PM","day":"Saturday"},{"day":"Sunday","hours":"1 to 5â¯PM"}]',
	'{"Parking":["Paid parking garage"],"Amenities":["Offers tours","Restroom","Restaurant"],"Offerings":["Gift shop"],"Crowd":["Family-friendly","LGBTQ+ friendly"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible restroom","Assistive hearing loop","Wheelchair accessible parking lot"],"Children":["Good for kids","Has changing table(s)","Kid-friendly activities"],"Service options":["Onsite services"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyBNjcRc9eQ9P9PzTMziwNSdSgN7qFxmDFqWeWBxjMy-b7YqnP-GspFQQd7LB8ohhgHRU7amf2O-ids1t1fFCrEsulR9XuYeW5dZa-jVcTu13bDPukmA0LYPPjq4H8ZT1b4ZIQpnVi7YAg=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'St Patrick&apos;s Cathedral',
	'Ard-Eaglais Naomh Pádraig',
	'The Church of Ireland&apos;s national cathedral, dating from 1220, with regular musical recitals.',
	'Tourist attraction',
	'St Patrick&apos;s Close, Dublin, D08 H6X3, Ireland',
	'https://www.stpatrickscathedral.ie/',
	'+353 1 453 9472',
	53.3395154,
	-6.2714767,
	4.5,
	'["Tourist attraction","Church","Cathedral"]',
	'2025-11-24T11:56:04.637Z',
	26294,
	'[{"hours":"9:30â¯AM to 5â¯PM","day":"Monday"},{"day":"Tuesday","hours":"9:30â¯AM to 5â¯PM"},{"day":"Wednesday","hours":"9:30â¯AM to 5â¯PM"},{"day":"Thursday","hours":"9:30â¯AM to 5â¯PM"},{"hours":"9:30â¯AM to 5â¯PM","day":"Friday"},{"hours":"9â¯AM to 5â¯PM","day":"Saturday"},{"day":"Sunday","hours":"9 to 10:30â¯AM, 1 to 2:30â¯PM"}]',
	'{"Accessibility":["Wheelchair accessible entrance"],"Service options":["Onsite services"],"Amenities":["Restroom"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz5-aXbWAdd_qYE3-O6O7qoUtk5SvLRr5fgGViY4R33DTaW_draLs0CvCUyJvx9LShHNKQziNoumqp9uVPL0Ca60sG-SFlQlEw98-fbIu6I3LQhISiZ4-_GQEcJrilhcYNGWpdR=w408-h306-k-no'
),(
	'IE-dublin',
	TRUE,
	'Viking Splash Tours',
	'',
	'Tour operator for rides through Dublin in amphibious buses that float along the Grand Canal Basin.',
	'Tour operator',
	'St Stephen&apos;s Green, North, Dublin 2, Ireland',
	'https://vikingsplashdublin.ie/',
	'+353 1 224 3852',
	53.3391018,
	-6.2576678,
	4.5,
	'["Tour operator","Tourist attraction"]',
	'2025-11-24T11:56:04.637Z',
	2415,
	'[{"hours":"9:30â¯AM to 4:30â¯PM","day":"Monday"},{"day":"Tuesday","hours":"9:30â¯AM to 4:30â¯PM"},{"day":"Wednesday","hours":"9:30â¯AM to 4:30â¯PM"},{"hours":"9:30â¯AM to 4:30â¯PM","day":"Thursday"},{"hours":"9:30â¯AM to 4:30â¯PM","day":"Friday"},{"day":"Saturday","hours":"9:30â¯AM to 4:30â¯PM"},{"day":"Sunday","hours":"9:30â¯AM to 4:30â¯PM"}]',
	'{"Children":["Family discount"],"Payments":["Credit cards","Debit cards"],"Accessibility":["Assistive hearing loop","Wheelchair accessible entrance","Wheelchair accessible parking lot","Wheelchair accessible restroom","Wheelchair accessible seating"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxzE17hiSHtbZLSQDfxmP25tJgLJBCzKXPuxEmwWjTE7akHIfiTgGGITJN36giALauU6g0Hnm3LmmSdEogfxaw3m7W1iofI0Z08_VISRD8bV7LXIYsX_1k_qaQxHrcdnuL9z-2K6J9vAeJi=w408-h307-k-no'
),(
	'IE-dublin',
	TRUE,
	'Dublin Castle',
	'Caisleán Bhaile Átha Cliath',
	'Historic site, dating from 1204, with 2 museums, cafes and gardens, plus state rooms and a library.',
	'Tourist attraction',
	'Dame St, Dublin 2, Ireland',
	'https://dublincastle.ie/',
	'+353 46 942 2213',
	53.3428861,
	-6.2674284,
	4.3,
	'["Tourist attraction","Historical place","Historical landmark","Castle"]',
	'2025-11-24T11:56:04.637Z',
	35998,
	'[{"hours":"9:45â¯AM to 5:15â¯PM","day":"Monday"},{"hours":"9:45â¯AM to 5:15â¯PM","day":"Tuesday"},{"day":"Wednesday","hours":"9:45â¯AM to 5:15â¯PM"},{"hours":"9:45â¯AM to 5:15â¯PM","day":"Thursday"},{"hours":"9:45â¯AM to 5:15â¯PM","day":"Friday"},{"hours":"9:45â¯AM to 5:15â¯PM","day":"Saturday"},{"hours":"9:45â¯AM to 5:15â¯PM","day":"Sunday"}]',
	'{"Service options":["Onsite services"],"Accessibility":["Wheelchair accessible entrance","Wheelchair accessible parking lot"],"Children":["Good for kids"],"Payments":["Credit cards","Debit cards","NFC mobile payments","Credit cards"]}',
	'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSy198LiHt4Y2PAEY4jc-JDwWHOnC98jsEwQqld1VmSRDGvopNMnIadqzfqhsnrFO1FzK60cEDl5zS3UIupdT0RLrQ3RHU8GBIqWK-h_a_fXrK4AM6vUoxD7D3IkI-TL82KrEi4=w408-h306-k-no'
);