DROP SCHEMA IF EXISTS iso CASCADE;
CREATE SCHEMA IF NOT EXISTS iso;

-- continents
CREATE TABLE IF NOT EXISTS iso.continents (
    "id" CHAR(2) NOT NULL PRIMARY KEY,
    "name" VARCHAR(20) NOT NULL
);

-- countries
CREATE TABLE IF NOT EXISTS iso.countries (
    "id" CHAR(2) PRIMARY KEY,
    "continent_id" CHAR(2) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "flag" CHAR(2) NOT NULL,
    "tld" CHAR(2) NOT NULL,
    "prefix" VARCHAR(100) NOT NULL,
    "is_eu" BOOLEAN NOT NULL DEFAULT FALSE,
    "is_enabled" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "fk_continent" FOREIGN KEY ("continent_id") REFERENCES iso.continents ("id")
);

--languages
CREATE TABLE IF NOT EXISTS iso.languages (
    "id" CHAR(3) PRIMARY KEY,
    "name" VARCHAR(100) UNIQUE,
    "is_enabled" BOOLEAN NOT NULL DEFAULT FALSE
);

-- country_languages
CREATE TABLE IF NOT EXISTS iso.country_languages (
    "id" SERIAL PRIMARY KEY,
    "country_id" CHAR(2) NOT NULL,
    "language_id" CHAR(3) NOT NULL,
    "is_enabled" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "fk_country" FOREIGN KEY ("country_id") REFERENCES iso.countries ("id"),
    CONSTRAINT "fk_language" FOREIGN KEY ("language_id") REFERENCES iso.languages ("id"),
    UNIQUE ("country_id", "language_id")
);

-- currencies
CREATE TABLE IF NOT EXISTS iso.currencies (
    "id" CHAR(3) NOT NULL PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL
);

-- country_currencies
CREATE TABLE IF NOT EXISTS iso.country_currencies (
    "id" SERIAL PRIMARY KEY,
    "country_id" CHAR(2),
    "currency_id" CHAR(3),
    "is_enabled" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "fk_country" FOREIGN KEY ("country_id") REFERENCES iso.countries ("id"),
    CONSTRAINT "fk_currency" FOREIGN KEY ("currency_id") REFERENCES iso.currencies ("id"),
    UNIQUE ("country_id", "currency_id")
);

-- insert data
INSERT INTO
    iso.continents ("id", "name")
VALUES
    ('AF', 'Africa'),
    ('AN', 'Antarctica'),
    ('AS', 'Asia'),
    ('EU', 'Europe'),
    ('NA', 'North America'),
    ('OC', 'Oceania'),
    ('SA', 'South America');

INSERT INTO
    iso.countries (
        "id",
        "continent_id",
        "name",
        "flag",
        "tld",
        "prefix",
        "is_eu"
    )
VALUES
    ('ad', 'EU', 'Andorra', '🇦🇩', 'ad', '376', false),
    (
        'ae',
        'AS',
        'United Arab Emirates',
        '🇦🇪',
        'ae',
        '971',
        false
    ),
    (
        'af',
        'AS',
        'Afghanistan',
        '🇦🇫',
        'af',
        '93',
        false
    ),
    (
        'ag',
        'NA',
        'Antigua and Barbuda',
        '🇦🇬',
        'ag',
        '1268',
        false
    ),
    (
        'ai',
        'NA',
        'Anguilla',
        '🇦🇮',
        'ai',
        '1264',
        false
    ),
    ('al', 'EU', 'Albania', '🇦🇱', 'al', '355', false),
    ('am', 'AS', 'Armenia', '🇦🇲', 'am', '374', false),
    ('ao', 'AF', 'Angola', '🇦🇴', 'ao', '244', false),
    ('aq', 'AN', 'Antarctica', '🇦🇶', 'aq', '', false),
    (
        'ar',
        'SA',
        'Argentina',
        '🇦🇷',
        'ar',
        '54',
        false
    ),
    (
        'as',
        'OC',
        'American Samoa',
        '🇦🇸',
        'as',
        '1684',
        false
    ),
    ('at', 'EU', 'Austria', '🇦🇹', 'at', '43', true),
    (
        'au',
        'OC',
        'Australia',
        '🇦🇺',
        'au',
        '61',
        false
    ),
    ('aw', 'NA', 'Aruba', '🇦🇼', 'aw', '297', false),
    (
        'ax',
        'EU',
        'Åland Islands',
        '🇦🇽',
        'ax',
        '358',
        false
    ),
    (
        'az',
        'AS',
        'Azerbaijan',
        '🇦🇿',
        'az',
        '994',
        false
    ),
    (
        'ba',
        'EU',
        'Bosnia and Herzegovina',
        '🇧🇦',
        'ba',
        '387',
        false
    ),
    (
        'bb',
        'NA',
        'Barbados',
        '🇧🇧',
        'bb',
        '1246',
        false
    ),
    (
        'bd',
        'AS',
        'Bangladesh',
        '🇧🇩',
        'bd',
        '880',
        false
    ),
    ('be', 'EU', 'Belgium', '🇧🇪', 'be', '32', true),
    (
        'bf',
        'AF',
        'Burkina Faso',
        '🇧🇫',
        'bf',
        '226',
        false
    ),
    ('bg', 'EU', 'Bulgaria', '🇧🇬', 'bg', '359', true),
    ('bh', 'AS', 'Bahrain', '🇧🇭', 'bh', '973', false),
    ('bi', 'AF', 'Burundi', '🇧🇮', 'bi', '257', false),
    ('bj', 'AF', 'Benin', '🇧🇯', 'bj', '229', false),
    (
        'bl',
        'NA',
        'Saint Barthélemy',
        '🇧🇱',
        'bl',
        '590',
        false
    ),
    (
        'bm',
        'NA',
        'Bermuda',
        '🇧🇲',
        'bm',
        '1441',
        false
    ),
    ('bn', 'AS', 'Brunei', '🇧🇳', 'bn', '673', false),
    ('bo', 'SA', 'Bolivia', '🇧🇴', 'bo', '591', false),
    (
        'bq',
        'NA',
        'Caribbean Netherlands',
        '🇧🇶',
        '',
        '599',
        false
    ),
    ('br', 'SA', 'Brazil', '🇧🇷', 'br', '55', false),
    (
        'bs',
        'NA',
        'Bahamas',
        '🇧🇸',
        'bs',
        '1242',
        false
    ),
    ('bt', 'AS', 'Bhutan', '🇧🇹', 'bt', '975', false),
    (
        'bv',
        'AN',
        'Bouvet Island',
        '🇧🇻',
        'bv',
        '',
        false
    ),
    (
        'bw',
        'AF',
        'Botswana',
        '🇧🇼',
        'bw',
        '267',
        false
    ),
    ('by', 'EU', 'Belarus', '🇧🇾', 'by', '375', false),
    ('bz', 'NA', 'Belize', '🇧🇿', 'bz', '501', false),
    ('ca', 'NA', 'Canada', '🇨🇦', 'ca', '1', false),
    (
        'cc',
        'AS',
        'Cocos (Keeling) Islands',
        '🇨🇨',
        'cc',
        '61',
        false
    ),
    (
        'cd',
        'AF',
        'DR Congo',
        '🇨🇩',
        'cd',
        '243',
        false
    ),
    (
        'cf',
        'AF',
        'Central African Republic',
        '🇨🇫',
        'cf',
        '236',
        false
    ),
    (
        'cg',
        'AF',
        'Republic of the Congo',
        '🇨🇬',
        'cg',
        '242',
        false
    ),
    (
        'ch',
        'EU',
        'Switzerland',
        '🇨🇭',
        'ch',
        '41',
        false
    ),
    (
        'ci',
        'AF',
        'Ivory Coast',
        '🇨🇮',
        'ci',
        '225',
        false
    ),
    (
        'ck',
        'OC',
        'Cook Islands',
        '🇨🇰',
        'ck',
        '682',
        false
    ),
    ('cl', 'SA', 'Chile', '🇨🇱', 'cl', '56', false),
    (
        'cm',
        'AF',
        'Cameroon',
        '🇨🇲',
        'cm',
        '237',
        false
    ),
    ('cn', 'AS', 'China', '🇨🇳', 'cn', '86', false),
    ('co', 'SA', 'Colombia', '🇨🇴', 'co', '57', false),
    (
        'cr',
        'NA',
        'Costa Rica',
        '🇨🇷',
        'cr',
        '506',
        false
    ),
    ('cu', 'NA', 'Cuba', '🇨🇺', 'cu', '53', false),
    (
        'cv',
        'AF',
        'Cape Verde',
        '🇨🇻',
        'cv',
        '238',
        false
    ),
    ('cw', 'NA', 'Curaçao', '🇨🇼', 'cw', '599', false),
    (
        'cx',
        'AS',
        'Christmas Island',
        '🇨🇽',
        'cx',
        '61',
        false
    ),
    ('cy', 'EU', 'Cyprus', '🇨🇾', 'cy', '357', true),
    (
        'cz',
        'EU',
        'Czech Republic',
        '🇨🇿',
        'cz',
        '420',
        true
    ),
    ('de', 'EU', 'Germany', '🇩🇪', 'de', '49', true),
    (
        'dj',
        'AF',
        'Djibouti',
        '🇩🇯',
        'dj',
        '253',
        false
    ),
    ('dk', 'EU', 'Denmark', '🇩🇰', 'dk', '45', true),
    (
        'dm',
        'NA',
        'Dominica',
        '🇩🇲',
        'dm',
        '1767',
        false
    ),
    (
        'do',
        'NA',
        'Dominican Republic',
        '🇩🇴',
        'do',
        '1809,1829,1849',
        false
    ),
    ('dz', 'AF', 'Algeria', '🇩🇿', 'dz', '213', false),
    ('ec', 'SA', 'Ecuador', '🇪🇨', 'ec', '593', false),
    ('ee', 'EU', 'Estonia', '🇪🇪', 'ee', '372', true),
    ('eg', 'AF', 'Egypt', '🇪🇬', 'eg', '20', false),
    (
        'eh',
        'AF',
        'Western Sahara',
        '🇪🇭',
        'eh',
        '212',
        false
    ),
    ('er', 'AF', 'Eritrea', '🇪🇷', 'er', '291', false),
    ('es', 'EU', 'Spain', '🇪🇸', 'es', '34', true),
    (
        'et',
        'AF',
        'Ethiopia',
        '🇪🇹',
        'et',
        '251',
        false
    ),
    ('fi', 'EU', 'Finland', '🇫🇮', 'fi', '358', true),
    ('fj', 'OC', 'Fiji', '🇫🇯', 'fj', '679', false),
    (
        'fk',
        'SA',
        'Falkland Islands',
        '🇫🇰',
        'fk',
        '500',
        false
    ),
    (
        'fm',
        'OC',
        'Micronesia',
        '🇫🇲',
        'fm',
        '691',
        false
    ),
    (
        'fo',
        'EU',
        'Faroe Islands',
        '🇫🇴',
        'fo',
        '298',
        false
    ),
    ('fr', 'EU', 'France', '🇫🇷', 'fr', '33', true),
    ('ga', 'AF', 'Gabon', '🇬🇦', 'ga', '241', false),
    (
        'gb',
        'EU',
        'United Kingdom',
        '🇬🇧',
        'uk',
        '44',
        false
    ),
    (
        'gd',
        'NA',
        'Grenada',
        '🇬🇩',
        'gd',
        '1473',
        false
    ),
    ('ge', 'AS', 'Georgia', '🇬🇪', 'ge', '995', false),
    (
        'gf',
        'SA',
        'French Guiana',
        '🇬🇫',
        'gf',
        '594',
        false
    ),
    ('gg', 'EU', 'Guernsey', '🇬🇬', 'gg', '44', false),
    ('gh', 'AF', 'Ghana', '🇬🇭', 'gh', '233', false),
    (
        'gi',
        'EU',
        'Gibraltar',
        '🇬🇮',
        'gi',
        '350',
        false
    ),
    (
        'gl',
        'NA',
        'Greenland',
        '🇬🇱',
        'gl',
        '299',
        false
    ),
    ('gm', 'AF', 'Gambia', '🇬🇲', 'gm', '220', false),
    ('gn', 'AF', 'Guinea', '🇬🇳', 'gn', '224', false),
    (
        'gp',
        'NA',
        'Guadeloupe',
        '🇬🇵',
        'gp',
        '590',
        false
    ),
    (
        'gq',
        'AF',
        'Equatorial Guinea',
        '🇬🇶',
        'gq',
        '240',
        false
    ),
    ('gr', 'EU', 'Greece', '🇬🇷', 'gr', '30', true),
    (
        'gs',
        'AN',
        'South Georgia',
        '🇬🇸',
        'gs',
        '500',
        false
    ),
    (
        'gt',
        'NA',
        'Guatemala',
        '🇬🇹',
        'gt',
        '502',
        false
    ),
    ('gu', 'OC', 'Guam', '🇬🇺', 'gu', '1671', false),
    (
        'gw',
        'AF',
        'Guinea-Bissau',
        '🇬🇼',
        'gw',
        '245',
        false
    ),
    ('gy', 'SA', 'Guyana', '🇬🇾', 'gy', '592', false),
    (
        'hk',
        'AS',
        'Hong Kong',
        '🇭🇰',
        'hk',
        '852',
        false
    ),
    (
        'hm',
        'AN',
        'Heard Island and McDonald Islands',
        '🇭🇲',
        'hm',
        '',
        false
    ),
    (
        'hn',
        'NA',
        'Honduras',
        '🇭🇳',
        'hn',
        '504',
        false
    ),
    ('hr', 'EU', 'Croatia', '🇭🇷', 'hr', '385', true),
    ('ht', 'NA', 'Haiti', '🇭🇹', 'ht', '509', false),
    ('hu', 'EU', 'Hungary', '🇭🇺', 'hu', '36', true),
    (
        'id',
        'AS',
        'Indonesia',
        '🇮🇩',
        'id',
        '62',
        false
    ),
    ('ie', 'EU', 'Ireland', '🇮🇪', 'ie', '353', true),
    ('il', 'AS', 'Israel', '🇮🇱', 'il', '972', false),
    (
        'im',
        'EU',
        'Isle of Man',
        '🇮🇲',
        'im',
        '44',
        false
    ),
    ('in', 'AS', 'India', '🇮🇳', 'in', '91', false),
    (
        'io',
        'AS',
        'British Indian Ocean Territory',
        '🇮🇴',
        'io',
        '246',
        false
    ),
    ('iq', 'AS', 'Iraq', '🇮🇶', 'iq', '964', false),
    ('ir', 'AS', 'Iran', '🇮🇷', 'ir', '98', false),
    ('is', 'EU', 'Iceland', '🇮🇸', 'is', '354', false),
    ('it', 'EU', 'Italy', '🇮🇹', 'it', '39', true),
    ('je', 'EU', 'Jersey', '🇯🇪', 'je', '44', false),
    (
        'jm',
        'NA',
        'Jamaica',
        '🇯🇲',
        'jm',
        '1876',
        false
    ),
    ('jo', 'AS', 'Jordan', '🇯🇴', 'jo', '962', false),
    ('jp', 'AS', 'Japan', '🇯🇵', 'jp', '81', false),
    ('ke', 'AF', 'Kenya', '🇰🇪', 'ke', '254', false),
    (
        'kg',
        'AS',
        'Kyrgyzstan',
        '🇰🇬',
        'kg',
        '996',
        false
    ),
    (
        'kh',
        'AS',
        'Cambodia',
        '🇰🇭',
        'kh',
        '855',
        false
    ),
    (
        'ki',
        'OC',
        'Kiribati',
        '🇰🇮',
        'ki',
        '686',
        false
    ),
    ('km', 'AF', 'Comoros', '🇰🇲', 'km', '269', false),
    (
        'kn',
        'NA',
        'Saint Kitts and Nevis',
        '🇰🇳',
        'kn',
        '1869',
        false
    ),
    (
        'kp',
        'AS',
        'North Korea',
        '🇰🇵',
        'kp',
        '850',
        false
    ),
    (
        'kr',
        'AS',
        'South Korea',
        '🇰🇷',
        'kr',
        '82',
        false
    ),
    ('kw', 'AS', 'Kuwait', '🇰🇼', 'kw', '965', false),
    (
        'ky',
        'NA',
        'Cayman Islands',
        '🇰🇾',
        'ky',
        '1345',
        false
    ),
    (
        'kz',
        'AS',
        'Kazakhstan',
        '🇰🇿',
        'kz',
        '76,77',
        false
    ),
    ('la', 'AS', 'Laos', '🇱🇦', 'la', '856', false),
    ('lb', 'AS', 'Lebanon', '🇱🇧', 'lb', '961', false),
    (
        'lc',
        'NA',
        'Saint Lucia',
        '🇱🇨',
        'lc',
        '1758',
        false
    ),
    (
        'li',
        'EU',
        'Liechtenstein',
        '🇱🇮',
        'li',
        '423',
        false
    ),
    (
        'lk',
        'AS',
        'Sri Lanka',
        '🇱🇰',
        'lk',
        '94',
        false
    ),
    ('lr', 'AF', 'Liberia', '🇱🇷', 'lr', '231', false),
    ('ls', 'AF', 'Lesotho', '🇱🇸', 'ls', '266', false),
    (
        'lt',
        'EU',
        'Lithuania',
        '🇱🇹',
        'lt',
        '370',
        true
    ),
    (
        'lu',
        'EU',
        'Luxembourg',
        '🇱🇺',
        'lu',
        '352',
        true
    ),
    ('lv', 'EU', 'Latvia', '🇱🇻', 'lv', '371', true),
    ('ly', 'AF', 'Libya', '🇱🇾', 'ly', '218', false),
    ('ma', 'AF', 'Morocco', '🇲🇦', 'ma', '212', false),
    ('mc', 'EU', 'Monaco', '🇲🇨', 'mc', '377', false),
    ('md', 'EU', 'Moldova', '🇲🇩', 'md', '373', false),
    (
        'me',
        'EU',
        'Montenegro',
        '🇲🇪',
        'me',
        '382',
        false
    ),
    (
        'mf',
        'NA',
        'Saint Martin',
        '🇲🇫',
        'fr',
        '590',
        false
    ),
    (
        'mg',
        'AF',
        'Madagascar',
        '🇲🇬',
        'mg',
        '261',
        false
    ),
    (
        'mh',
        'OC',
        'Marshall Islands',
        '🇲🇭',
        'mh',
        '692',
        false
    ),
    (
        'mk',
        'EU',
        'Macedonia',
        '🇲🇰',
        'mk',
        '389',
        false
    ),
    ('ml', 'AF', 'Mali', '🇲🇱', 'ml', '223', false),
    ('mm', 'AS', 'Myanmar', '🇲🇲', 'mm', '95', false),
    (
        'mn',
        'AS',
        'Mongolia',
        '🇲🇳',
        'mn',
        '976',
        false
    ),
    ('mo', 'AS', 'Macau', '🇲🇴', 'mo', '853', false),
    (
        'mp',
        'OC',
        'Northern Mariana Islands',
        '🇲🇵',
        'mp',
        '1670',
        false
    ),
    (
        'mq',
        'NA',
        'Martinique',
        '🇲🇶',
        'mq',
        '596',
        false
    ),
    (
        'mr',
        'AF',
        'Mauritania',
        '🇲🇷',
        'mr',
        '222',
        false
    ),
    (
        'ms',
        'NA',
        'Montserrat',
        '🇲🇸',
        'ms',
        '1664',
        false
    ),
    ('mt', 'EU', 'Malta', '🇲🇹', 'mt', '356', true),
    (
        'mu',
        'AF',
        'Mauritius',
        '🇲🇺',
        'mu',
        '230',
        false
    ),
    (
        'mv',
        'AS',
        'Maldives',
        '🇲🇻',
        'mv',
        '960',
        false
    ),
    ('mw', 'AF', 'Malawi', '🇲🇼', 'mw', '265', false),
    ('mx', 'NA', 'Mexico', '🇲🇽', 'mx', '52', false),
    ('my', 'AS', 'Malaysia', '🇲🇾', 'my', '60', false),
    (
        'mz',
        'AF',
        'Mozambique',
        '🇲🇿',
        'mz',
        '258',
        false
    ),
    ('na', 'AF', 'Namibia', '🇳🇦', 'na', '264', false),
    (
        'nc',
        'OC',
        'New Caledonia',
        '🇳🇨',
        'nc',
        '687',
        false
    ),
    ('ne', 'AF', 'Niger', '🇳🇪', 'ne', '227', false),
    (
        'nf',
        'OC',
        'Norfolk Island',
        '🇳🇫',
        'nf',
        '672',
        false
    ),
    ('ng', 'AF', 'Nigeria', '🇳🇬', 'ng', '234', false),
    (
        'ni',
        'NA',
        'Nicaragua',
        '🇳🇮',
        'ni',
        '505',
        false
    ),
    (
        'nl',
        'EU',
        'Netherlands',
        '🇳🇱',
        'nl',
        '31',
        true
    ),
    ('no', 'EU', 'Norway', '🇳🇴', 'no', '47', false),
    ('np', 'AS', 'Nepal', '🇳🇵', 'np', '977', false),
    ('nr', 'OC', 'Nauru', '🇳🇷', 'nr', '674', false),
    ('nu', 'OC', 'Niue', '🇳🇺', 'nu', '683', false),
    (
        'nz',
        'OC',
        'New Zealand',
        '🇳🇿',
        'nz',
        '64',
        false
    ),
    ('om', 'AS', 'Oman', '🇴🇲', 'om', '968', false),
    ('pa', 'NA', 'Panama', '🇵🇦', 'pa', '507', false),
    ('pe', 'SA', 'Peru', '🇵🇪', 'pe', '51', false),
    (
        'pf',
        'OC',
        'French Polynesia',
        '🇵🇫',
        'pf',
        '689',
        false
    ),
    (
        'pg',
        'OC',
        'Papua New Guinea',
        '🇵🇬',
        'pg',
        '675',
        false
    ),
    (
        'ph',
        'AS',
        'Philippines',
        '🇵🇭',
        'ph',
        '63',
        false
    ),
    ('pk', 'AS', 'Pakistan', '🇵🇰', 'pk', '92', false),
    ('pl', 'EU', 'Poland', '🇵🇱', 'pl', '48', true),
    (
        'pm',
        'NA',
        'Saint Pierre and Miquelon',
        '🇵🇲',
        'pm',
        '508',
        false
    ),
    (
        'pn',
        'OC',
        'Pitcairn Islands',
        '🇵🇳',
        'pn',
        '64',
        false
    ),
    (
        'pr',
        'NA',
        'Puerto Rico',
        '🇵🇷',
        'pr',
        '1787,1939',
        false
    ),
    (
        'ps',
        'AS',
        'Palestine',
        '🇵🇸',
        'ps',
        '970',
        false
    ),
    ('pt', 'EU', 'Portugal', '🇵🇹', 'pt', '351', true),
    ('pw', 'OC', 'Palau', '🇵🇼', 'pw', '680', false),
    (
        'py',
        'SA',
        'Paraguay',
        '🇵🇾',
        'py',
        '595',
        false
    ),
    ('qa', 'AS', 'Qatar', '🇶🇦', 'qa', '974', false),
    ('re', 'AF', 'Réunion', '🇷🇪', 're', '262', false),
    ('ro', 'EU', 'Romania', '🇷🇴', 'ro', '40', true),
    ('rs', 'EU', 'Serbia', '🇷🇸', 'rs', '381', false),
    ('ru', 'EU', 'Russia', '🇷🇺', 'ru', '7', false),
    ('rw', 'AF', 'Rwanda', '🇷🇼', 'rw', '250', false),
    (
        'sa',
        'AS',
        'Saudi Arabia',
        '🇸🇦',
        'sa',
        '966',
        false
    ),
    (
        'sb',
        'OC',
        'Solomon Islands',
        '🇸🇧',
        'sb',
        '677',
        false
    ),
    (
        'sc',
        'AF',
        'Seychelles',
        '🇸🇨',
        'sc',
        '248',
        false
    ),
    ('sd', 'AF', 'Sudan', '🇸🇩', 'sd', '249', false),
    ('se', 'EU', 'Sweden', '🇸🇪', 'se', '46', true),
    (
        'sg',
        'AS',
        'Singapore',
        '🇸🇬',
        'sg',
        '65',
        false
    ),
    (
        'sh',
        'AF',
        'Saint Helena',
        '🇸🇭',
        '',
        '290',
        false
    ),
    ('si', 'EU', 'Slovenia', '🇸🇮', 'si', '386', true),
    (
        'sj',
        'EU',
        'Svalbard and Jan Mayen',
        '🇸🇯',
        'sj',
        '4779',
        false
    ),
    ('sk', 'EU', 'Slovakia', '🇸🇰', 'sk', '421', true),
    (
        'sl',
        'AF',
        'Sierra Leone',
        '🇸🇱',
        'sl',
        '232',
        false
    ),
    (
        'sm',
        'EU',
        'San Marino',
        '🇸🇲',
        'sm',
        '378',
        false
    ),
    ('sn', 'AF', 'Senegal', '🇸🇳', 'sn', '221', false),
    ('so', 'AF', 'Somalia', '🇸🇴', 'so', '252', false),
    (
        'sr',
        'SA',
        'Suriname',
        '🇸🇷',
        'sr',
        '597',
        false
    ),
    (
        'ss',
        'AF',
        'South Sudan',
        '🇸🇸',
        'ss',
        '211',
        false
    ),
    (
        'st',
        'AF',
        'São Tomé and Príncipe',
        '🇸🇹',
        'st',
        '239',
        false
    ),
    (
        'sv',
        'NA',
        'El Salvador',
        '🇸🇻',
        'sv',
        '503',
        false
    ),
    (
        'sx',
        'NA',
        'Sint Maarten',
        '🇸🇽',
        'sx',
        '1721',
        false
    ),
    ('sy', 'AS', 'Syria', '🇸🇾', 'sy', '963', false),
    (
        'sz',
        'AF',
        'Swaziland',
        '🇸🇿',
        'sz',
        '268',
        false
    ),
    (
        'tc',
        'NA',
        'Turks and Caicos Islands',
        '🇹🇨',
        'tc',
        '1649',
        false
    ),
    ('td', 'AF', 'Chad', '🇹🇩', 'td', '235', false),
    (
        'tf',
        'AN',
        'French Southern and Antarctic Lands',
        '🇹🇫',
        'tf',
        '',
        false
    ),
    ('tg', 'AF', 'Togo', '🇹🇬', 'tg', '228', false),
    ('th', 'AS', 'Thailand', '🇹🇭', 'th', '66', false),
    (
        'tj',
        'AS',
        'Tajikistan',
        '🇹🇯',
        'tj',
        '992',
        false
    ),
    ('tk', 'OC', 'Tokelau', '🇹🇰', 'tk', '690', false),
    (
        'tl',
        'OC',
        'Timor-Leste',
        '🇹🇱',
        'tl',
        '670',
        false
    ),
    (
        'tm',
        'AS',
        'Turkmenistan',
        '🇹🇲',
        'tm',
        '993',
        false
    ),
    ('tn', 'AF', 'Tunisia', '🇹🇳', 'tn', '216', false),
    ('to', 'OC', 'Tonga', '🇹🇴', 'to', '676', false),
    ('tr', 'AS', 'Turkey', '🇹🇷', 'tr', '90', false),
    (
        'tt',
        'NA',
        'Trinidad and Tobago',
        '🇹🇹',
        'tt',
        '1868',
        false
    ),
    ('tv', 'OC', 'Tuvalu', '🇹🇻', 'tv', '688', false),
    ('tw', 'AS', 'Taiwan', '🇹🇼', 'tw', '886', false),
    (
        'tz',
        'AF',
        'Tanzania',
        '🇹🇿',
        'tz',
        '255',
        false
    ),
    ('ua', 'EU', 'Ukraine', '🇺🇦', 'ua', '380', false),
    ('ug', 'AF', 'Uganda', '🇺🇬', 'ug', '256', false),
    (
        'um',
        'OC',
        'United States Minor Outlying Islands',
        '🇺🇲',
        'us',
        '',
        false
    ),
    (
        'us',
        'NA',
        'United States',
        '🇺🇸',
        'us',
        '1',
        false
    ),
    ('uy', 'SA', 'Uruguay', '🇺🇾', 'uy', '598', false),
    (
        'uz',
        'AS',
        'Uzbekistan',
        '🇺🇿',
        'uz',
        '998',
        false
    ),
    (
        'va',
        'EU',
        'Vatican City',
        '🇻🇦',
        'va',
        '3906698,379',
        false
    ),
    (
        'vc',
        'NA',
        'Saint Vincent and the Grenadines',
        '🇻🇨',
        'vc',
        '1784',
        false
    ),
    (
        've',
        'SA',
        'Venezuela',
        '🇻🇪',
        've',
        '58',
        false
    ),
    (
        'vg',
        'NA',
        'British Virgin Islands',
        '🇻🇬',
        'vg',
        '1284',
        false
    ),
    (
        'vi',
        'NA',
        'United States Virgin Islands',
        '🇻🇮',
        'vi',
        '1340',
        false
    ),
    ('vn', 'AS', 'Vietnam', '🇻🇳', 'vn', '84', false),
    ('vu', 'OC', 'Vanuatu', '🇻🇺', 'vu', '678', false),
    (
        'wf',
        'OC',
        'Wallis and Futuna',
        '🇼🇫',
        'wf',
        '681',
        false
    ),
    ('ws', 'OC', 'Samoa', '🇼🇸', 'ws', '685', false),
    ('xk', 'EU', 'Kosovo', '🇽🇰', '', '383', false),
    ('ye', 'AS', 'Yemen', '🇾🇪', 'ye', '967', false),
    ('yt', 'AF', 'Mayotte', '🇾🇹', 'yt', '262', false),
    (
        'za',
        'AF',
        'South Africa',
        '🇿🇦',
        'za',
        '27',
        false
    ),
    ('zm', 'AF', 'Zambia', '🇿🇲', 'zm', '260', false),
    (
        'zw',
        'AF',
        'Zimbabwe',
        '🇿🇼',
        'zw',
        '263',
        false
    );

INSERT INTO
    iso.languages ("id", "name")
VALUES
    ('afr', 'Afrikaans'),
    ('amh', 'Amharic'),
    ('ara', 'Arabic'),
    ('arc', 'Aramaic'),
    ('aym', 'Aymara'),
    ('aze', 'Azerbaijani'),
    ('bar', 'Austro-Bavarian German'),
    ('bel', 'Belarusian'),
    ('ben', 'Bengali'),
    ('ber', 'Berber'),
    ('bis', 'Bislama'),
    ('bjz', 'Belizean Creole'),
    ('bos', 'Bosnian'),
    ('bul', 'Bulgarian'),
    ('bwg', 'Chibarwe'),
    ('cal', 'Carolinian'),
    ('cat', 'Catalan'),
    ('ces', 'Czech'),
    ('cha', 'Chamorro'),
    ('ckb', 'Sorani'),
    ('cmn', 'Mandarin'),
    ('crs', 'Seychellois Creole'),
    ('dan', 'Danish'),
    ('deu', 'German'),
    ('div', 'Maldivian'),
    ('dzo', 'Dzongkha'),
    ('ell', 'Greek'),
    ('eng', 'English'),
    ('est', 'Estonian'),
    ('eus', 'Basque'),
    ('fao', 'Faroese'),
    ('fas', 'Persian'),
    ('fij', 'Fijian'),
    ('fil', 'Filipino'),
    ('fin', 'Finnish'),
    ('fra', 'French'),
    ('gil', 'Gilbertese'),
    ('gle', 'Irish'),
    ('glg', 'Galician'),
    ('glv', 'Manx'),
    ('grn', 'Guaraní'),
    ('gsw', 'Swiss German'),
    ('hat', 'Haitian Creole'),
    ('heb', 'Hebrew'),
    ('her', 'Herero'),
    ('hgm', 'Khoekhoe'),
    ('hif', 'Fiji Hindi'),
    ('hin', 'Hindi'),
    ('hmo', 'Hiri Motu'),
    ('hrv', 'Croatian'),
    ('hun', 'Hungarian'),
    ('hye', 'Armenian'),
    ('ind', 'Indonesian'),
    ('isl', 'Icelandic'),
    ('ita', 'Italian'),
    ('jam', 'Jamaican Patois'),
    ('jpn', 'Japanese'),
    ('kal', 'Greenlandic'),
    ('kat', 'Georgian'),
    ('kaz', 'Kazakh'),
    ('kck', 'Kalanga'),
    ('khi', 'Khoisan'),
    ('khm', 'Khmer'),
    ('kin', 'Kinyarwanda'),
    ('kir', 'Kyrgyz'),
    ('kon', 'Kikongo'),
    ('kor', 'Korean'),
    ('kwn', 'Kwangali'),
    ('lao', 'Lao'),
    ('lat', 'Latin'),
    ('lav', 'Latvian'),
    ('lin', 'Lingala'),
    ('lit', 'Lithuanian'),
    ('loz', 'Lozi'),
    ('ltz', 'Luxembourgish'),
    ('lua', 'Tshiluba'),
    ('mah', 'Marshallese'),
    ('mey', 'Hassaniya'),
    ('mfe', 'Mauritian Creole'),
    ('mkd', 'Macedonian'),
    ('mlg', 'Malagasy'),
    ('mlt', 'Maltese'),
    ('mon', 'Mongolian'),
    ('mri', 'Māori'),
    ('msa', 'Malay'),
    ('mya', 'Burmese'),
    ('nau', 'Nauru'),
    ('nbl', 'Southern Ndebele'),
    ('ndc', 'Ndau'),
    ('nde', 'Northern Ndebele'),
    ('ndo', 'Ndonga'),
    ('nep', 'Nepali'),
    ('nfr', 'Guernésiais'),
    ('niu', 'Niuean'),
    ('nld', 'Dutch'),
    ('nno', 'Norwegian Nynorsk'),
    ('nob', 'Norwegian Bokmål'),
    ('nor', 'Norwegian'),
    ('nrf', 'Jèrriais'),
    ('nso', 'Northern Sotho'),
    ('nya', 'Chewa'),
    ('nzs', 'New Zealand Sign Language'),
    ('oci', 'Occitan'),
    ('pap', 'Papiamento'),
    ('pau', 'Palauan'),
    ('pih', 'Norfuk'),
    ('pol', 'Polish'),
    ('por', 'Portuguese'),
    ('prs', 'Dari'),
    ('pus', 'Pashto'),
    ('que', 'Quechua'),
    ('rar', 'Cook Islands Māori'),
    ('roh', 'Romansh'),
    ('ron', 'Romanian'),
    ('run', 'Kirundi'),
    ('rus', 'Russian'),
    ('sag', 'Sango'),
    ('sin', 'Sinhala'),
    ('slk', 'Slovak'),
    ('slv', 'Slovene'),
    ('smi', 'Sami'),
    ('smo', 'Samoan'),
    ('sna', 'Shona'),
    ('som', 'Somali'),
    ('sot', 'Sotho'),
    ('spa', 'Spanish'),
    ('sqi', 'Albanian'),
    ('srd', 'Sardinian'),
    ('srp', 'Serbian'),
    ('ssw', 'Swazi'),
    ('swa', 'Swahili'),
    ('swe', 'Swedish'),
    ('tam', 'Tamil'),
    ('tet', 'Tetum'),
    ('tgk', 'Tajik'),
    ('tha', 'Thai'),
    ('tir', 'Tigrinya'),
    ('tkl', 'Tokelauan'),
    ('toi', 'Tonga'),
    ('ton', 'Tongan'),
    ('tpi', 'Tok Pisin'),
    ('tsn', 'Tswana'),
    ('tso', 'Tsonga'),
    ('tuk', 'Turkmen'),
    ('tur', 'Turkish'),
    ('tvl', 'Tuvaluan'),
    ('ukr', 'Ukrainian'),
    ('urd', 'Urdu'),
    ('uzb', 'Uzbek'),
    ('ven', 'Venda'),
    ('vie', 'Vietnamese'),
    ('xho', 'Xhosa'),
    ('zdj', 'Comorian'),
    ('zho', 'Chinese'),
    ('zib', 'Zimbabwean Sign Language'),
    ('zul', 'Zulu');

INSERT INTO
    iso.currencies ("id", "name")
VALUES
    ('AED', 'UAE Dirham'),
    ('AFN', 'Afghani'),
    ('ALL', 'Lek'),
    ('AMD', 'Armenian Dram'),
    ('ANG', 'Netherlands Antillean Guilder'),
    ('AOA', 'Kwanza'),
    ('ARS', 'Argentine Peso'),
    ('AUD', 'Australian Dollar'),
    ('AWG', 'Aruban Florin'),
    ('AZN', 'Azerbaijanian Manat'),
    ('BAM', 'Convertible Mark'),
    ('BBD', 'Barbados Dollar'),
    ('BDT', 'Taka'),
    ('BGN', 'Bulgarian Lev'),
    ('BHD', 'Bahraini Dinar'),
    ('BIF', 'Burundi Franc'),
    ('BMD', 'Bermudian Dollar'),
    ('BND', 'Brunei Dollar'),
    ('BOB', 'Boliviano'),
    ('BRL', 'Brazilian Real'),
    ('BSD', 'Bahamian Dollar'),
    ('BTN', 'Bhutanese ngultrum'),
    ('BWP', 'Pula'),
    ('BYN', 'Belarussian Ruble'),
    ('BZD', 'Belize Dollar'),
    ('CAD', 'Canadian Dollar'),
    ('CDF', 'Congolese franc'),
    ('CHF', 'Swiss Franc'),
    ('CLP', 'Chilean Peso'),
    ('CNY', 'Yuan Renminbi'),
    ('COP', 'Colombian Peso'),
    ('CRC', 'Costa Rican Colon'),
    ('CUP', 'Cuban Peso'),
    ('CVE', 'Cabo Verde Escudo'),
    ('CZK', 'Czech Koruna'),
    ('DJF', 'Djibouti Franc'),
    ('DKK', 'Danish Krone'),
    ('DOP', 'Dominican Peso'),
    ('DZD', 'Algerian Dinar'),
    ('EGP', 'Egyptian Pound'),
    ('ERN', 'Nakfa'),
    ('ETB', 'Ethiopian Birr'),
    ('EUR', 'Euro'),
    ('FJD', 'Fiji Dollar'),
    ('FKP', 'Falkland Islands Pound'),
    ('GBP', 'Pound Sterling'),
    ('GEL', 'Lari'),
    ('GHS', 'Ghana Cedi'),
    ('GIP', 'Gibraltar Pound'),
    ('GMD', 'Dalasi'),
    ('GNF', 'Guinea Franc'),
    ('GTQ', 'Quetzal'),
    ('GYD', 'Guyana Dollar'),
    ('HKD', 'Hong Kong dollar'),
    ('HNL', 'Lempira'),
    ('HRK', 'Croatian Kuna'),
    ('HTG', 'Haitian gourde'),
    ('HUF', 'Forint'),
    ('IDR', 'Rupiah'),
    ('ILS', 'Israeli new shekel'),
    ('INR', 'Indian Rupee'),
    ('IQD', 'Iraqi Dinar'),
    ('IRR', 'Iranian rial'),
    ('ISK', 'Iceland Krona'),
    ('JMD', 'Jamaican Dollar'),
    ('JOD', 'Jordanian Dinar'),
    ('JPY', 'Yen'),
    ('KES', 'Kenyan Shilling'),
    ('KGS', 'Som'),
    ('KHR', 'Riel'),
    ('KMF', 'Comoro Franc'),
    ('KPW', 'North Korean won'),
    ('KRW', 'South Korean won'),
    ('KWD', 'Kuwaiti Dinar'),
    ('KYD', 'Cayman Islands Dollar'),
    ('KZT', 'Tenge'),
    ('LAK', 'Kip'),
    ('LBP', 'Lebanese Pound'),
    ('LKR', 'Sri Lanka Rupee'),
    ('LRD', 'Liberian Dollar'),
    ('LSL', 'Lesotho loti'),
    ('LYD', 'Libyan Dinar'),
    ('MAD', 'Moroccan Dirham'),
    ('MDL', 'Moldovan leu'),
    ('MGA', 'Malagasy Ariary'),
    ('MKD', 'Macedonian denar'),
    ('MMK', 'Kyat'),
    ('MNT', 'Tugrik'),
    ('MOP', 'Macanese pataca'),
    ('MRO', 'Ouguiya'),
    ('MUR', 'Mauritius Rupee'),
    ('MVR', 'Rufiyaa'),
    ('MWK', 'Kwacha'),
    ('MXN', 'Mexican Peso'),
    ('MYR', 'Malaysian Ringgit'),
    ('MZN', 'Mozambique Metical'),
    ('NAD', 'Namibian dollar'),
    ('NGN', 'Naira'),
    ('NIO', 'Cordoba Oro'),
    ('NOK', 'Norwegian krone'),
    ('NPR', 'Nepalese Rupee'),
    ('NZD', 'New Zealand Dollar'),
    ('OMR', 'Rial Omani'),
    ('PAB', 'Panamanian balboa'),
    ('PEN', 'Nuevo Sol'),
    ('PGK', 'Kina'),
    ('PHP', 'Philippine Peso'),
    ('PKR', 'Pakistan Rupee'),
    ('PLN', 'Zloty'),
    ('PYG', 'Guarani'),
    ('QAR', 'Qatari Rial'),
    ('RON', 'New Romanian Leu'),
    ('RSD', 'Serbian Dinar'),
    ('RUB', 'Russian Ruble'),
    ('RWF', 'Rwanda Franc'),
    ('SAR', 'Saudi Riyal'),
    ('SBD', 'Solomon Islands Dollar'),
    ('SCR', 'Seychelles Rupee'),
    ('SDG', 'Sudanese Pound'),
    ('SEK', 'Swedish Krona'),
    ('SGD', 'Singapore Dollar'),
    ('SHP', 'Saint Helena pound'),
    ('SLL', 'Leone'),
    ('SOS', 'Somali Shilling'),
    ('SRD', 'Surinam Dollar'),
    ('SSP', 'South Sudanese Pound'),
    ('STD', 'Dobra'),
    ('SVC', 'Salvadoran colón'),
    ('SYP', 'Syrian Pound'),
    ('SZL', 'Lilangeni'),
    ('THB', 'Baht'),
    ('TJS', 'Somoni'),
    ('TMT', 'Turkmenistan New Manat'),
    ('TND', 'Tunisian Dinar'),
    ('TOP', 'Pa’anga'),
    ('TRY', 'Turkish Lira'),
    ('TTD', 'Trinidad and Tobago Dollar'),
    ('TWD', 'New Taiwan dollar'),
    ('TZS', 'Tanzanian shilling'),
    ('UAH', 'Hryvnia'),
    ('UGX', 'Uganda Shilling'),
    ('USD', 'US Dollar'),
    ('UYU', 'Peso Uruguayo'),
    ('UZS', 'Uzbekistan Sum'),
    ('VES', 'Venezuelan bolívar soberano'),
    ('VND', 'Dong'),
    ('VUV', 'Vatu'),
    ('WST', 'Tala'),
    ('XAF', 'CFA Franc BEAC'),
    ('XCD', 'East Caribbean Dollar'),
    ('XOF', 'CFA Franc BCEAO'),
    ('XPF', 'CFP franc (franc Pacifique)'),
    ('YER', 'Yemeni Rial'),
    ('ZAR', 'Rand'),
    ('ZMW', 'Zambian Kwacha'),
    ('ZWL', 'Zimbabwe Dollar');

INSERT INTO
    iso.country_languages ("country_id", "language_id")
VALUES
    ('ad', 'cat'),
    ('ae', 'ara'),
    ('af', 'prs'),
    ('af', 'pus'),
    ('af', 'tuk'),
    ('ag', 'eng'),
    ('ai', 'eng'),
    ('al', 'sqi'),
    ('am', 'hye'),
    ('am', 'rus'),
    ('ao', 'por'),
    ('ar', 'grn'),
    ('ar', 'spa'),
    ('as', 'eng'),
    ('as', 'smo'),
    ('at', 'bar'),
    ('au', 'eng'),
    ('aw', 'nld'),
    ('aw', 'pap'),
    ('ax', 'swe'),
    ('az', 'aze'),
    ('az', 'rus'),
    ('ba', 'bos'),
    ('ba', 'hrv'),
    ('ba', 'srp'),
    ('bb', 'eng'),
    ('bd', 'ben'),
    ('be', 'deu'),
    ('be', 'fra'),
    ('be', 'nld'),
    ('bf', 'fra'),
    ('bg', 'bul'),
    ('bh', 'ara'),
    ('bi', 'fra'),
    ('bi', 'run'),
    ('bj', 'fra'),
    ('bl', 'fra'),
    ('bm', 'eng'),
    ('bn', 'msa'),
    ('bo', 'aym'),
    ('bo', 'grn'),
    ('bo', 'que'),
    ('bo', 'spa'),
    ('bq', 'eng'),
    ('br', 'por'),
    ('bs', 'eng'),
    ('bt', 'dzo'),
    ('bv', 'nor'),
    ('bw', 'eng'),
    ('bw', 'tsn'),
    ('by', 'bel'),
    ('by', 'rus'),
    ('bz', 'bjz'),
    ('bz', 'eng'),
    ('bz', 'spa'),
    ('ca', 'eng'),
    ('ca', 'fra'),
    ('cc', 'eng'),
    ('cd', 'fra'),
    ('cd', 'kon'),
    ('cd', 'lin'),
    ('cd', 'lua'),
    ('cd', 'swa'),
    ('cf', 'fra'),
    ('cf', 'sag'),
    ('cg', 'fra'),
    ('cg', 'kon'),
    ('cg', 'lin'),
    ('ch', 'fra'),
    ('ch', 'gsw'),
    ('ch', 'ita'),
    ('ch', 'roh'),
    ('ci', 'fra'),
    ('ck', 'eng'),
    ('ck', 'rar'),
    ('cl', 'spa'),
    ('cm', 'eng'),
    ('cm', 'fra'),
    ('cn', 'cmn'),
    ('co', 'spa'),
    ('cr', 'spa'),
    ('cu', 'spa'),
    ('cv', 'por'),
    ('cw', 'eng'),
    ('cw', 'nld'),
    ('cw', 'pap'),
    ('cx', 'eng'),
    ('cy', 'ell'),
    ('cy', 'tur'),
    ('cz', 'ces'),
    ('cz', 'slk'),
    ('de', 'deu'),
    ('dj', 'ara'),
    ('dj', 'fra'),
    ('dk', 'dan'),
    ('dm', 'eng'),
    ('do', 'spa'),
    ('dz', 'ara'),
    ('ec', 'spa'),
    ('ee', 'est'),
    ('eg', 'ara'),
    ('eh', 'ber'),
    ('eh', 'mey'),
    ('eh', 'spa'),
    ('er', 'ara'),
    ('er', 'eng'),
    ('er', 'tir'),
    ('es', 'cat'),
    ('es', 'eus'),
    ('es', 'glg'),
    ('es', 'oci'),
    ('es', 'spa'),
    ('et', 'amh'),
    ('fi', 'fin'),
    ('fi', 'swe'),
    ('fj', 'eng'),
    ('fj', 'fij'),
    ('fj', 'hif'),
    ('fk', 'eng'),
    ('fm', 'eng'),
    ('fo', 'dan'),
    ('fo', 'fao'),
    ('fr', 'fra'),
    ('ga', 'fra'),
    ('gb', 'eng'),
    ('gd', 'eng'),
    ('ge', 'kat'),
    ('gf', 'fra'),
    ('gg', 'eng'),
    ('gg', 'fra'),
    ('gg', 'nfr'),
    ('gh', 'eng'),
    ('gi', 'eng'),
    ('gl', 'kal'),
    ('gm', 'eng'),
    ('gn', 'fra'),
    ('gp', 'fra'),
    ('gq', 'fra'),
    ('gq', 'por'),
    ('gq', 'spa'),
    ('gr', 'ell'),
    ('gs', 'eng'),
    ('gt', 'spa'),
    ('gu', 'cha'),
    ('gu', 'eng'),
    ('gu', 'spa'),
    ('gw', 'por'),
    ('gy', 'eng'),
    ('hk', 'eng'),
    ('hk', 'zho'),
    ('hm', 'eng'),
    ('hn', 'spa'),
    ('hr', 'hrv'),
    ('ht', 'fra'),
    ('ht', 'hat'),
    ('hu', 'hun'),
    ('id', 'ind'),
    ('ie', 'eng'),
    ('ie', 'gle'),
    ('il', 'ara'),
    ('il', 'heb'),
    ('im', 'eng'),
    ('im', 'glv'),
    ('in', 'eng'),
    ('in', 'hin'),
    ('in', 'tam'),
    ('io', 'eng'),
    ('iq', 'ara'),
    ('iq', 'arc'),
    ('iq', 'ckb'),
    ('ir', 'fas'),
    ('is', 'isl'),
    ('it', 'bar'),
    ('it', 'ita'),
    ('it', 'srd'),
    ('je', 'eng'),
    ('je', 'fra'),
    ('je', 'nrf'),
    ('jm', 'eng'),
    ('jm', 'jam'),
    ('jo', 'ara'),
    ('jp', 'jpn'),
    ('ke', 'eng'),
    ('ke', 'swa'),
    ('kg', 'kir'),
    ('kg', 'rus'),
    ('kh', 'khm'),
    ('ki', 'eng'),
    ('ki', 'gil'),
    ('km', 'ara'),
    ('km', 'fra'),
    ('km', 'zdj'),
    ('kn', 'eng'),
    ('kp', 'kor'),
    ('kr', 'kor'),
    ('kw', 'ara'),
    ('ky', 'eng'),
    ('kz', 'kaz'),
    ('kz', 'rus'),
    ('la', 'lao'),
    ('lb', 'ara'),
    ('lb', 'fra'),
    ('lc', 'eng'),
    ('li', 'deu'),
    ('lk', 'sin'),
    ('lk', 'tam'),
    ('lr', 'eng'),
    ('ls', 'eng'),
    ('ls', 'sot'),
    ('lt', 'lit'),
    ('lu', 'deu'),
    ('lu', 'fra'),
    ('lu', 'ltz'),
    ('lv', 'lav'),
    ('ly', 'ara'),
    ('ma', 'ara'),
    ('ma', 'ber'),
    ('mc', 'fra'),
    ('md', 'ron'),
    ('me', 'srp'),
    ('mf', 'fra'),
    ('mg', 'fra'),
    ('mg', 'mlg'),
    ('mh', 'eng'),
    ('mh', 'mah'),
    ('mk', 'mkd'),
    ('ml', 'fra'),
    ('mm', 'mya'),
    ('mn', 'mon'),
    ('mo', 'por'),
    ('mo', 'zho'),
    ('mp', 'cal'),
    ('mp', 'cha'),
    ('mp', 'eng'),
    ('mq', 'fra'),
    ('mr', 'ara'),
    ('ms', 'eng'),
    ('mt', 'eng'),
    ('mt', 'mlt'),
    ('mu', 'eng'),
    ('mu', 'fra'),
    ('mu', 'mfe'),
    ('mv', 'div'),
    ('mw', 'eng'),
    ('mw', 'nya'),
    ('mx', 'spa'),
    ('my', 'eng'),
    ('my', 'msa'),
    ('mz', 'por'),
    ('na', 'afr'),
    ('na', 'deu'),
    ('na', 'eng'),
    ('na', 'her'),
    ('na', 'hgm'),
    ('na', 'kwn'),
    ('na', 'loz'),
    ('na', 'ndo'),
    ('na', 'tsn'),
    ('nc', 'fra'),
    ('ne', 'fra'),
    ('nf', 'eng'),
    ('nf', 'pih'),
    ('ng', 'eng'),
    ('ni', 'spa'),
    ('nl', 'nld'),
    ('no', 'nno'),
    ('no', 'nob'),
    ('no', 'smi'),
    ('np', 'nep'),
    ('nr', 'eng'),
    ('nr', 'nau'),
    ('nu', 'eng'),
    ('nu', 'niu'),
    ('nz', 'eng'),
    ('nz', 'mri'),
    ('nz', 'nzs'),
    ('om', 'ara'),
    ('pa', 'spa'),
    ('pe', 'aym'),
    ('pe', 'que'),
    ('pe', 'spa'),
    ('pf', 'fra'),
    ('pg', 'eng'),
    ('pg', 'hmo'),
    ('pg', 'tpi'),
    ('ph', 'eng'),
    ('ph', 'fil'),
    ('pk', 'eng'),
    ('pk', 'urd'),
    ('pl', 'pol'),
    ('pm', 'fra'),
    ('pn', 'eng'),
    ('pr', 'eng'),
    ('pr', 'spa'),
    ('ps', 'ara'),
    ('pt', 'por'),
    ('pw', 'eng'),
    ('pw', 'pau'),
    ('py', 'grn'),
    ('py', 'spa'),
    ('qa', 'ara'),
    ('re', 'fra'),
    ('ro', 'ron'),
    ('rs', 'srp'),
    ('ru', 'rus'),
    ('rw', 'eng'),
    ('rw', 'fra'),
    ('rw', 'kin'),
    ('sa', 'ara'),
    ('sb', 'eng'),
    ('sc', 'crs'),
    ('sc', 'eng'),
    ('sc', 'fra'),
    ('sd', 'ara'),
    ('sd', 'eng'),
    ('se', 'swe'),
    ('sg', 'cmn'),
    ('sg', 'eng'),
    ('sg', 'msa'),
    ('sg', 'tam'),
    ('sh', 'eng'),
    ('si', 'slv'),
    ('sj', 'nor'),
    ('sk', 'slk'),
    ('sl', 'eng'),
    ('sm', 'ita'),
    ('sn', 'fra'),
    ('so', 'ara'),
    ('so', 'som'),
    ('sr', 'nld'),
    ('ss', 'eng'),
    ('st', 'por'),
    ('sv', 'spa'),
    ('sx', 'eng'),
    ('sx', 'fra'),
    ('sx', 'nld'),
    ('sy', 'ara'),
    ('sz', 'eng'),
    ('sz', 'ssw'),
    ('tc', 'eng'),
    ('td', 'ara'),
    ('td', 'fra'),
    ('tf', 'fra'),
    ('tg', 'fra'),
    ('th', 'tha'),
    ('tj', 'rus'),
    ('tj', 'tgk'),
    ('tk', 'eng'),
    ('tk', 'smo'),
    ('tk', 'tkl'),
    ('tl', 'por'),
    ('tl', 'tet'),
    ('tm', 'rus'),
    ('tm', 'tuk'),
    ('tn', 'ara'),
    ('to', 'eng'),
    ('to', 'ton'),
    ('tr', 'tur'),
    ('tt', 'eng'),
    ('tv', 'eng'),
    ('tv', 'tvl'),
    ('tw', 'cmn'),
    ('tz', 'eng'),
    ('tz', 'swa'),
    ('ua', 'ukr'),
    ('ug', 'eng'),
    ('ug', 'swa'),
    ('um', 'eng'),
    ('us', 'eng'),
    ('uy', 'spa'),
    ('uz', 'rus'),
    ('uz', 'uzb'),
    ('va', 'ita'),
    ('va', 'lat'),
    ('vc', 'eng'),
    ('ve', 'spa'),
    ('vg', 'eng'),
    ('vi', 'eng'),
    ('vn', 'vie'),
    ('vu', 'bis'),
    ('vu', 'eng'),
    ('vu', 'fra'),
    ('wf', 'fra'),
    ('ws', 'eng'),
    ('ws', 'smo'),
    ('xk', 'sqi'),
    ('xk', 'srp'),
    ('ye', 'ara'),
    ('yt', 'fra'),
    ('za', 'afr'),
    ('za', 'eng'),
    ('za', 'nbl'),
    ('za', 'nso'),
    ('za', 'sot'),
    ('za', 'ssw'),
    ('za', 'tsn'),
    ('za', 'tso'),
    ('za', 'ven'),
    ('za', 'xho'),
    ('za', 'zul'),
    ('zm', 'eng'),
    ('zw', 'bwg'),
    ('zw', 'eng'),
    ('zw', 'kck'),
    ('zw', 'khi'),
    ('zw', 'ndc'),
    ('zw', 'nde'),
    ('zw', 'nya'),
    ('zw', 'sna'),
    ('zw', 'sot'),
    ('zw', 'toi'),
    ('zw', 'tsn'),
    ('zw', 'tso'),
    ('zw', 'ven'),
    ('zw', 'xho'),
    ('zw', 'zib');

INSERT INTO
    iso.country_currencies ("country_id", "currency_id")
VALUES
    ('ad', 'EUR'),
    ('ae', 'AED'),
    ('af', 'AFN'),
    ('ag', 'XCD'),
    ('ai', 'XCD'),
    ('al', 'ALL'),
    ('am', 'AMD'),
    ('ao', 'AOA'),
    ('ar', 'ARS'),
    ('as', 'USD'),
    ('at', 'EUR'),
    ('au', 'AUD'),
    ('aw', 'AWG'),
    ('ax', 'EUR'),
    ('az', 'AZN'),
    ('ba', 'BAM'),
    ('bb', 'BBD'),
    ('bd', 'BDT'),
    ('be', 'EUR'),
    ('bf', 'XOF'),
    ('bg', 'BGN'),
    ('bh', 'BHD'),
    ('bi', 'BIF'),
    ('bj', 'XOF'),
    ('bl', 'EUR'),
    ('bm', 'BMD'),
    ('bn', 'BND'),
    ('bo', 'BOB'),
    ('bq', 'USD'),
    ('br', 'BRL'),
    ('bs', 'BSD'),
    ('bt', 'BTN'),
    ('bv', 'NOK'),
    ('bw', 'BWP'),
    ('by', 'BYN'),
    ('bz', 'BZD'),
    ('ca', 'CAD'),
    ('cc', 'AUD'),
    ('cd', 'CDF'),
    ('cf', 'XAF'),
    ('cg', 'XAF'),
    ('ch', 'CHF'),
    ('ci', 'XOF'),
    ('ck', 'NZD'),
    ('cl', 'CLP'),
    ('cm', 'XAF'),
    ('cn', 'CNY'),
    ('co', 'COP'),
    ('cr', 'CRC'),
    ('cu', 'CUP'),
    ('cv', 'CVE'),
    ('cw', 'ANG'),
    ('cx', 'AUD'),
    ('cy', 'EUR'),
    ('cz', 'CZK'),
    ('de', 'EUR'),
    ('dj', 'DJF'),
    ('dk', 'DKK'),
    ('dm', 'XCD'),
    ('do', 'DOP'),
    ('dz', 'DZD'),
    ('ec', 'USD'),
    ('ee', 'EUR'),
    ('eg', 'EGP'),
    ('eh', 'MAD'),
    ('er', 'ERN'),
    ('es', 'EUR'),
    ('et', 'ETB'),
    ('fi', 'EUR'),
    ('fj', 'FJD'),
    ('fk', 'FKP'),
    ('fm', 'USD'),
    ('fo', 'DKK'),
    ('fr', 'EUR'),
    ('ga', 'XAF'),
    ('gb', 'GBP'),
    ('gd', 'XCD'),
    ('ge', 'GEL'),
    ('gf', 'EUR'),
    ('gg', 'GBP'),
    ('gh', 'GHS'),
    ('gi', 'GIP'),
    ('gl', 'DKK'),
    ('gm', 'GMD'),
    ('gn', 'GNF'),
    ('gp', 'EUR'),
    ('gq', 'XAF'),
    ('gr', 'EUR'),
    ('gs', 'GBP'),
    ('gt', 'GTQ'),
    ('gu', 'USD'),
    ('gw', 'XOF'),
    ('gy', 'GYD'),
    ('hk', 'HKD'),
    ('hm', 'AUD'),
    ('hn', 'HNL'),
    ('hr', 'HRK'),
    ('ht', 'HTG'),
    ('hu', 'HUF'),
    ('id', 'IDR'),
    ('ie', 'EUR'),
    ('il', 'ILS'),
    ('im', 'GBP'),
    ('in', 'INR'),
    ('io', 'USD'),
    ('iq', 'IQD'),
    ('ir', 'IRR'),
    ('is', 'ISK'),
    ('it', 'EUR'),
    ('je', 'GBP'),
    ('jm', 'JMD'),
    ('jo', 'JOD'),
    ('jp', 'JPY'),
    ('ke', 'KES'),
    ('kg', 'KGS'),
    ('kh', 'KHR'),
    ('ki', 'AUD'),
    ('km', 'KMF'),
    ('kn', 'XCD'),
    ('kp', 'KPW'),
    ('kr', 'KRW'),
    ('kw', 'KWD'),
    ('ky', 'KYD'),
    ('kz', 'KZT'),
    ('la', 'LAK'),
    ('lb', 'LBP'),
    ('lc', 'XCD'),
    ('li', 'CHF'),
    ('lk', 'LKR'),
    ('lr', 'LRD'),
    ('ls', 'LSL'),
    ('lt', 'EUR'),
    ('lu', 'EUR'),
    ('lv', 'EUR'),
    ('ly', 'LYD'),
    ('ma', 'MAD'),
    ('mc', 'EUR'),
    ('md', 'MDL'),
    ('me', 'EUR'),
    ('mf', 'EUR'),
    ('mg', 'MGA'),
    ('mh', 'USD'),
    ('mk', 'MKD'),
    ('ml', 'XOF'),
    ('mm', 'MMK'),
    ('mn', 'MNT'),
    ('mo', 'MOP'),
    ('mp', 'USD'),
    ('mq', 'EUR'),
    ('mr', 'MRO'),
    ('ms', 'XCD'),
    ('mt', 'EUR'),
    ('mu', 'MUR'),
    ('mv', 'MVR'),
    ('mw', 'MWK'),
    ('mx', 'MXN'),
    ('my', 'MYR'),
    ('mz', 'MZN'),
    ('na', 'NAD'),
    ('nc', 'XPF'),
    ('ne', 'XOF'),
    ('nf', 'AUD'),
    ('ng', 'NGN'),
    ('ni', 'NIO'),
    ('nl', 'EUR'),
    ('no', 'NOK'),
    ('np', 'NPR'),
    ('nr', 'AUD'),
    ('nu', 'NZD'),
    ('nz', 'NZD'),
    ('om', 'OMR'),
    ('pa', 'PAB'),
    ('pe', 'PEN'),
    ('pf', 'XPF'),
    ('pg', 'PGK'),
    ('ph', 'PHP'),
    ('pk', 'PKR'),
    ('pl', 'PLN'),
    ('pm', 'EUR'),
    ('pn', 'NZD'),
    ('pr', 'USD'),
    ('ps', 'ILS'),
    ('pt', 'EUR'),
    ('pw', 'USD'),
    ('py', 'PYG'),
    ('qa', 'QAR'),
    ('re', 'EUR'),
    ('ro', 'RON'),
    ('rs', 'RSD'),
    ('ru', 'RUB'),
    ('rw', 'RWF'),
    ('sa', 'SAR'),
    ('sb', 'SBD'),
    ('sc', 'SCR'),
    ('sd', 'SDG'),
    ('se', 'SEK'),
    ('sg', 'SGD'),
    ('sh', 'SHP'),
    ('si', 'EUR'),
    ('sj', 'NOK'),
    ('sk', 'EUR'),
    ('sl', 'SLL'),
    ('sm', 'EUR'),
    ('sn', 'XOF'),
    ('so', 'SOS'),
    ('sr', 'SRD'),
    ('ss', 'SSP'),
    ('st', 'STD'),
    ('sv', 'SVC'),
    ('sx', 'ANG'),
    ('sy', 'SYP'),
    ('sz', 'SZL'),
    ('tc', 'USD'),
    ('td', 'XAF'),
    ('tf', 'EUR'),
    ('tg', 'XOF'),
    ('th', 'THB'),
    ('tj', 'TJS'),
    ('tk', 'NZD'),
    ('tl', 'USD'),
    ('tm', 'TMT'),
    ('tn', 'TND'),
    ('to', 'TOP'),
    ('tr', 'TRY'),
    ('tt', 'TTD'),
    ('tv', 'AUD'),
    ('tw', 'TWD'),
    ('tz', 'TZS'),
    ('ua', 'UAH'),
    ('ug', 'UGX'),
    ('um', 'USD'),
    ('us', 'USD'),
    ('uy', 'UYU'),
    ('uz', 'UZS'),
    ('va', 'EUR'),
    ('vc', 'XCD'),
    ('ve', 'VES'),
    ('vg', 'USD'),
    ('vi', 'USD'),
    ('vn', 'VND'),
    ('vu', 'VUV'),
    ('wf', 'XPF'),
    ('ws', 'WST'),
    ('xk', 'EUR'),
    ('ye', 'YER'),
    ('yt', 'EUR'),
    ('za', 'ZAR'),
    ('zm', 'ZMW'),
    ('zw', 'ZWL');